//// =============================================================================
//// [C3I-SIL6-MSTS] MATHEMATICAL & SEMANTIC MODULE CONTRACT
//// =============================================================================
//// <c3i-module>
////   <identity>
////     <module>cepaf_gleam/ha/pid_tuner</module>
////     <fsharp-lineage>N/A — Pure Gleam Autonomous Telemetry PID Tuner</fsharp-lineage>
////   </identity>
////   <fractal-topology>
////     <layer>L0_CONSTITUTIONAL</layer>
////     <layer>L4_SYSTEM</layer>
////   </fractal-topology>
////   <compliance>
////     <stamp-controls>SC-PID-001, SC-SIL6-001, SC-JIDOKA-001, SC-MUDA-001</stamp-controls>
////   </compliance>
////   <algebraic-properties>
////     <property name="asymptotic-stability">Closed-loop error e(t) = lambda(t) - lambda* decays exponentially</property>
////     <property name="anti-windup">Integral state is strictly bounded within [-I_max, I_max]</property>
////   </algebraic-properties>
//// </c3i-module>
//// =============================================================================

import gleam/float
import gleam/int

/// PID controller configuration parameters.
pub type PidConfig {
  PidConfig(
    kp: Float,
    ki: Float,
    kd: Float,
    setpoint: Float,
    integral_windup_limit: Float,
    output_min: Float,
    output_max: Float,
    base_concurrency: Int,
    base_publish_interval_ms: Int,
  )
}

/// Dynamic PID state memory.
pub type PidState {
  PidState(
    config: PidConfig,
    integral_accum: Float,
    prev_error: Float,
    last_sample_epoch_us: Int,
    last_output: Float,
  )
}

/// Actuation directives generated by the PID controller.
pub type PidActuation {
  PidActuation(
    recommended_concurrency: Int,
    recommended_publish_interval_ms: Int,
    recommended_batch_size: Int,
    control_output: Float,
    error_term: Float,
  )
}

/// Default high-resilience PID configuration for Lyapunov stability control.
pub fn default_pid_config() -> PidConfig {
  PidConfig(
    kp: 1.2,
    ki: 0.05,
    kd: 0.3,
    setpoint: -3.0,
    integral_windup_limit: 5.0,
    output_min: 0.1,
    output_max: 2.0,
    base_concurrency: 16,
    base_publish_interval_ms: 50,
  )
}

/// Initialize the PID controller.
pub fn init_pid_tuner(config: PidConfig, now_us: Int) -> PidState {
  PidState(
    config: config,
    integral_accum: 0.0,
    prev_error: 0.0,
    last_sample_epoch_us: now_us,
    last_output: 1.0,
  )
}

/// Update the PID controller with an observed Lyapunov exponent and obtain actuation directives.
pub fn update_pid(
  state: PidState,
  observed_lambda: Float,
  now_us: Int,
) -> #(PidState, PidActuation) {
  let dt_sec = case now_us > state.last_sample_epoch_us {
    True -> {
      let diff_us = now_us - state.last_sample_epoch_us
      int.to_float(diff_us) /. 1_000_000.0
    }
    False -> 0.1
  }
  let safe_dt = case dt_sec <. 0.001 {
    True -> 0.001
    False -> dt_sec
  }

  // Error = setpoint - observed (e.g. -3.0 - (-1.0) = -2.0 when diverging)
  // Higher observed_lambda means more unstable, error becomes negative
  let error = state.config.setpoint -. observed_lambda

  // Integral with anti-windup clamping
  let raw_integral = state.integral_accum +. { error *. safe_dt }
  let clamped_integral =
    clamp_float(
      raw_integral,
      0.0 -. state.config.integral_windup_limit,
      state.config.integral_windup_limit,
    )

  // Derivative
  let derivative = { error -. state.prev_error } /. safe_dt

  // Control equation: u(t) = 1.0 + Kp*e + Ki*integral + Kd*derivative
  let raw_output =
    1.0
    +. { state.config.kp *. error }
    +. { state.config.ki *. clamped_integral }
    +. { state.config.kd *. derivative }

  let control_output =
    clamp_float(raw_output, state.config.output_min, state.config.output_max)

  // Compute actuation scaling
  let rec_concurrency =
    int.max(
      1,
      float.round(int.to_float(state.config.base_concurrency) *. control_output),
    )

  let rec_interval =
    int.max(
      10,
      float.round(
        int.to_float(state.config.base_publish_interval_ms) /. control_output,
      ),
    )

  let rec_batch =
    int.max(1, rec_concurrency / 2)

  let updated_state =
    PidState(
      config: state.config,
      integral_accum: clamped_integral,
      prev_error: error,
      last_sample_epoch_us: now_us,
      last_output: control_output,
    )

  let actuation =
    PidActuation(
      recommended_concurrency: rec_concurrency,
      recommended_publish_interval_ms: rec_interval,
      recommended_batch_size: rec_batch,
      control_output: control_output,
      error_term: error,
    )

  #(updated_state, actuation)
}

/// Reset the accumulated integral state to zero.
pub fn reset_integral(state: PidState) -> PidState {
  PidState(..state, integral_accum: 0.0)
}

fn clamp_float(val: Float, min_val: Float, max_val: Float) -> Float {
  case val <. min_val {
    True -> min_val
    False ->
      case val >. max_val {
        True -> max_val
        False -> val
      }
  }
}
