let digest value =
  value |> Digestif.SHA256.digest_string |> Digestif.SHA256.to_hex

let kdl_string value =
  let buffer = Buffer.create (String.length value + 8) in
  Buffer.add_char buffer '"';
  String.iter
    (function
      | '"' -> Buffer.add_string buffer "\\\""
      | '\\' -> Buffer.add_string buffer "\\\\"
      | '\n' -> Buffer.add_string buffer "\\n"
      | '\r' -> Buffer.add_string buffer "\\r"
      | '\t' -> Buffer.add_string buffer "\\t"
      | character -> Buffer.add_char buffer character)
    value;
  Buffer.add_char buffer '"';
  Buffer.contents buffer

let render_config_kdl intent =
  String.concat "\n"
    [
      "// Generated by hermes_zellij from typed declarative intent.";
      "// Intent digest: " ^ Zellij_intent.digest intent;
      "default_shell " ^ kdl_string (Zellij_intent.shell intent);
      "default_cwd " ^ kdl_string (Zellij_intent.workspace_root intent);
      "on_force_close \"detach\"";
      "session_serialization true";
      "serialize_pane_viewport true";
      "pane_frames true";
      "simplified_ui false";
      "";
    ]

let launcher_name = "zellij-attach-harness-bionic"

let command_links intent =
  List.map
    (fun session ->
      ( Zellij_intent.session_name session,
        Filename.concat (Zellij_intent.command_root intent) launcher_name ))
    (Zellij_intent.sessions intent)

let markdown_cell value =
  value |> String.split_on_char '|' |> String.concat "\\|"
  |> String.split_on_char '\n' |> String.concat "<br>"

let list_cell values = values |> String.concat "; " |> markdown_cell
let option_cell render = function None -> "-" | Some value -> render value

let render_ontology_markdown () =
  let header =
    [
      "# Zellij executable ontology";
      "";
      "Generated from `Zellij_ontology.nodes`. One ontology holon per row.";
      "";
      "| ID | Parent | Level | Kind | Lifecycle | Carrier | Operations | \
       Observations | Invariants | Hazards | Sources | RCA origin | Residuals \
       |";
      "|---|---|---|---|---|---|---|---|---|---|---|---|---|";
    ]
  in
  let rows =
    List.map
      (fun node ->
        Printf.sprintf
          "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |"
          (markdown_cell (Zellij_ontology.id node))
          (option_cell markdown_cell (Zellij_ontology.parent_id node))
          (Zellij_ontology.level_name (Zellij_ontology.level node))
          (Zellij_ontology.kind_name (Zellij_ontology.kind node))
          (Zellij_ontology.lifecycle_name (Zellij_ontology.lifecycle node))
          (markdown_cell (Zellij_ontology.carrier node))
          (list_cell (Zellij_ontology.operations node))
          (list_cell (Zellij_ontology.observations node))
          (list_cell (Zellij_ontology.invariants node))
          (list_cell (Zellij_ontology.hazards node))
          (list_cell (Zellij_ontology.sources node))
          (match Zellij_ontology.rca_origin node with
          | Specification -> "Specification"
          | Implementation -> "Implementation"
          | Environment -> "Environment"
          | Evidence -> "Evidence"
          | Control -> "Control")
          (list_cell (Zellij_ontology.residuals node)))
      Zellij_ontology.nodes
  in
  String.concat "\n" (header @ rows @ [ "" ])

let render_atlas_markdown () =
  let header =
    [
      "# Zellij fractal functional atlas";
      "";
      "Generated from `Zellij_atlas.rows`. One atomic capability per row.";
      "";
      "| ID | Ontology | Session | Operation | Lifecycle | Credit | \
       Description | Documentation oracle | Residuals |";
      "|---|---|---|---|---|---|---|---|---|";
    ]
  in
  let rows =
    List.map
      (fun row ->
        Printf.sprintf "| %s | %s | %s | %s | %s | %s | %s | %s | %s |"
          (markdown_cell (Zellij_atlas.id row))
          (markdown_cell (Zellij_atlas.ontology_id row))
          (option_cell
             (fun session -> Zellij_intent.session_name session)
             (Zellij_atlas.session row))
          (option_cell Zellij_atlas.operation_name (Zellij_atlas.operation row))
          (Zellij_atlas.lifecycle_name (Zellij_atlas.lifecycle row))
          (Zellij_atlas.credit_name (Zellij_atlas.credit row))
          (markdown_cell (Zellij_atlas.description row))
          (option_cell markdown_cell (Zellij_atlas.documentation_url row))
          (list_cell (Zellij_atlas.residuals row)))
      Zellij_atlas.rows
  in
  String.concat "\n" (header @ rows @ [ "" ])

let render_algebra_markdown () =
  String.concat "\n"
    [
      "# Zellij fractal functional algebra";
      "";
      "The carrier is the closed six-session set `S = {zlt-1, ..., zlt-6}`.";
      "Observations form normalized finite maps from `S` to command, \
       live-session, and cwd predicates.";
      "";
      "| Law | Equation | Negative control |";
      "|---|---|---|";
      "| Closure | `normalize : observation list -> result` | Unknown or \
       duplicate session identities are rejected |";
      "| Identity | `ensure(s, present) = present` | Ensuring an existing \
       session does not duplicate it |";
      "| Idempotence | `ensure(s, ensure(s, x)) = ensure(s, x)` | Repeated \
       convergence has no additional effect |";
      "| Commutativity | `union(a, b) = union(b, a)` | Normalization fixes \
       carrier order |";
      "| Associativity | `union(union(a,b),c) = union(a,union(b,c))` | \
       Duplicate keys fail before composition |";
      "| Empty-is-not-success | `complete([]) = false` | Vacuous evidence \
       cannot prove integration |";
      "| Exact denominator | `complete(o) iff domain(o) = S and all predicates \
       hold` | Five of six is partial |";
      "| Name preservation | `command(s) = session_name(s)` | Aliases outside \
       `S` are rejected |";
      "| Source separation | `documented != implemented != tested != live` | \
       Documentation gives `No_credit` |";
      "";
    ]

let render_guide_markdown intent =
  let commands =
    Zellij_intent.sessions intent
    |> List.map (fun session ->
        let name = Zellij_intent.session_name session in
        Printf.sprintf "- `%s` attaches to or creates independent session `%s`."
          name name)
  in
  String.concat "\n"
    ([
       "# Harness-bionic Zellij workspace";
       "";
       "Intent digest: `" ^ Zellij_intent.digest intent ^ "`";
       "";
       "Workspace: `" ^ Zellij_intent.workspace_root intent ^ "`";
       "";
       "Commands:";
       "";
     ]
    @ commands
    @ [
        "";
        "Each command is a manual attachment point. Applying configuration \
         does not auto-attach the current shell.";
        "";
        "The official documentation is an external oracle; the typed OCaml \
         intent and algebra remain normative for this integration.";
        "";
      ])

let render_authority_json () =
  let pages =
    List.map
      (fun row ->
        `Assoc
          [
            ("id", `String (Zellij_atlas.id row));
            ("description", `String (Zellij_atlas.description row));
            ( "url",
              match Zellij_atlas.documentation_url row with
              | Some url -> `String url
              | None -> `Null );
            ( "lifecycle",
              `String (Zellij_atlas.lifecycle_name (Zellij_atlas.lifecycle row))
            );
            ( "semantic_credit",
              `String (Zellij_atlas.credit_name (Zellij_atlas.credit row)) );
            ("acquisition_status", `String "discovered-from-official-toc");
            ("content_digest", `Null);
            ( "version_applicability",
              `String
                "current website; installed 0.44.3 applicability not \
                 established" );
          ])
      Zellij_atlas.documentation_pages
  in
  Yojson.Safe.pretty_to_string
    (`Assoc
       [
         ("schema", `String "hermes-zellij-authority-v1");
         ("source_class", `String "external-documentation-oracle");
         ( "inventory_source",
           `String "https://zellij.dev/documentation/toc.html" );
         ("inventory_observed_at", `String "2026-08-13T14:18:00+02:00");
         ("inventory_complete", `Bool true);
         ("atlas_digest", `String Zellij_atlas.digest);
         ("pages", `List pages);
       ])
  ^ "\n"

let render_model_json intent =
  let sessions =
    Zellij_intent.sessions intent
    |> List.map (fun session ->
        let name = Zellij_intent.session_name session in
        `Assoc [ ("command", `String name); ("session", `String name) ])
  in
  Yojson.Safe.pretty_to_string
    (`Assoc
       [
         ("schema", `String "hermes-zellij-model-v1");
         ("intent_digest", `String (Zellij_intent.digest intent));
         ( "intent",
           Yojson.Safe.from_string (Zellij_intent.canonical_json intent) );
         ("atlas_digest", `String Zellij_atlas.digest);
         ("sessions", `List sessions);
       ])
  ^ "\n"
