@sciviz @fractal-specifications #fractal-l2 #fractal-l4 #fractal-l5
Feature: SciViz All 167 Registered Extensions 1x1 Fractal Feature Map Specification
  As a Formal Verification Architect
  I want each extension card to contain detailed technical and functional specifications
  So that underlying algorithms and scientific domains are rigorously verifiable

  Background:
    Given I am on the page "http://127.0.0.1:4100/sciviz/extensions"

  Scenario Outline: SciViz Extension <name> 1x1 Fractal Specification Verification
    Then the sciviz card for "<name>" should detail technical aspect "<technical_aspect>"
    And the sciviz card for "<name>" should detail functional aspect "<functional_aspect>"

    Examples:
      | name | technical_aspect | functional_aspect |
      | ggram | Constraint-solving viewport hierarchy unifying | Scientific publication plates, multi-modal |
      | ggQQunif | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggupset | Power set boolean combination | Genomics gene set overlaps |
      | xmrr | Statistical process control limit | Manufacturing quality assurance, semiconductor |
      | gg3D | 3D-to-2D projection matrix multiplication | Engineering response surfaces, chemical |
      | ggQC | Statistical process control limit | Manufacturing quality assurance, semiconductor |
      | ggdist | Continuous kernel density estimation | Bayesian posterior parameter estimation |
      | ggedit | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggpage | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggpca | Eigen-decomposition and non-linear manifold | Single-cell transcriptomics, customer segmentation |
      | ggbreak | Affine piecewise coordinate mapping | Comparing massive outliers alongside |
      | ggimg | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | gganatogram | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggforce | Computational geometry algorithms including | Cluster boundary discovery, spatial |
      | ggalt | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggiraph | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggmuller | Smooth polynomial spline interpolation | Process pipelines, patient journey |
      | ggstance | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggrepel | Simulated annealing spring-force physics | Transcriptomic volcano plots, astronomical |
      | ggraph | Stress-majorization, Fruchterman-Reingold force-directed, and | Distributed microservice mesh topology |
      | gginnards | Reflective introspection of the | Automated plot testing, programmatic |
      | ggpp | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggpmisc | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | geomnet | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggExtra | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggfortify | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | autoplotly | Reflective introspection of the | Interactive visual debugging, exploratory |
      | gganimate | State interpolation and tweening | Dynamic planetary orbits, spread |
      | ggfx | Pixel-level raster convolution kernels | Highlighting critical anomalies with |
      | plotROC | True Positive Rate vs | Diagnostic test evaluation, machine |
      | ggbump | Sigmoid curve interpolation providing | League table sports rankings |
      | ggthemes | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggspectra | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggstatsplot | Executes statistical hypothesis testing | Biomedical comparative studies, A/B |
      | ggnetwork | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggtech | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggradar | Polar coordinate mapping (r_i | Athlete skill profile assessments |
      | ggx | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggTimeSeries | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | ggtree | Tree traversal algorithms mapping | Evolutionary genomics, viral variant |
      | ggseas | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | ggsci | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggmosaic | Recursive orthogonal area partitioning | Categorical survey analysis, cross-tabulation |
      | survminer | Non-parametric Kaplan-Meier estimator S(t) | Clinical survival trials, hardware |
      | ggeasy | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggside | Constraint-solving viewport hierarchy unifying | Scientific publication plates, multi-modal |
      | ggcorrplot | Bivariate Pearson/Spearman correlation coefficient | Multivariate feature selection, collinearity |
      | ggpubr | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggthemr | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | GGally | Eigen-decomposition and non-linear manifold | Single-cell transcriptomics, customer segmentation |
      | ggseqlogo | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggChernoff | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggridges | Kernel density estimation evaluated | Seasonal temperature variations, multi-stage |
      | lemon | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | cowplot | Grid-based viewport arrangement allocating | Assembling multi-panel figures for |
      | qqplotr | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggalluvial | Cubic Bezier curve interpolation | Customer cohort retention, election |
      | patchwork | Constraint-solving layout engine unifying | Scientific publication figures, executive |
      | ggquiver | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggsignif | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggdag | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggformula | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggbeeswarm | 1D circle packing and | Clinical biomarker levels per |
      | ggperiodic | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | ggpol | Recursive rectangular area partitioning | Resource allocation auditing, file |
      | ggpirate | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | esquisse | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggerror | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggdark | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | sugrrants | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | tvthemes | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggfittext | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggparty | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | gggenes | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | gggenomes | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | treemapify | Bruls-Huizing-van Wijk squarified treemap | Budget allocations, disk storage |
      | lindia | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | gghalves | Asymmetric kernel density projection | Raincloud plots, small-sample distribution |
      | ggrastr | SVG pattern element definitions | Black-and-white printing accessibility, highlighting |
      | ggpointdensity | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggsom | Eigen-decomposition and non-linear manifold | Single-cell transcriptomics, customer segmentation |
      | ggnewscale | Dynamic scale environment isolation | Overlaying distinct datasets (heat |
      | ggh4x | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | ggarrow | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | legendry | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | ggcharts | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | humapr | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggshadow | SVG pattern element definitions | Black-and-white printing accessibility, highlighting |
      | ggseg | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | mdthemes | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggwordcloud | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggasym | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | gglorenz | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | hrbrthemes | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggpattern | SVG pattern element definitions | Black-and-white printing accessibility, highlighting |
      | ggtext | Force-directed repulsion optimization and | Outlier labeling in dense |
      | calendR | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | ggip | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | gglm | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | econocharts | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ComplexUpset | Recursive rectangular area partitioning | Resource allocation auditing, file |
      | ggchromatic | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggheatmap | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | see | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | directlabels | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggHoriPlot | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | ggtrace | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggESDA | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | geomtextpath | Differential geometry arc-length parameterization | Topographic contour maps, river |
      | ggdensity | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggtranscript | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | piecepackr | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | oblicubes | 3D-to-2D projection matrix multiplication | Engineering response surfaces, chemical |
      | ggDoubleHeat | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | nflplotR | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggbraid | Smooth polynomial spline interpolation | Process pipelines, patient journey |
      | ggblanket | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggpie | Recursive rectangular area partitioning | Resource allocation auditing, file |
      | ggstar | Reflective introspection of the | Interactive visual debugging, exploratory |
      | ggarchery | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | tidyterra | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggseqplot | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggsurvfit | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggsector | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggterror | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggragged | Constraint-solving viewport hierarchy unifying | Scientific publication plates, multi-modal |
      | ggmapinset | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggmagnify | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | ggblend | SVG pattern element definitions | Black-and-white printing accessibility, highlighting |
      | ggflowchart | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggrain | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggoutlierscatterplot | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggautothemes | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | AMR | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ichimoku | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | eheat | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggstats | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggfoundry | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggalign | Non-linear coordinate projections and | Compositional data analysis (metallurgy |
      | ggreveal | Reflective introspection of the | Interactive visual debugging, exploratory |
      | geofacet | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | tidyplots | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | rphylopic | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | deeptime | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | ggpcp | Eigen-decomposition and non-linear manifold | Single-cell transcriptomics, customer segmentation |
      | ggvolcano | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggfootball | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggfields | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggsankeyfier | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggpath | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | gglinedensity | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggsurveillance | Rolling statistical parameter calculations | Semiconductor manufacturing quality control |
      | gguapo | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggDNAvis | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggdibbler | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggprop.test | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggsky | Differential vector calculus v(x,y) | Fluid dynamics, meteorological wind |
      | ggpop | Recursive rectangular area partitioning | Resource allocation auditing, file |
      | ggpointless | Statistical estimation algorithms calculating | Model validation, clinical trial |
      | ggincerta | Mathematical density estimation and | Quantifying statistical uncertainty, risk |
      | ggRandomForests | Chromosomal base-pair coordinate mapping | GWAS variant discovery, pathogen |
      | ggcube | 3D-to-2D projection matrix multiplication | Engineering response surfaces, chemical |
      | ggtaichi | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
      | ggchord2 | Relational graph algorithms (force-directed | Network infrastructure topology, biochemical |
      | ggtintshade | SVG pattern element definitions | Black-and-white printing accessibility, highlighting |
      | glydraw | Force-directed repulsion optimization and | Outlier labeling in dense |
      | ggmultiglyph | CIE-L*a*b* and CAM02-UCS perceptually | Publication-ready figure styling, dark |
