(* GENERATED by harness/quint_to_ocaml.ml from a Quint spec — DO NOT EDIT.
   Regenerate with: dune exec ./harness/zigvm_harness.exe -- --codegen-quint
   Module: sa_plan_ooda_bridge (STATE MACHINE).  Links against Quint_rt (bounded trace-explorer). *)
[@@@warning "-a"]

type state = { phase : int; version : int; fence : int; completion_count : int }

let init : state = { phase = (0); version = (0); fence = (0); completion_count = (0) }

let rec claim (s : state) : state option =
    if ((s.phase = (4))) then Some ({ s with phase = (5); version = (s.version + (1)); fence = (s.fence + (1)); completion_count = s.completion_count }) else None

and execute (s : state) : state option =
    if ((s.phase = (5))) then Some ({ s with phase = (6); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and start_verification (s : state) : state option =
    if ((s.phase = (6))) then Some ({ s with phase = (7); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and verify (s : state) : state option =
    if ((s.phase = (7))) then Some ({ s with phase = (8); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and record (s : state) : state option =
    if ((s.phase = (8))) then Some ({ s with phase = (9); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and complete (s : state) : state option =
    if ((s.phase = (9))) then Some ({ s with phase = (10); version = (s.version + (1)); fence = s.fence; completion_count = (s.completion_count + (1)) }) else None

and duplicate_replay (s : state) : state option =
    Some ({ s with phase = s.phase; version = s.version; fence = s.fence; completion_count = s.completion_count })

and stale_fence_rejection (s : state) : state option =
    if ((s.fence > (0))) then Some ({ s with phase = s.phase; version = s.version; fence = s.fence; completion_count = s.completion_count }) else None

and orient (s : state) : state option =
    if ((s.phase = (0))) then Some ({ s with phase = (1); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and decide_selected (s : state) : state option =
    if ((s.phase = (1))) then Some ({ s with phase = (2); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and materialize (s : state) : state option =
    if ((s.phase = (2))) then Some ({ s with phase = (3); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and preflight (s : state) : state option =
    if ((s.phase = (3))) then Some ({ s with phase = (4); version = (s.version + (1)); fence = s.fence; completion_count = s.completion_count }) else None

and step (s : state) : state list =
    Quint_rt.sm_any s [ orient; decide_selected; materialize; preflight; claim; execute; start_verification; verify; record; complete; duplicate_replay; stale_fence_rejection ]

let inv_phase_domain (s : state) =
    ((s.phase >= (0)) && (s.phase <= (10)))

let inv_version_matches_progress (s : state) =
    (s.version = s.phase)

let inv_fence_monotone_bound (s : state) =
    ((s.fence >= (0)) && (s.fence <= (1)))

let inv_completion_unique (s : state) =
    ((s.completion_count >= (0)) && (s.completion_count <= (1)))

let inv_completion_requires_terminal (s : state) =
    ((s.completion_count = (0)) || ((s.phase = (10)) && (s.completion_count = (1))))
