[package]
name = "nas_k8s_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
k8s-openapi = { version = "0.27", features = ["v1_34"] }
kube = { version = "3.1", features = ["client", "derive", "runtime", "rustls-tls"] }
schemars = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
