(* GENERATED by gen_stanza.exe from the dune library graph.
   Do not edit. A dune rule regenerates this and diffs it, so drift
   fails the build rather than rotting quietly.

   195 libraries. A value of this type is a WITNESS that the library
   exists in the graph; there is no way to make one from a string, which
   is the whole point. *)

type t

val name : t -> string
val dune_file : t -> string
val owner_directory : t -> string
val equal : t -> t -> bool
val compare : t -> t -> int
val all : t list

(** The reverse dependency cone, baked in from the graph at generation
    time: everything that would be affected if this library were wrong.
    Excludes the library itself. *)
val cone : t -> t list

(** Union of the cones of several targets, minus the targets. This is
    the additive law: [cone_of (S @ T) = cone_of S union cone_of T]. *)
val cone_of : t list -> t list

(** {1 The libraries} *)

val agent_dispatch_hook : t
val agent_time_hook : t
val hermes_agent_loop_compress_units : t
val hermes_agent_loop_context_compression : t
val hermes_agent_loop_context_engine : t
val hermes_agent_loop_context_file_units : t
val hermes_agent_loop_context_units : t
val hermes_agent_loop_conversation_loop : t
val hermes_agent_loop_finalize_units : t
val hermes_agent_loop_interactive_cli_units : t
val hermes_agent_loop_interrupt_control : t
val hermes_agent_loop_json_canonical : t
val hermes_agent_loop_loop_send_path : t
val hermes_agent_loop_mcp_units : t
val hermes_agent_loop_memory_units : t
val hermes_agent_loop_message_hygiene : t
val hermes_agent_loop_message_repairs : t
val hermes_agent_loop_prompt_assembly : t
val hermes_agent_loop_prompt_units : t
val hermes_agent_loop_redact_units : t
val hermes_agent_loop_skill_units : t
val hermes_agent_loop_subagent_units : t
val hermes_agent_loop_tool_units : t
val hermes_agent_loop_turn_finalization : t
val hermes_debugging : t
val hermes_dependability_abandonment_protocol : t
val hermes_dependability_approval : t
val hermes_dependability_approval_crypto : t
val hermes_dependability_authority_store : t
val hermes_dependability_clock : t
val hermes_dependability_completion_store : t
val hermes_dependability_core : t
val hermes_dependability_credential : t
val hermes_dependability_dispatch_store : t
val hermes_dependability_filesystem : t
val hermes_dependability_network : t
val hermes_dependability_owner_inventory : t
val hermes_dependability_process : t
val hermes_dependability_process_protocol : t
val hermes_dependability_process_test_support : t
val hermes_dependability_recovery_vault : t
val hermes_dependability_solver : t
val hermes_dependability_sqlite : t
val hermes_dependability_sqlite_location : t
val hermes_dependability_sqlite_test_support : t
val hermes_dependability_topology : t
val hermes_dependability_writer_lease : t
val hermes_dune_graph : t
val hermes_external_access : t
val hermes_fpp_window_authority : t
val hermes_harness_agent_model : t
val hermes_harness_anthropic_adapter : t
val hermes_harness_bedrock_converse : t
val hermes_harness_blueprint : t
val hermes_harness_bootstrap : t
val hermes_harness_capability_catalog : t
val hermes_harness_capture_diagnostic : t
val hermes_harness_codex_message_shapes : t
val hermes_harness_contract_catalog : t
val hermes_harness_control_plane : t
val hermes_harness_converge : t
val hermes_harness_core : t
val hermes_harness_dependency_smt : t
val hermes_harness_determinism_verifier : t
val hermes_harness_diff_triage : t
val hermes_harness_drift_rules : t
val hermes_harness_e2e_framework : t
val hermes_harness_e2e_tier1_tests : t
val hermes_harness_e2e_tier2_tests : t
val hermes_harness_e2e_tier3_tests : t
val hermes_harness_e2e_tier4_tests : t
val hermes_harness_evidence : t
val hermes_harness_evidence_import : t
val hermes_harness_evidence_rollup : t
val hermes_harness_evolution_model : t
val hermes_harness_expect_posterior : t
val hermes_harness_feature_catalog : t
val hermes_harness_formal_coverage : t
val hermes_harness_formal_specs : t
val hermes_harness_fpp_usecases : t
val hermes_harness_fractal_catalog : t
val hermes_harness_fractal_countermeasures : t
val hermes_harness_fractal_ontology : t
val hermes_harness_fractal_parity : t
val hermes_harness_gap_plan : t
val hermes_harness_gemini_schema : t
val hermes_harness_gospel_check : t
val hermes_harness_harness_config : t
val hermes_harness_harness_topology : t
val hermes_harness_hermes_analysis : t
val hermes_harness_hermes_imports : t
val hermes_harness_hermes_rete : t
val hermes_harness_hermes_zenoh : t
val hermes_harness_homeostasis : t
val hermes_harness_info_math : t
val hermes_harness_inventory : t
val hermes_harness_message_hygiene : t
val hermes_harness_ocaml_only_guard : t
val hermes_harness_openrouter_contract : t
val hermes_harness_openrouter_transport : t
val hermes_harness_orientation_history : t
val hermes_harness_parity : t
val hermes_harness_parity_algebra : t
val hermes_harness_parity_compare : t
val hermes_harness_parity_dashboard : t
val hermes_harness_parity_intent : t
val hermes_harness_parity_lattice_extracted : t
val hermes_harness_parity_ledger : t
val hermes_harness_parity_normalizer : t
val hermes_harness_path_safety : t
val hermes_harness_plan : t
val hermes_harness_posterior_assessment : t
val hermes_harness_qcheck_seed : t
val hermes_harness_receipt_reliability : t
val hermes_harness_reference_artifacts : t
val hermes_harness_reference_capture : t
val hermes_harness_replay_executor : t
val hermes_harness_report : t
val hermes_harness_resource_envelope : t
val hermes_harness_retry_utils : t
val hermes_harness_rocq_lattice : t
val hermes_harness_route_resolution : t
val hermes_harness_ruliad : t
val hermes_harness_ruliad_rules : t
val hermes_harness_runtime_coverage : t
val hermes_harness_rust_rules : t
val hermes_harness_session_fixture : t
val hermes_harness_site_build : t
val hermes_harness_sop_execution : t
val hermes_harness_suite_telemetry : t
val hermes_harness_swarm_algebra : t
val hermes_harness_turn_budget : t
val hermes_harness_turn_preflight : t
val hermes_harness_web_read_model : t
val hermes_jj_protocol : t
val hermes_nix : t
val hermes_ops : t
val hermes_ops_capability : t
val hermes_ops_capability_core : t
val hermes_ops_completion_topology : t
val hermes_ops_config_authority : t
val hermes_ops_dashboard : t
val hermes_ops_governance : t
val hermes_ops_topology : t
val hermes_stanza : t
val hermes_sysml : t
val hermes_vcs : t
val hermes_vision : t
val hermes_wiki_address : t
val hermes_wiki_ast : t
val hermes_wiki_blocks : t
val hermes_wiki_build : t
val hermes_wiki_callout : t
val hermes_wiki_control : t
val hermes_wiki_core : t
val hermes_wiki_datastore : t
val hermes_wiki_diag : t
val hermes_wiki_directive : t
val hermes_wiki_doctest : t
val hermes_wiki_export : t
val hermes_wiki_fpp : t
val hermes_wiki_fpp_interp : t
val hermes_wiki_graph : t
val hermes_wiki_httpd : t
val hermes_wiki_iface : t
val hermes_wiki_include : t
val hermes_wiki_km : t
val hermes_wiki_lifecycle : t
val hermes_wiki_mbse : t
val hermes_wiki_navsearch : t
val hermes_wiki_ordering : t
val hermes_wiki_present : t
val hermes_wiki_query : t
val hermes_wiki_reconcile : t
val hermes_wiki_ref : t
val hermes_wiki_register : t
val hermes_wiki_search : t
val hermes_wiki_sheaf : t
val hermes_wiki_similarity : t
val hermes_wiki_source_ext : t
val hermes_wiki_theme : t
val hermes_wiki_toc : t
val hermes_wiki_topology : t
val hermes_wiki_transclude : t
val hermes_wiki_view : t
val hermes_wiki_visibility : t
val hermes_zellij : t
val run_swarm_bridge_programme : t
val sa_plan : t
val toolchain_core : t
val wiki_baseline_triage : t
val wiki_core : t
val wiki_render : t
val wiki_server : t
val wiki_suite_telemetry : t
