(* GENERATED by gen_stanza.exe from the dune library graph.
   Do not edit. A dune rule regenerates this and diffs it, so drift
   fails the build rather than rotting quietly.

   195 libraries. A value of this type is a WITNESS that the library
   exists in the graph; there is no way to make one from a string, which
   is the whole point. *)

type t = int

let names = [|
  "agent_dispatch_hook";
  "agent_time_hook";
  "hermes_agent_loop_compress_units";
  "hermes_agent_loop_context_compression";
  "hermes_agent_loop_context_engine";
  "hermes_agent_loop_context_file_units";
  "hermes_agent_loop_context_units";
  "hermes_agent_loop_conversation_loop";
  "hermes_agent_loop_finalize_units";
  "hermes_agent_loop_interactive_cli_units";
  "hermes_agent_loop_interrupt_control";
  "hermes_agent_loop_json_canonical";
  "hermes_agent_loop_loop_send_path";
  "hermes_agent_loop_mcp_units";
  "hermes_agent_loop_memory_units";
  "hermes_agent_loop_message_hygiene";
  "hermes_agent_loop_message_repairs";
  "hermes_agent_loop_prompt_assembly";
  "hermes_agent_loop_prompt_units";
  "hermes_agent_loop_redact_units";
  "hermes_agent_loop_skill_units";
  "hermes_agent_loop_subagent_units";
  "hermes_agent_loop_tool_units";
  "hermes_agent_loop_turn_finalization";
  "hermes_debugging";
  "hermes_dependability_abandonment_protocol";
  "hermes_dependability_approval";
  "hermes_dependability_approval_crypto";
  "hermes_dependability_authority_store";
  "hermes_dependability_clock";
  "hermes_dependability_completion_store";
  "hermes_dependability_core";
  "hermes_dependability_credential";
  "hermes_dependability_dispatch_store";
  "hermes_dependability_filesystem";
  "hermes_dependability_network";
  "hermes_dependability_owner_inventory";
  "hermes_dependability_process";
  "hermes_dependability_process_protocol";
  "hermes_dependability_process_test_support";
  "hermes_dependability_recovery_vault";
  "hermes_dependability_solver";
  "hermes_dependability_sqlite";
  "hermes_dependability_sqlite_location";
  "hermes_dependability_sqlite_test_support";
  "hermes_dependability_topology";
  "hermes_dependability_writer_lease";
  "hermes_dune_graph";
  "hermes_external_access";
  "hermes_fpp_window_authority";
  "hermes_harness_agent_model";
  "hermes_harness_anthropic_adapter";
  "hermes_harness_bedrock_converse";
  "hermes_harness_blueprint";
  "hermes_harness_bootstrap";
  "hermes_harness_capability_catalog";
  "hermes_harness_capture_diagnostic";
  "hermes_harness_codex_message_shapes";
  "hermes_harness_contract_catalog";
  "hermes_harness_control_plane";
  "hermes_harness_converge";
  "hermes_harness_core";
  "hermes_harness_dependency_smt";
  "hermes_harness_determinism_verifier";
  "hermes_harness_diff_triage";
  "hermes_harness_drift_rules";
  "hermes_harness_e2e_framework";
  "hermes_harness_e2e_tier1_tests";
  "hermes_harness_e2e_tier2_tests";
  "hermes_harness_e2e_tier3_tests";
  "hermes_harness_e2e_tier4_tests";
  "hermes_harness_evidence";
  "hermes_harness_evidence_import";
  "hermes_harness_evidence_rollup";
  "hermes_harness_evolution_model";
  "hermes_harness_expect_posterior";
  "hermes_harness_feature_catalog";
  "hermes_harness_formal_coverage";
  "hermes_harness_formal_specs";
  "hermes_harness_fpp_usecases";
  "hermes_harness_fractal_catalog";
  "hermes_harness_fractal_countermeasures";
  "hermes_harness_fractal_ontology";
  "hermes_harness_fractal_parity";
  "hermes_harness_gap_plan";
  "hermes_harness_gemini_schema";
  "hermes_harness_gospel_check";
  "hermes_harness_harness_config";
  "hermes_harness_harness_topology";
  "hermes_harness_hermes_analysis";
  "hermes_harness_hermes_imports";
  "hermes_harness_hermes_rete";
  "hermes_harness_hermes_zenoh";
  "hermes_harness_homeostasis";
  "hermes_harness_info_math";
  "hermes_harness_inventory";
  "hermes_harness_message_hygiene";
  "hermes_harness_ocaml_only_guard";
  "hermes_harness_openrouter_contract";
  "hermes_harness_openrouter_transport";
  "hermes_harness_orientation_history";
  "hermes_harness_parity";
  "hermes_harness_parity_algebra";
  "hermes_harness_parity_compare";
  "hermes_harness_parity_dashboard";
  "hermes_harness_parity_intent";
  "hermes_harness_parity_lattice_extracted";
  "hermes_harness_parity_ledger";
  "hermes_harness_parity_normalizer";
  "hermes_harness_path_safety";
  "hermes_harness_plan";
  "hermes_harness_posterior_assessment";
  "hermes_harness_qcheck_seed";
  "hermes_harness_receipt_reliability";
  "hermes_harness_reference_artifacts";
  "hermes_harness_reference_capture";
  "hermes_harness_replay_executor";
  "hermes_harness_report";
  "hermes_harness_resource_envelope";
  "hermes_harness_retry_utils";
  "hermes_harness_rocq_lattice";
  "hermes_harness_route_resolution";
  "hermes_harness_ruliad";
  "hermes_harness_ruliad_rules";
  "hermes_harness_runtime_coverage";
  "hermes_harness_rust_rules";
  "hermes_harness_session_fixture";
  "hermes_harness_site_build";
  "hermes_harness_sop_execution";
  "hermes_harness_suite_telemetry";
  "hermes_harness_swarm_algebra";
  "hermes_harness_turn_budget";
  "hermes_harness_turn_preflight";
  "hermes_harness_web_read_model";
  "hermes_jj_protocol";
  "hermes_nix";
  "hermes_ops";
  "hermes_ops_capability";
  "hermes_ops_capability_core";
  "hermes_ops_completion_topology";
  "hermes_ops_config_authority";
  "hermes_ops_dashboard";
  "hermes_ops_governance";
  "hermes_ops_topology";
  "hermes_stanza";
  "hermes_sysml";
  "hermes_vcs";
  "hermes_vision";
  "hermes_wiki_address";
  "hermes_wiki_ast";
  "hermes_wiki_blocks";
  "hermes_wiki_build";
  "hermes_wiki_callout";
  "hermes_wiki_control";
  "hermes_wiki_core";
  "hermes_wiki_datastore";
  "hermes_wiki_diag";
  "hermes_wiki_directive";
  "hermes_wiki_doctest";
  "hermes_wiki_export";
  "hermes_wiki_fpp";
  "hermes_wiki_fpp_interp";
  "hermes_wiki_graph";
  "hermes_wiki_httpd";
  "hermes_wiki_iface";
  "hermes_wiki_include";
  "hermes_wiki_km";
  "hermes_wiki_lifecycle";
  "hermes_wiki_mbse";
  "hermes_wiki_navsearch";
  "hermes_wiki_ordering";
  "hermes_wiki_present";
  "hermes_wiki_query";
  "hermes_wiki_reconcile";
  "hermes_wiki_ref";
  "hermes_wiki_register";
  "hermes_wiki_search";
  "hermes_wiki_sheaf";
  "hermes_wiki_similarity";
  "hermes_wiki_source_ext";
  "hermes_wiki_theme";
  "hermes_wiki_toc";
  "hermes_wiki_topology";
  "hermes_wiki_transclude";
  "hermes_wiki_view";
  "hermes_wiki_visibility";
  "hermes_zellij";
  "run_swarm_bridge_programme";
  "sa_plan";
  "toolchain_core";
  "wiki_baseline_triage";
  "wiki_core";
  "wiki_render";
  "wiki_server";
  "wiki_suite_telemetry";
|]

let dune_files = [|
  "modules/system_engg/dune";
  "modules/system_engg/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_agent_loop/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dependability/dune";
  "modules/hermes_dune_graph/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_fpp_authority/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/generated_rocq/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/swarm/dune";
  "modules/hermes_harness/dune";
  "modules/swarm/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_harness/dune";
  "modules/hermes_vcs/dune";
  "modules/hermes_nix/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops_dashboard/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_ops/dune";
  "modules/hermes_stanza/dune";
  "modules/hermes_sysml/dune";
  "modules/hermes_vcs/dune";
  "modules/hermes_vision/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/build/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/control/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/fpp/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/source/dune";
  "modules/hermes_wiki/src/surface/dune";
  "modules/hermes_wiki/src/fpp/dune";
  "modules/hermes_wiki/src/fpp/dune";
  "modules/hermes_wiki/src/graph/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/source/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/km/dune";
  "modules/hermes_wiki/src/km/dune";
  "modules/hermes_wiki/src/mbse/dune";
  "modules/hermes_wiki/src/surface/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/present/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/reconcile/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/register/dune";
  "modules/hermes_wiki/src/search/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/graph/dune";
  "modules/hermes_wiki/src/source/dune";
  "modules/hermes_wiki/src/present/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/fpp/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_wiki/src/engine/dune";
  "modules/hermes_zellij/dune";
  "modules/system_engg/dune";
  "modules/sa_plan/dune";
  "modules/hermes_toolchain/dune";
  "modules/hermes_wiki/src/tools/dune";
  "modules/hermes_wiki/src/core/dune";
  "modules/hermes_wiki/src/render/dune";
  "modules/hermes_wiki/src/server/dune";
  "modules/hermes_wiki/test/dune";
|]

let name t = names.(t)
let dune_file t = dune_files.(t)
let owner_directory t = Filename.dirname (dune_file t)
let equal (a : t) b = a = b
let compare (a : t) b = Stdlib.compare a b
let all = List.init (Array.length names) (fun i -> i)

(* cone.(i) is the reverse dependency cone of library i, as indices. *)
let cone_table = [|
  [|  |];
  [|  |];
  [| 103 |];
  [| 67; 68; 69; 70; 103 |];
  [| 67; 68; 69; 70; 103 |];
  [| 103 |];
  [| 103 |];
  [| 67; 68; 69; 70; 103 |];
  [| 103 |];
  [| 103 |];
  [|  |];
  [| 12; 103 |];
  [| 103 |];
  [| 103 |];
  [| 13; 20; 21; 103 |];
  [| 3; 4; 7; 17; 23; 67; 68; 69; 70; 103 |];
  [| 103 |];
  [| 67; 68; 69; 70; 103 |];
  [| 103 |];
  [| 103 |];
  [| 103 |];
  [| 103 |];
  [| 103 |];
  [| 67; 68; 69; 70; 103 |];
  [| 136; 141 |];
  [| 26; 33; 46; 136; 141 |];
  [| 46; 136; 141 |];
  [| 26; 46; 136; 141 |];
  [| 26; 30; 33; 40; 46; 136; 141 |];
  [| 26; 28; 30; 32; 33; 34; 35; 37; 39; 40; 41; 42; 43; 44; 46; 136; 141 |];
  [|  |];
  [| 25; 26; 27; 28; 30; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41; 42; 43; 44; 46; 136; 141 |];
  [| 35 |];
  [| 26; 46; 136; 141 |];
  [| 26; 28; 30; 33; 40; 41; 42; 43; 44; 46; 136; 141 |];
  [|  |];
  [| 26; 28; 30; 33; 40; 46; 136; 141 |];
  [| 39 |];
  [| 37; 39; 136; 141 |];
  [|  |];
  [|  |];
  [|  |];
  [| 26; 28; 30; 33; 40; 41; 44; 46; 136; 141 |];
  [| 26; 28; 30; 33; 40; 41; 42; 44; 46; 136; 141 |];
  [|  |];
  [|  |];
  [| 136; 141 |];
  [|  |];
  [| 136; 141 |];
  [| 77; 79; 84; 88; 127; 128; 133; 136; 137; 139; 141; 143; 168; 175; 182 |];
  [|  |];
  [| 103 |];
  [| 103 |];
  [| 65; 78; 87; 104; 105 |];
  [| 56; 63; 78; 103; 115; 126 |];
  [| 62; 80; 104; 105; 114 |];
  [| 78; 103 |];
  [| 103 |];
  [| 104 |];
  [| 77; 79; 84; 104; 127; 128; 133; 136; 141 |];
  [|  |];
  [| 54; 56; 63; 71; 73; 78; 80; 101; 103; 104; 113; 114; 115; 117; 126; 127; 133; 136; 141 |];
  [|  |];
  [|  |];
  [|  |];
  [|  |];
  [| 67; 68; 69; 70 |];
  [|  |];
  [|  |];
  [|  |];
  [|  |];
  [| 73; 80; 101; 103; 104; 113; 114; 117; 127; 133; 136; 141 |];
  [|  |];
  [| 104; 113; 127; 133; 136; 141 |];
  [|  |];
  [| 111 |];
  [| 80; 101; 117 |];
  [| 84; 127; 128; 133; 136; 141 |];
  [|  |];
  [| 77; 84; 127; 128; 133; 136; 141 |];
  [|  |];
  [| 65; 104 |];
  [| 77; 78; 79; 84; 87; 88; 104; 127; 128; 130; 133; 136; 141 |];
  [|  |];
  [| 127 |];
  [| 103 |];
  [|  |];
  [| 78 |];
  [| 77; 79; 84; 127; 128; 133; 136; 141 |];
  [| 90; 104 |];
  [|  |];
  [| 65; 111; 136; 141 |];
  [| 136; 147 |];
  [| 59; 77; 79; 84; 104; 127; 128; 133; 136; 141 |];
  [| 107 |];
  [| 56; 63; 71; 73; 78; 80; 101; 103; 104; 113; 114; 115; 117; 126; 127; 133; 136; 141 |];
  [| 132 |];
  [|  |];
  [| 99; 103; 116; 132 |];
  [| 103; 116 |];
  [| 136 |];
  [| 117 |];
  [| 53; 65; 73; 77; 78; 79; 84; 87; 103; 104; 105; 113; 127; 128; 133; 136; 141 |];
  [|  |];
  [|  |];
  [| 104 |];
  [|  |];
  [|  |];
  [| 56; 63; 78; 103; 115; 126 |];
  [| 103 |];
  [|  |];
  [|  |];
  [|  |];
  [| 136; 141 |];
  [|  |];
  [| 56; 63; 78; 103; 126 |];
  [| 103 |];
  [|  |];
  [| 66; 67; 68; 69; 70; 78; 87; 136; 141; 186; 187 |];
  [| 103 |];
  [|  |];
  [| 103 |];
  [| 111; 136; 141 |];
  [|  |];
  [|  |];
  [|  |];
  [| 103 |];
  [|  |];
  [| 136; 141 |];
  [|  |];
  [| 128; 136; 141 |];
  [| 7; 10; 67; 68; 69; 70; 103; 132 |];
  [|  |];
  [| 127 |];
  [| 30; 37; 38; 39; 136; 141 |];
  [|  |];
  [|  |];
  [| 136; 141 |];
  [| 24; 25; 26; 27; 28; 30; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41; 42; 43; 44; 46; 48; 136; 137; 141; 142; 143 |];
  [| 136; 141 |];
  [| 136; 141 |];
  [| 136 |];
  [| 136; 141; 143 |];
  [| 136; 141 |];
  [| 129; 136; 137; 141; 194 |];
  [| 50; 77; 78; 79; 82; 84; 87; 88; 104; 127; 128; 130; 133; 136; 141; 168 |];
  [| 26; 30; 33; 37; 38; 39; 40; 46; 134; 136; 141 |];
  [|  |];
  [| 136; 168; 175 |];
  [| 84; 127; 133; 136; 148; 150; 151; 154; 155; 157; 158; 159; 162; 166; 167; 168; 169; 170; 171; 172; 175; 176; 177; 178; 179; 181; 184; 185 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 84; 127; 133; 136; 148; 149; 150; 151; 154; 155; 157; 158; 159; 162; 166; 167; 168; 169; 170; 171; 172; 175; 176; 177; 178; 179; 181; 184; 185 |];
  [| 136; 168; 175 |];
  [| 84; 127; 133; 136; 148; 150; 151; 155; 157; 158; 159; 162; 166; 167; 168; 169; 170; 171; 172; 175; 176; 177; 178; 179; 181; 184; 185 |];
  [| 136; 168; 175 |];
  [| 45; 48; 49; 53; 56; 63; 65; 66; 67; 68; 69; 70; 73; 77; 78; 79; 81; 84; 87; 88; 102; 103; 104; 105; 113; 118; 127; 128; 130; 133; 136; 137; 139; 141; 143; 147; 153; 160; 161; 168; 175; 182; 186; 187 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 45; 48; 49; 77; 79; 84; 88; 127; 128; 130; 133; 136; 137; 139; 141; 143; 147; 161; 168; 175; 182 |];
  [| 77; 79; 84; 127; 128; 133; 136; 141 |];
  [| 136; 168; 169; 175; 178 |];
  [|  |];
  [| 136; 168; 175; 179 |];
  [| 84; 127; 133; 136; 148; 149; 150; 151; 154; 155; 157; 158; 159; 162; 166; 167; 168; 169; 170; 171; 172; 175; 176; 177; 178; 179; 181; 184; 185 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 155; 168; 175; 184 |];
  [| 136; 153; 168; 175 |];
  [| 84; 127; 133; 136; 148; 150; 151; 154; 155; 157; 158; 159; 162; 166; 167; 168; 169; 170; 171; 172; 175; 176; 177; 178; 179; 181; 184; 185 |];
  [| 136; 168 |];
  [| 136; 168; 169; 175 |];
  [| 136; 151; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 171; 175 |];
  [| 136; 168; 169; 175 |];
  [| 136; 141; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [| 136; 168; 175 |];
  [|  |];
  [|  |];
  [| 110; 187 |];
  [|  |];
  [|  |];
  [| 136; 168; 169; 175; 176 |];
  [|  |];
  [|  |];
  [|  |];
|]

let cone t = Array.to_list cone_table.(t)

module IntSet = Set.Make (Int)

let cone_of targets =
  let seeds = IntSet.of_list targets in
  let reached =
    List.fold_left
      (fun acc t -> List.fold_left (fun a x -> IntSet.add x a) acc (cone t))
      IntSet.empty targets
  in
  IntSet.elements (IntSet.diff reached seeds)

(* {1 The libraries} *)

let agent_dispatch_hook : t = 0
let agent_time_hook : t = 1
let hermes_agent_loop_compress_units : t = 2
let hermes_agent_loop_context_compression : t = 3
let hermes_agent_loop_context_engine : t = 4
let hermes_agent_loop_context_file_units : t = 5
let hermes_agent_loop_context_units : t = 6
let hermes_agent_loop_conversation_loop : t = 7
let hermes_agent_loop_finalize_units : t = 8
let hermes_agent_loop_interactive_cli_units : t = 9
let hermes_agent_loop_interrupt_control : t = 10
let hermes_agent_loop_json_canonical : t = 11
let hermes_agent_loop_loop_send_path : t = 12
let hermes_agent_loop_mcp_units : t = 13
let hermes_agent_loop_memory_units : t = 14
let hermes_agent_loop_message_hygiene : t = 15
let hermes_agent_loop_message_repairs : t = 16
let hermes_agent_loop_prompt_assembly : t = 17
let hermes_agent_loop_prompt_units : t = 18
let hermes_agent_loop_redact_units : t = 19
let hermes_agent_loop_skill_units : t = 20
let hermes_agent_loop_subagent_units : t = 21
let hermes_agent_loop_tool_units : t = 22
let hermes_agent_loop_turn_finalization : t = 23
let hermes_debugging : t = 24
let hermes_dependability_abandonment_protocol : t = 25
let hermes_dependability_approval : t = 26
let hermes_dependability_approval_crypto : t = 27
let hermes_dependability_authority_store : t = 28
let hermes_dependability_clock : t = 29
let hermes_dependability_completion_store : t = 30
let hermes_dependability_core : t = 31
let hermes_dependability_credential : t = 32
let hermes_dependability_dispatch_store : t = 33
let hermes_dependability_filesystem : t = 34
let hermes_dependability_network : t = 35
let hermes_dependability_owner_inventory : t = 36
let hermes_dependability_process : t = 37
let hermes_dependability_process_protocol : t = 38
let hermes_dependability_process_test_support : t = 39
let hermes_dependability_recovery_vault : t = 40
let hermes_dependability_solver : t = 41
let hermes_dependability_sqlite : t = 42
let hermes_dependability_sqlite_location : t = 43
let hermes_dependability_sqlite_test_support : t = 44
let hermes_dependability_topology : t = 45
let hermes_dependability_writer_lease : t = 46
let hermes_dune_graph : t = 47
let hermes_external_access : t = 48
let hermes_fpp_window_authority : t = 49
let hermes_harness_agent_model : t = 50
let hermes_harness_anthropic_adapter : t = 51
let hermes_harness_bedrock_converse : t = 52
let hermes_harness_blueprint : t = 53
let hermes_harness_bootstrap : t = 54
let hermes_harness_capability_catalog : t = 55
let hermes_harness_capture_diagnostic : t = 56
let hermes_harness_codex_message_shapes : t = 57
let hermes_harness_contract_catalog : t = 58
let hermes_harness_control_plane : t = 59
let hermes_harness_converge : t = 60
let hermes_harness_core : t = 61
let hermes_harness_dependency_smt : t = 62
let hermes_harness_determinism_verifier : t = 63
let hermes_harness_diff_triage : t = 64
let hermes_harness_drift_rules : t = 65
let hermes_harness_e2e_framework : t = 66
let hermes_harness_e2e_tier1_tests : t = 67
let hermes_harness_e2e_tier2_tests : t = 68
let hermes_harness_e2e_tier3_tests : t = 69
let hermes_harness_e2e_tier4_tests : t = 70
let hermes_harness_evidence : t = 71
let hermes_harness_evidence_import : t = 72
let hermes_harness_evidence_rollup : t = 73
let hermes_harness_evolution_model : t = 74
let hermes_harness_expect_posterior : t = 75
let hermes_harness_feature_catalog : t = 76
let hermes_harness_formal_coverage : t = 77
let hermes_harness_formal_specs : t = 78
let hermes_harness_fpp_usecases : t = 79
let hermes_harness_fractal_catalog : t = 80
let hermes_harness_fractal_countermeasures : t = 81
let hermes_harness_fractal_ontology : t = 82
let hermes_harness_fractal_parity : t = 83
let hermes_harness_gap_plan : t = 84
let hermes_harness_gemini_schema : t = 85
let hermes_harness_gospel_check : t = 86
let hermes_harness_harness_config : t = 87
let hermes_harness_harness_topology : t = 88
let hermes_harness_hermes_analysis : t = 89
let hermes_harness_hermes_imports : t = 90
let hermes_harness_hermes_rete : t = 91
let hermes_harness_hermes_zenoh : t = 92
let hermes_harness_homeostasis : t = 93
let hermes_harness_info_math : t = 94
let hermes_harness_inventory : t = 95
let hermes_harness_message_hygiene : t = 96
let hermes_harness_ocaml_only_guard : t = 97
let hermes_harness_openrouter_contract : t = 98
let hermes_harness_openrouter_transport : t = 99
let hermes_harness_orientation_history : t = 100
let hermes_harness_parity : t = 101
let hermes_harness_parity_algebra : t = 102
let hermes_harness_parity_compare : t = 103
let hermes_harness_parity_dashboard : t = 104
let hermes_harness_parity_intent : t = 105
let hermes_harness_parity_lattice_extracted : t = 106
let hermes_harness_parity_ledger : t = 107
let hermes_harness_parity_normalizer : t = 108
let hermes_harness_path_safety : t = 109
let hermes_harness_plan : t = 110
let hermes_harness_posterior_assessment : t = 111
let hermes_harness_qcheck_seed : t = 112
let hermes_harness_receipt_reliability : t = 113
let hermes_harness_reference_artifacts : t = 114
let hermes_harness_reference_capture : t = 115
let hermes_harness_replay_executor : t = 116
let hermes_harness_report : t = 117
let hermes_harness_resource_envelope : t = 118
let hermes_harness_retry_utils : t = 119
let hermes_harness_rocq_lattice : t = 120
let hermes_harness_route_resolution : t = 121
let hermes_harness_ruliad : t = 122
let hermes_harness_ruliad_rules : t = 123
let hermes_harness_runtime_coverage : t = 124
let hermes_harness_rust_rules : t = 125
let hermes_harness_session_fixture : t = 126
let hermes_harness_site_build : t = 127
let hermes_harness_sop_execution : t = 128
let hermes_harness_suite_telemetry : t = 129
let hermes_harness_swarm_algebra : t = 130
let hermes_harness_turn_budget : t = 131
let hermes_harness_turn_preflight : t = 132
let hermes_harness_web_read_model : t = 133
let hermes_jj_protocol : t = 134
let hermes_nix : t = 135
let hermes_ops : t = 136
let hermes_ops_capability : t = 137
let hermes_ops_capability_core : t = 138
let hermes_ops_completion_topology : t = 139
let hermes_ops_config_authority : t = 140
let hermes_ops_dashboard : t = 141
let hermes_ops_governance : t = 142
let hermes_ops_topology : t = 143
let hermes_stanza : t = 144
let hermes_sysml : t = 145
let hermes_vcs : t = 146
let hermes_vision : t = 147
let hermes_wiki_address : t = 148
let hermes_wiki_ast : t = 149
let hermes_wiki_blocks : t = 150
let hermes_wiki_build : t = 151
let hermes_wiki_callout : t = 152
let hermes_wiki_control : t = 153
let hermes_wiki_core : t = 154
let hermes_wiki_datastore : t = 155
let hermes_wiki_diag : t = 156
let hermes_wiki_directive : t = 157
let hermes_wiki_doctest : t = 158
let hermes_wiki_export : t = 159
let hermes_wiki_fpp : t = 160
let hermes_wiki_fpp_interp : t = 161
let hermes_wiki_graph : t = 162
let hermes_wiki_httpd : t = 163
let hermes_wiki_iface : t = 164
let hermes_wiki_include : t = 165
let hermes_wiki_km : t = 166
let hermes_wiki_lifecycle : t = 167
let hermes_wiki_mbse : t = 168
let hermes_wiki_navsearch : t = 169
let hermes_wiki_ordering : t = 170
let hermes_wiki_present : t = 171
let hermes_wiki_query : t = 172
let hermes_wiki_reconcile : t = 173
let hermes_wiki_ref : t = 174
let hermes_wiki_register : t = 175
let hermes_wiki_search : t = 176
let hermes_wiki_sheaf : t = 177
let hermes_wiki_similarity : t = 178
let hermes_wiki_source_ext : t = 179
let hermes_wiki_theme : t = 180
let hermes_wiki_toc : t = 181
let hermes_wiki_topology : t = 182
let hermes_wiki_transclude : t = 183
let hermes_wiki_view : t = 184
let hermes_wiki_visibility : t = 185
let hermes_zellij : t = 186
let run_swarm_bridge_programme : t = 187
let sa_plan : t = 188
let toolchain_core : t = 189
let wiki_baseline_triage : t = 190
let wiki_core : t = 191
let wiki_render : t = 192
let wiki_server : t = 193
let wiki_suite_telemetry : t = 194
