// Generated by tools/generate_ev_recovery_runner.ml; component observations only.
import crdt_health_bridge_test
import crdt_mesh_sync_test
import deadman_freshness_test
import delta_mesh_engine_test
import ev_control_boundary_test
import ev_control_bounds_test
import gleam/io
import heijunka_scheduler_test
import homeostasis_evolution_engine_test
import homeostasis_evolution_hud_test
import multi_agent_quorum_hud_test
import multi_agent_quorum_test
import predictive_autoscaler_hud_test
import predictive_autoscaler_test
import rag_cache_mesh_test
import tui_15_evolutionary_cycles_test
import work_stealing_test

pub fn main() {
  ev_control_bounds_test.pending_proposal_intake_is_bounded_test()
  io.println(
    "PASS ev_control_bounds_test.pending_proposal_intake_is_bounded_test",
  )
  ev_control_bounds_test.fractional_refill_is_partition_invariant_test()
  io.println(
    "PASS ev_control_bounds_test.fractional_refill_is_partition_invariant_test",
  )
  ev_control_bounds_test.partial_token_is_not_issued_early_test()
  io.println(
    "PASS ev_control_bounds_test.partial_token_is_not_issued_early_test",
  )
  ev_control_bounds_test.queue_derivative_uses_elapsed_seconds_test()
  io.println(
    "PASS ev_control_bounds_test.queue_derivative_uses_elapsed_seconds_test",
  )
  ev_control_bounds_test.nonforward_queue_sample_preserves_state_test()
  io.println(
    "PASS ev_control_bounds_test.nonforward_queue_sample_preserves_state_test",
  )
  ev_control_bounds_test.invalid_worker_order_cannot_construct_unsafe_state_test()
  io.println(
    "PASS ev_control_bounds_test.invalid_worker_order_cannot_construct_unsafe_state_test",
  )
  ev_control_bounds_test.negative_worker_limit_cannot_construct_unsafe_state_test()
  io.println(
    "PASS ev_control_bounds_test.negative_worker_limit_cannot_construct_unsafe_state_test",
  )
  ev_control_bounds_test.negative_token_capacity_cannot_construct_unsafe_state_test()
  io.println(
    "PASS ev_control_bounds_test.negative_token_capacity_cannot_construct_unsafe_state_test",
  )
  ev_control_bounds_test.negative_refill_rate_cannot_construct_unsafe_state_test()
  io.println(
    "PASS ev_control_bounds_test.negative_refill_rate_cannot_construct_unsafe_state_test",
  )
  ev_control_bounds_test.nonpositive_latency_cannot_construct_unsafe_state_test()
  io.println(
    "PASS ev_control_bounds_test.nonpositive_latency_cannot_construct_unsafe_state_test",
  )
  ev_control_bounds_test.retired_ratified_snapshot_cannot_regain_authority_test()
  io.println(
    "PASS ev_control_bounds_test.retired_ratified_snapshot_cannot_regain_authority_test",
  )
  ev_control_bounds_test.pending_ballot_cannot_be_retired_test()
  io.println(
    "PASS ev_control_bounds_test.pending_ballot_cannot_be_retired_test",
  )
  ev_control_bounds_test.actor_terminal_retirement_frees_exactly_one_slot_test()
  io.println(
    "PASS ev_control_bounds_test.actor_terminal_retirement_frees_exactly_one_slot_test",
  )
  ev_control_bounds_test.refill_partitions_conserve_fraction_and_saturation_test()
  io.println(
    "PASS ev_control_bounds_test.refill_partitions_conserve_fraction_and_saturation_test",
  )
  ev_control_bounds_test.derivative_tracks_observation_time_independently_of_refill_test()
  io.println(
    "PASS ev_control_bounds_test.derivative_tracks_observation_time_independently_of_refill_test",
  )
  ev_control_boundary_test.outsider_cannot_ratify_test()
  io.println("PASS ev_control_boundary_test.outsider_cannot_ratify_test")
  ev_control_boundary_test.named_peer_cannot_impersonate_sovereign_test()
  io.println(
    "PASS ev_control_boundary_test.named_peer_cannot_impersonate_sovereign_test",
  )
  ev_control_boundary_test.byzantine_fault_is_terminal_test()
  io.println("PASS ev_control_boundary_test.byzantine_fault_is_terminal_test")
  ev_control_boundary_test.negative_debit_is_rejected_test()
  io.println("PASS ev_control_boundary_test.negative_debit_is_rejected_test")
  ev_control_boundary_test.intervention_after_ratification_blocks_apply_test()
  io.println(
    "PASS ev_control_boundary_test.intervention_after_ratification_blocks_apply_test",
  )
  ev_control_boundary_test.physiology_after_ratification_blocks_apply_test()
  io.println(
    "PASS ev_control_boundary_test.physiology_after_ratification_blocks_apply_test",
  )
  ev_control_boundary_test.ratified_replay_is_rejected_test()
  io.println("PASS ev_control_boundary_test.ratified_replay_is_rejected_test")
  ev_control_boundary_test.forged_verdict_without_votes_is_rejected_test()
  io.println(
    "PASS ev_control_boundary_test.forged_verdict_without_votes_is_rejected_test",
  )
  ev_control_boundary_test.mismatched_mutation_is_rejected_test()
  io.println(
    "PASS ev_control_boundary_test.mismatched_mutation_is_rejected_test",
  )
  ev_control_boundary_test.skipped_generation_is_rejected_test()
  io.println(
    "PASS ev_control_boundary_test.skipped_generation_is_rejected_test",
  )
  ev_control_boundary_test.stale_generation_cannot_regress_state_test()
  io.println(
    "PASS ev_control_boundary_test.stale_generation_cannot_regress_state_test",
  )
  ev_control_boundary_test.token_debits_conserve_available_and_consumed_test()
  io.println(
    "PASS ev_control_boundary_test.token_debits_conserve_available_and_consumed_test",
  )
  ev_control_boundary_test.unconfigured_bft_roster_fails_closed_test()
  io.println(
    "PASS ev_control_boundary_test.unconfigured_bft_roster_fails_closed_test",
  )
  ev_control_boundary_test.actor_rejects_forged_votes_and_stale_vote_snapshot_test()
  io.println(
    "PASS ev_control_boundary_test.actor_rejects_forged_votes_and_stale_vote_snapshot_test",
  )
  ev_control_boundary_test.actor_intervention_and_replay_preserve_owned_state_test()
  io.println(
    "PASS ev_control_boundary_test.actor_intervention_and_replay_preserve_owned_state_test",
  )
  ev_control_boundary_test.actor_byzantine_fault_cannot_be_overwritten_test()
  io.println(
    "PASS ev_control_boundary_test.actor_byzantine_fault_cannot_be_overwritten_test",
  )
  ev_control_boundary_test.actor_rejects_unsubmitted_proposal_test()
  io.println(
    "PASS ev_control_boundary_test.actor_rejects_unsubmitted_proposal_test",
  )
  multi_agent_quorum_test.sovereign_identities_test()
  io.println("PASS multi_agent_quorum_test.sovereign_identities_test")
  multi_agent_quorum_test.ballot_creation_test()
  io.println("PASS multi_agent_quorum_test.ballot_creation_test")
  multi_agent_quorum_test.two_of_three_ratification_test()
  io.println("PASS multi_agent_quorum_test.two_of_three_ratification_test")
  multi_agent_quorum_test.two_of_three_rejection_test()
  io.println("PASS multi_agent_quorum_test.two_of_three_rejection_test")
  multi_agent_quorum_test.byzantine_conflicting_vote_detection_test()
  io.println(
    "PASS multi_agent_quorum_test.byzantine_conflicting_vote_detection_test",
  )
  multi_agent_quorum_test.vote_entropy_calculation_test()
  io.println("PASS multi_agent_quorum_test.vote_entropy_calculation_test")
  multi_agent_quorum_test.quorum_engine_record_test()
  io.println("PASS multi_agent_quorum_test.quorum_engine_record_test")
  predictive_autoscaler_test.init_autoscaler_test()
  io.println("PASS predictive_autoscaler_test.init_autoscaler_test")
  predictive_autoscaler_test.token_consumption_and_refill_test()
  io.println(
    "PASS predictive_autoscaler_test.token_consumption_and_refill_test",
  )
  predictive_autoscaler_test.token_exhaustion_test()
  io.println("PASS predictive_autoscaler_test.token_exhaustion_test")
  predictive_autoscaler_test.scale_up_on_queue_spike_test()
  io.println("PASS predictive_autoscaler_test.scale_up_on_queue_spike_test")
  predictive_autoscaler_test.cooldown_inhibits_scaling_test()
  io.println("PASS predictive_autoscaler_test.cooldown_inhibits_scaling_test")
  predictive_autoscaler_test.scale_down_on_idle_queue_test()
  io.println("PASS predictive_autoscaler_test.scale_down_on_idle_queue_test")
  predictive_autoscaler_hud_test.init_autoscaler_hud_test()
  io.println("PASS predictive_autoscaler_hud_test.init_autoscaler_hud_test")
  predictive_autoscaler_hud_test.update_from_autoscaler_test()
  io.println("PASS predictive_autoscaler_hud_test.update_from_autoscaler_test")
  predictive_autoscaler_hud_test.render_svg_and_html_test()
  io.println("PASS predictive_autoscaler_hud_test.render_svg_and_html_test")
  homeostasis_evolution_engine_test.four_party_quorum_members_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.four_party_quorum_members_test",
  )
  homeostasis_evolution_engine_test.pid_homeostasis_convergence_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.pid_homeostasis_convergence_test",
  )
  homeostasis_evolution_engine_test.equilibrium_transition_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.equilibrium_transition_test",
  )
  homeostasis_evolution_engine_test.propose_evolution_blocked_before_homeostasis_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.propose_evolution_blocked_before_homeostasis_test",
  )
  homeostasis_evolution_engine_test.three_of_four_evolution_ratification_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.three_of_four_evolution_ratification_test",
  )
  homeostasis_evolution_engine_test.instability_intervention_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.instability_intervention_test",
  )
  homeostasis_evolution_engine_test.three_of_four_evolution_rejection_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.three_of_four_evolution_rejection_test",
  )
  homeostasis_evolution_engine_test.homeostasis_actor_lifecycle_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.homeostasis_actor_lifecycle_test",
  )
  homeostasis_evolution_engine_test.physiological_homeostasis_gating_test()
  io.println(
    "PASS homeostasis_evolution_engine_test.physiological_homeostasis_gating_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_01_simd_scorer_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_01_simd_scorer_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_02_heijunka_queue_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_02_heijunka_queue_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_03_solo5_microvm_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_03_solo5_microvm_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_04_crdt_delta_sync_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_04_crdt_delta_sync_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_05_lyapunov_pid_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_05_lyapunov_pid_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_06_zenoh_zmof_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_06_zenoh_zmof_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_07_sre_antibody_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_07_sre_antibody_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_08_gospel_rete_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_08_gospel_rete_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_09_solo5_cas_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_09_solo5_cas_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_10_max_mojo_vec_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_10_max_mojo_vec_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_11_prajna_breaker_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_11_prajna_breaker_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_12_quantum_entangle_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_12_quantum_entangle_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_13_chaos_sandbox_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_13_chaos_sandbox_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_14_crdt_sheaf_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_14_crdt_sheaf_test",
  )
  tui_15_evolutionary_cycles_test.evolutionary_cycle_15_otel_stream_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.evolutionary_cycle_15_otel_stream_test",
  )
  tui_15_evolutionary_cycles_test.continuous_15_evolutionary_cycles_e2e_test()
  io.println(
    "PASS tui_15_evolutionary_cycles_test.continuous_15_evolutionary_cycles_e2e_test",
  )
  homeostasis_evolution_hud_test.render_hud_converging_test()
  io.println("PASS homeostasis_evolution_hud_test.render_hud_converging_test")
  homeostasis_evolution_hud_test.render_hud_equilibrium_test()
  io.println("PASS homeostasis_evolution_hud_test.render_hud_equilibrium_test")
  homeostasis_evolution_hud_test.render_hud_live_event_log_test()
  io.println(
    "PASS homeostasis_evolution_hud_test.render_hud_live_event_log_test",
  )
  multi_agent_quorum_hud_test.init_quorum_hud_test()
  io.println("PASS multi_agent_quorum_hud_test.init_quorum_hud_test")
  multi_agent_quorum_hud_test.update_from_engine_test()
  io.println("PASS multi_agent_quorum_hud_test.update_from_engine_test")
  multi_agent_quorum_hud_test.render_svg_and_html_test()
  io.println("PASS multi_agent_quorum_hud_test.render_svg_and_html_test")
  heijunka_scheduler_test.enqueue_priority_ordering_test()
  io.println("PASS heijunka_scheduler_test.enqueue_priority_ordering_test")
  heijunka_scheduler_test.pull_batch_nominal_controller_test()
  io.println("PASS heijunka_scheduler_test.pull_batch_nominal_controller_test")
  heijunka_scheduler_test.pull_batch_throttled_controller_test()
  io.println(
    "PASS heijunka_scheduler_test.pull_batch_throttled_controller_test",
  )
  heijunka_scheduler_test.pull_batch_respects_remaining_concurrency_after_prior_leases_test()
  io.println(
    "PASS heijunka_scheduler_test.pull_batch_respects_remaining_concurrency_after_prior_leases_test",
  )
  heijunka_scheduler_test.pull_batch_halted_controller_test()
  io.println("PASS heijunka_scheduler_test.pull_batch_halted_controller_test")
  heijunka_scheduler_test.task_completion_and_reclaim_test()
  io.println("PASS heijunka_scheduler_test.task_completion_and_reclaim_test")
  heijunka_scheduler_test.reclaim_expired_preserves_original_task_identity_test()
  io.println(
    "PASS heijunka_scheduler_test.reclaim_expired_preserves_original_task_identity_test",
  )
  heijunka_scheduler_test.reclaim_expired_keeps_pending_depth_bounded_test()
  io.println(
    "PASS heijunka_scheduler_test.reclaim_expired_keeps_pending_depth_bounded_test",
  )
  heijunka_scheduler_test.complete_task_does_not_release_another_workers_lease_test()
  io.println(
    "PASS heijunka_scheduler_test.complete_task_does_not_release_another_workers_lease_test",
  )
  heijunka_scheduler_test.complete_task_does_not_release_another_plans_lease_test()
  io.println(
    "PASS heijunka_scheduler_test.complete_task_does_not_release_another_plans_lease_test",
  )
  heijunka_scheduler_test.pull_batch_drains_deferred_reclaims_test()
  io.println(
    "PASS heijunka_scheduler_test.pull_batch_drains_deferred_reclaims_test",
  )
  work_stealing_test.work_stealing_init_test()
  io.println("PASS work_stealing_test.work_stealing_init_test")
  work_stealing_test.work_stealing_enqueue_and_cluster_count_test()
  io.println(
    "PASS work_stealing_test.work_stealing_enqueue_and_cluster_count_test",
  )
  work_stealing_test.work_stealing_victim_selection_heaviest_test()
  io.println(
    "PASS work_stealing_test.work_stealing_victim_selection_heaviest_test",
  )
  work_stealing_test.work_stealing_victim_selection_lyapunov_test()
  io.println(
    "PASS work_stealing_test.work_stealing_victim_selection_lyapunov_test",
  )
  work_stealing_test.work_stealing_request_and_transfer_handshake_test()
  io.println(
    "PASS work_stealing_test.work_stealing_request_and_transfer_handshake_test",
  )
  work_stealing_test.apply_steal_response_is_idempotent_for_a_replayed_transfer_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_is_idempotent_for_a_replayed_transfer_test",
  )
  work_stealing_test.apply_steal_response_deduplicates_tasks_inside_one_transfer_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_deduplicates_tasks_inside_one_transfer_test",
  )
  work_stealing_test.apply_steal_response_keeps_distinct_plan_task_identities_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_keeps_distinct_plan_task_identities_test",
  )
  work_stealing_test.apply_steal_response_remains_replay_safe_after_accepted_work_leaves_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_remains_replay_safe_after_accepted_work_leaves_test",
  )
  work_stealing_test.apply_steal_response_rejects_a_response_for_another_recipient_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_rejects_a_response_for_another_recipient_test",
  )
  work_stealing_test.handle_steal_request_replays_its_original_response_test()
  io.println(
    "PASS work_stealing_test.handle_steal_request_replays_its_original_response_test",
  )
  work_stealing_test.handle_steal_request_rejects_a_request_for_another_donor_test()
  io.println(
    "PASS work_stealing_test.handle_steal_request_rejects_a_request_for_another_donor_test",
  )
  work_stealing_test.apply_steal_response_bounds_empty_transfer_receipts_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_bounds_empty_transfer_receipts_test",
  )
  work_stealing_test.apply_steal_response_requires_a_reserved_request_test()
  io.println(
    "PASS work_stealing_test.apply_steal_response_requires_a_reserved_request_test",
  )
  work_stealing_test.full_receiver_does_not_send_a_request_that_can_strand_donor_work_test()
  io.println(
    "PASS work_stealing_test.full_receiver_does_not_send_a_request_that_can_strand_donor_work_test",
  )
  work_stealing_test.receiver_reserves_the_last_slot_before_requesting_a_single_batch_test()
  io.println(
    "PASS work_stealing_test.receiver_reserves_the_last_slot_before_requesting_a_single_batch_test",
  )
  work_stealing_test.wrong_donor_rejection_cannot_consume_another_donor_reservation_test()
  io.println(
    "PASS work_stealing_test.wrong_donor_rejection_cannot_consume_another_donor_reservation_test",
  )
  delta_mesh_engine_test.health_observation_advances_causal_clock_test()
  io.println(
    "PASS delta_mesh_engine_test.health_observation_advances_causal_clock_test",
  )
  delta_mesh_engine_test.worker_observation_epoch_cannot_regress_test()
  io.println(
    "PASS delta_mesh_engine_test.worker_observation_epoch_cannot_regress_test",
  )
  delta_mesh_engine_test.stale_health_does_not_advance_clock_test()
  io.println(
    "PASS delta_mesh_engine_test.stale_health_does_not_advance_clock_test",
  )
  delta_mesh_engine_test.gossip_queue_is_bounded_test()
  io.println("PASS delta_mesh_engine_test.gossip_queue_is_bounded_test")
  delta_mesh_engine_test.engine_init_test()
  io.println("PASS delta_mesh_engine_test.engine_init_test")
  delta_mesh_engine_test.engine_register_peer_test()
  io.println("PASS delta_mesh_engine_test.engine_register_peer_test")
  delta_mesh_engine_test.engine_local_mutation_and_gossip_test()
  io.println(
    "PASS delta_mesh_engine_test.engine_local_mutation_and_gossip_test",
  )
  delta_mesh_engine_test.engine_two_node_reconciliation_test()
  io.println("PASS delta_mesh_engine_test.engine_two_node_reconciliation_test")
  delta_mesh_engine_test.digest_only_exchange_does_not_claim_remote_state_test()
  io.println(
    "PASS delta_mesh_engine_test.digest_only_exchange_does_not_claim_remote_state_test",
  )
  delta_mesh_engine_test.local_mutation_invalidates_prior_peer_coverage_test()
  io.println(
    "PASS delta_mesh_engine_test.local_mutation_invalidates_prior_peer_coverage_test",
  )
  delta_mesh_engine_test.stale_ack_cannot_restore_peer_coverage_after_local_change_test()
  io.println(
    "PASS delta_mesh_engine_test.stale_ack_cannot_restore_peer_coverage_after_local_change_test",
  )
  delta_mesh_engine_test.stale_ack_cannot_erase_a_newer_peer_frontier_test()
  io.println(
    "PASS delta_mesh_engine_test.stale_ack_cannot_erase_a_newer_peer_frontier_test",
  )
  delta_mesh_engine_test.stale_delta_cannot_erase_a_newer_peer_frontier_test()
  io.println(
    "PASS delta_mesh_engine_test.stale_delta_cannot_erase_a_newer_peer_frontier_test",
  )
  delta_mesh_engine_test.remote_ahead_ack_requests_the_missing_delta_test()
  io.println(
    "PASS delta_mesh_engine_test.remote_ahead_ack_requests_the_missing_delta_test",
  )
  delta_mesh_engine_test.full_two_way_exchange_converges_only_after_remote_delta_test()
  io.println(
    "PASS delta_mesh_engine_test.full_two_way_exchange_converges_only_after_remote_delta_test",
  )
  delta_mesh_engine_test.incoming_merge_invalidates_other_peer_coverage_test()
  io.println(
    "PASS delta_mesh_engine_test.incoming_merge_invalidates_other_peer_coverage_test",
  )
  delta_mesh_engine_test.engine_health_aggregation_test()
  io.println("PASS delta_mesh_engine_test.engine_health_aggregation_test")
  delta_mesh_engine_test.full_queue_rejects_without_advancing_round_and_can_drain_test()
  io.println(
    "PASS delta_mesh_engine_test.full_queue_rejects_without_advancing_round_and_can_drain_test",
  )
  delta_mesh_engine_test.outbound_drain_retains_fifo_and_is_empty_on_repeat_test()
  io.println(
    "PASS delta_mesh_engine_test.outbound_drain_retains_fifo_and_is_empty_on_repeat_test",
  )
  delta_mesh_engine_test.full_queue_defers_delta_application_until_retry_test()
  io.println(
    "PASS delta_mesh_engine_test.full_queue_defers_delta_application_until_retry_test",
  )
  delta_mesh_engine_test.full_queue_can_receive_ack_and_peer_time_does_not_regress_test()
  io.println(
    "PASS delta_mesh_engine_test.full_queue_can_receive_ack_and_peer_time_does_not_regress_test",
  )
  delta_mesh_engine_test.health_only_change_generates_delta_against_previous_clock_test()
  io.println(
    "PASS delta_mesh_engine_test.health_only_change_generates_delta_against_previous_clock_test",
  )
  delta_mesh_engine_test.full_queue_rejects_both_digest_response_branches_test()
  io.println(
    "PASS delta_mesh_engine_test.full_queue_rejects_both_digest_response_branches_test",
  )
  delta_mesh_engine_test.stale_ack_recovery_refuses_when_outbound_queue_is_full_test()
  io.println(
    "PASS delta_mesh_engine_test.stale_ack_recovery_refuses_when_outbound_queue_is_full_test",
  )
  delta_mesh_engine_test.gossip_timestamp_cannot_precede_latest_observation_test()
  io.println(
    "PASS delta_mesh_engine_test.gossip_timestamp_cannot_precede_latest_observation_test",
  )
  delta_mesh_engine_test.repeated_health_sample_is_idempotent_test()
  io.println(
    "PASS delta_mesh_engine_test.repeated_health_sample_is_idempotent_test",
  )
  delta_mesh_engine_test.reversed_same_tick_health_deltas_preserve_latest_sample_test()
  io.println(
    "PASS delta_mesh_engine_test.reversed_same_tick_health_deltas_preserve_latest_sample_test",
  )
  delta_mesh_engine_test.concurrent_same_target_health_converges_in_both_orders_test()
  io.println(
    "PASS delta_mesh_engine_test.concurrent_same_target_health_converges_in_both_orders_test",
  )
  delta_mesh_engine_test.local_health_after_merge_supersedes_same_tick_remote_sample_test()
  io.println(
    "PASS delta_mesh_engine_test.local_health_after_merge_supersedes_same_tick_remote_sample_test",
  )
  delta_mesh_engine_test.successive_gossip_retains_accepted_epoch_test()
  io.println(
    "PASS delta_mesh_engine_test.successive_gossip_retains_accepted_epoch_test",
  )
  delta_mesh_engine_test.incoming_ack_and_digest_observations_advance_outgoing_epoch_test()
  io.println(
    "PASS delta_mesh_engine_test.incoming_ack_and_digest_observations_advance_outgoing_epoch_test",
  )
  delta_mesh_engine_test.newer_sample_time_wins_over_an_older_logical_counter_test()
  io.println(
    "PASS delta_mesh_engine_test.newer_sample_time_wins_over_an_older_logical_counter_test",
  )
  deadman_freshness_test.repeated_trip_emits_no_duplicate_actions_test()
  io.println(
    "PASS deadman_freshness_test.repeated_trip_emits_no_duplicate_actions_test",
  )
  deadman_freshness_test.backward_tick_cannot_clear_a_trip_test()
  io.println(
    "PASS deadman_freshness_test.backward_tick_cannot_clear_a_trip_test",
  )
  deadman_freshness_test.stale_heartbeat_cannot_recover_a_trip_test()
  io.println(
    "PASS deadman_freshness_test.stale_heartbeat_cannot_recover_a_trip_test",
  )
  deadman_freshness_test.fresh_recovery_rearms_one_new_trip_test()
  io.println(
    "PASS deadman_freshness_test.fresh_recovery_rearms_one_new_trip_test",
  )
  deadman_freshness_test.exact_single_interval_trips_test()
  io.println("PASS deadman_freshness_test.exact_single_interval_trips_test")
  deadman_freshness_test.repeated_warning_and_duplicate_tick_are_quiet_test()
  io.println(
    "PASS deadman_freshness_test.repeated_warning_and_duplicate_tick_are_quiet_test",
  )
  deadman_freshness_test.invalid_intervals_are_quarantined_and_not_heartbeat_recovered_test()
  io.println(
    "PASS deadman_freshness_test.invalid_intervals_are_quarantined_and_not_heartbeat_recovered_test",
  )
  deadman_freshness_test.stale_reregistration_cannot_clear_a_trip_test()
  io.println(
    "PASS deadman_freshness_test.stale_reregistration_cannot_clear_a_trip_test",
  )
  deadman_freshness_test.actor_order_is_stable_across_ticks_test()
  io.println(
    "PASS deadman_freshness_test.actor_order_is_stable_across_ticks_test",
  )
  deadman_freshness_test.explicit_valid_configuration_can_recover_quarantine_test()
  io.println(
    "PASS deadman_freshness_test.explicit_valid_configuration_can_recover_quarantine_test",
  )
  deadman_freshness_test.heartbeat_at_trip_observation_time_does_not_rearm_test()
  io.println(
    "PASS deadman_freshness_test.heartbeat_at_trip_observation_time_does_not_rearm_test",
  )
  deadman_freshness_test.deadman_init_test()
  io.println("PASS deadman_freshness_test.deadman_init_test")
  deadman_freshness_test.deadman_registration_nominal_test()
  io.println("PASS deadman_freshness_test.deadman_registration_nominal_test")
  deadman_freshness_test.deadman_warning_escalation_test()
  io.println("PASS deadman_freshness_test.deadman_warning_escalation_test")
  deadman_freshness_test.deadman_trip_and_failover_test()
  io.println("PASS deadman_freshness_test.deadman_trip_and_failover_test")
  crdt_health_bridge_test.record_and_merge_health_test()
  io.println("PASS crdt_health_bridge_test.record_and_merge_health_test")
  crdt_health_bridge_test.health_telemetry_lww_convergence_test()
  io.println(
    "PASS crdt_health_bridge_test.health_telemetry_lww_convergence_test",
  )
  crdt_mesh_sync_test.mesh_sync_digest_and_drift_test()
  io.println("PASS crdt_mesh_sync_test.mesh_sync_digest_and_drift_test")
  crdt_mesh_sync_test.mesh_sync_reconciliation_and_ack_test()
  io.println("PASS crdt_mesh_sync_test.mesh_sync_reconciliation_and_ack_test")
  rag_cache_mesh_test.new_cache_mesh_test()
  io.println("PASS rag_cache_mesh_test.new_cache_mesh_test")
  rag_cache_mesh_test.dot_product_and_norm_test()
  io.println("PASS rag_cache_mesh_test.dot_product_and_norm_test")
  rag_cache_mesh_test.cosine_similarity_test()
  io.println("PASS rag_cache_mesh_test.cosine_similarity_test")
  rag_cache_mesh_test.exact_and_semantic_lookup_test()
  io.println("PASS rag_cache_mesh_test.exact_and_semantic_lookup_test")
  rag_cache_mesh_test.record_hit_and_miss_test()
  io.println("PASS rag_cache_mesh_test.record_hit_and_miss_test")
  rag_cache_mesh_test.lru_capacity_and_expiry_test()
  io.println("PASS rag_cache_mesh_test.lru_capacity_and_expiry_test")
  rag_cache_mesh_test.vector_refresh_test()
  io.println("PASS rag_cache_mesh_test.vector_refresh_test")
  rag_cache_mesh_test.expired_lookup_is_not_returned_as_a_hit_test()
  io.println(
    "PASS rag_cache_mesh_test.expired_lookup_is_not_returned_as_a_hit_test",
  )
  rag_cache_mesh_test.put_refuses_negative_counts_and_oversize_vectors_test()
  io.println(
    "PASS rag_cache_mesh_test.put_refuses_negative_counts_and_oversize_vectors_test",
  )
  rag_cache_mesh_test.refresh_updates_the_freshness_observation_test()
  io.println(
    "PASS rag_cache_mesh_test.refresh_updates_the_freshness_observation_test",
  )
  rag_cache_mesh_test.refresh_refuses_an_empty_vector_test()
  io.println("PASS rag_cache_mesh_test.refresh_refuses_an_empty_vector_test")
  rag_cache_mesh_test.lookup_before_content_observation_is_stale_test()
  io.println(
    "PASS rag_cache_mesh_test.lookup_before_content_observation_is_stale_test",
  )
  rag_cache_mesh_test.refresh_before_embedding_observation_preserves_embedding_test()
  io.println(
    "PASS rag_cache_mesh_test.refresh_before_embedding_observation_preserves_embedding_test",
  )
  rag_cache_mesh_test.semantic_lookup_requires_matching_dimensions_test()
  io.println(
    "PASS rag_cache_mesh_test.semantic_lookup_requires_matching_dimensions_test",
  )
  rag_cache_mesh_test.semantic_lookup_refuses_extreme_embedding_without_arithmetic_test()
  io.println(
    "PASS rag_cache_mesh_test.semantic_lookup_refuses_extreme_embedding_without_arithmetic_test",
  )
  rag_cache_mesh_test.accepted_embedding_boundary_has_stable_cosine_test()
  io.println(
    "PASS rag_cache_mesh_test.accepted_embedding_boundary_has_stable_cosine_test",
  )
  rag_cache_mesh_test.tiny_nonzero_vectors_preserve_analytic_similarity_test()
  io.println(
    "PASS rag_cache_mesh_test.tiny_nonzero_vectors_preserve_analytic_similarity_test",
  )
  rag_cache_mesh_test.tiny_accepted_embedding_can_semantically_match_test()
  io.println(
    "PASS rag_cache_mesh_test.tiny_accepted_embedding_can_semantically_match_test",
  )
  rag_cache_mesh_test.subnormal_identity_and_zero_vector_controls_test()
  io.println(
    "PASS rag_cache_mesh_test.subnormal_identity_and_zero_vector_controls_test",
  )
  io.println("177 component invocations passed; EV admission NOT_GRANTED")
}
