(* gen_markdown_baseline — freeze the wiki's rendering as a committed baseline.

   WHY. The AST renderer was admitted by differential against the streaming
   renderer over every real document. Retiring that oracle would delete the
   specification, so the guarantee is transferred here first: a digest per
   document, taken from the rendering the differential proved equivalent, and
   committed. `LAW CORPUS-BASELINE` then pins every future rendering to it
   without needing the old implementation to exist.

   WHAT IS DIGESTED. Two digests per document: the CONTENT (the markdown
   source) and the RENDERING (the normalized token stream). The rendering
   digest is the guarantee; the content digest is what makes it usable.

   WHY BOTH — a defect in the first version of this file, found the same day it
   landed. Digesting only the rendering pins it to the CONTENT of the live
   corpus, so editing any document reddens the gate and the only way to green
   it is to regenerate. Two journals regenerated by a concurrent session did
   exactly that within the hour. A guard whose normal failure mode is "run the
   generator again" teaches everyone to run the generator reflexively, and then
   it is no longer a guard — it is a formality that fires on the wrong events
   and gets waved through on the right ones.

   With both digests the law says the thing it actually means: for every
   document whose CONTENT is unchanged, the RENDERING must be unchanged. A
   document someone edited carries no information about the renderer, so it is
   skipped — and COUNTED, because the strength of this baseline is exactly the
   number of content-stable documents behind it. A renderer change still drifts
   every one of them at once; a prose edit drifts nothing.

   The normalized token stream, not raw bytes, is what the rendering digest
   covers — the same equivalence the differential used, so attribute quoting
   and whitespace next to a block boundary do not trip it while a changed
   class, id, attribute value, element or text run does. `GUARD
   NORMALIZER-DISCRIMINATES` and `GUARD NORMALIZER-KEEPS-INLINE-GAPS` in
   `markdown_ast_laws.ml` are what make that a meaningful statement rather than
   a hopeful one.

   REGENERATION IS A DELIBERATE ACT. This executable is never run by the gate.
   Rewriting the baseline to make a red gate green would silently accept a
   rendering change across the corpus, so a cycle that regenerates it owes a
   visible `regen:` disclosure — the same rule every other generated artifact
   here follows. *)

let rec walk acc dir =
  Array.fold_left
    (fun acc e ->
      let p = Filename.concat dir e in
      if (try Sys.is_directory p with Sys_error _ -> false) then walk acc p
      else if Filename.check_suffix p ".md" then p :: acc
      else acc)
    acc
    (try Sys.readdir dir with Sys_error _ -> [||])

let read p =
  let ic = open_in_bin p in
  let s = really_input_string ic (in_channel_length ic) in
  close_in ic;
  s

let () =
  let root = if Array.length Sys.argv > 1 then Sys.argv.(1) else Sys.getcwd () in
  let files = List.sort compare (walk [] (Filename.concat root "docs")) in
  let pages = List.filter_map (fun p -> try Some (p, read p) with _ -> None) files in
  let tbl = Hashtbl.create 1024 in
  List.iter
    (fun (p, _) ->
      let b = Filename.remove_extension (Filename.basename p) in
      Hashtbl.replace tbl (String.lowercase_ascii b) (Wiki_render.Markdown_ast.znorm b))
    pages;
  let resolve k = Hashtbl.find_opt tbl (String.lowercase_ascii k) in
  let out = Buffer.create (64 * List.length pages) in
  Buffer.add_string out
    "# markdown render baseline — <render-digest> <content-digest> <path>.\n\
     # render-digest  = the NORMALIZED token stream the AST produces\n\
     # content-digest = the markdown source it was produced from\n\
     # The law checks the rendering ONLY where the content still matches, so an\n\
     # edited document is skipped rather than reported as renderer drift.\n\
     # Generated by harness/gen_markdown_baseline.ml. Regenerating is a deliberate\n\
     # act and owes a visible `regen:` disclosure: it accepts a rendering change\n\
     # across every listed document.\n";
  List.iter
    (fun (p, md) ->
      let html =
        Wiki_render.Markdown_ast.render_string ~resolve
          (Wiki_render.Markdown_ast.parse_with_resolve ~resolve md)
      in
      let toks = Wiki_render.Markdown_ast_laws.normalize html in
      let digest = Digest.to_hex (Digest.string (String.concat "\031" toks)) in
      let content = Digest.to_hex (Digest.string md) in
      let rel =
        let rl = String.length root + 1 in
        if String.length p > rl && String.sub p 0 (String.length root) = root then
          String.sub p rl (String.length p - rl)
        else p
      in
      Buffer.add_string out (Printf.sprintf "%s %s %s\n" digest content rel))
    pages;
  let path = Filename.concat root "docs/design/markdown-render-baseline.txt" in
  let oc = open_out_bin path in
  output_string oc (Buffer.contents out);
  close_out oc;
  Printf.printf "wrote %s (%d documents)\n" path (List.length pages)
