type node_kind = Declaration | Command | Surface | Activity | Receipt | Criterion | Metric | Model
type node = { node_id : string; kind : node_kind; obligation_id : string }
type relation = Declares | Projects | Executes | Produces | Satisfies | Measures | Models
type edge = { source : string; relation : relation; target : string }

let suffix id value = id ^ ":" ^ value

let surface_suffix = function
  | Ops_capability.Ocaml_api -> "surface:ocaml-api"
  | Cli -> "surface:cli" | Mcp -> "surface:mcp" | Zenoh -> "surface:zenoh"

let surfaces = Ops_capability.[ Ocaml_api; Cli; Mcp; Zenoh ]

let nodes_for (item : Ops_governance.obligation) =
  let node kind name = { node_id = suffix item.id name; kind; obligation_id = item.id } in
  [ node Declaration "declaration"; node Command "command";
    node Activity "activity"; node Receipt "receipt"; node Criterion "criterion";
    node Metric "metric"; node Model "model" ]
  @ List.map (fun surface -> node Surface (surface_suffix surface)) surfaces

let edges_for (item : Ops_governance.obligation) =
  let id = item.id in
  let edge source relation target =
    { source = suffix id source; relation; target = suffix id target }
  in
  [ edge "declaration" Declares "command";
    edge "model" Models "activity";
    edge "activity" Produces "receipt";
    edge "receipt" Satisfies "criterion";
    edge "activity" Measures "metric" ]
  @ List.concat_map
      (fun surface ->
        let name = surface_suffix surface in
        [ edge "command" Projects name; edge name Executes "activity" ])
      surfaces

let nodes = List.concat_map nodes_for Ops_governance.obligations
let edges = List.concat_map edges_for Ops_governance.obligations

let paths_to_criterion obligation_id =
  match Ops_governance.find_obligation obligation_id with
  | None -> []
  | Some _ ->
      List.map
        (fun surface ->
          [ suffix obligation_id "declaration"; suffix obligation_id "command";
            suffix obligation_id (surface_suffix surface); suffix obligation_id "activity";
            suffix obligation_id "receipt"; suffix obligation_id "criterion" ])
        surfaces

let validate () =
  let errors = ref [] in
  let add message = errors := message :: !errors in
  let ids = List.map (fun node -> node.node_id) nodes in
  if nodes = [] then add "ontology is empty";
  if List.length ids <> List.length (List.sort_uniq compare ids) then add "duplicate ontology node";
  List.iter
    (fun edge ->
      if not (List.mem edge.source ids) then add ("edge source missing: " ^ edge.source);
      if not (List.mem edge.target ids) then add ("edge target missing: " ^ edge.target))
    edges;
  List.iter
    (fun (item : Ops_governance.obligation) ->
      let paths = paths_to_criterion item.id in
      if List.length paths <> 4 then add (item.id ^ ": not four surface paths");
      List.iter
        (fun path ->
          let rec check_edges = function
            | [] | [ _ ] -> ()
            | source :: (target :: _ as rest) ->
                if not (List.exists (fun edge -> edge.source = source && edge.target = target) edges)
                then add (item.id ^ ": broken path " ^ source ^ " -> " ^ target);
                check_edges rest
          in
          check_edges path)
        paths)
    Ops_governance.obligations;
  List.rev !errors

let lifecycle_rank = function
  | Ops_capability.Declared -> 0 | Implemented -> 1 | Executed -> 2 | Current -> 3

let lifecycle_leq left right = lifecycle_rank left <= lifecycle_rank right

type parity_admission = Grant | Block | Deny

let parity_level = function Ops_capability.L4 | L5 | L6 -> true | _ -> false

let admit_parity ~level ~evidence ~origin ~divergent =
  if evidence <> Ops_capability.Differential || not (parity_level level) then Block
  else if divergent then
    if origin = Ops_capability.Implementation then Deny else Block
  else Grant

let surface_homomorphism receipts =
  match receipts with
  | first :: rest when List.length receipts = 4 ->
      let normalized = Ops_command.receipt_json first in
      List.for_all (fun receipt -> Ops_command.receipt_json receipt = normalized) rest
  | _ -> false

let ooda_closed = function
  | Ops_capability.[ Observe; Orient; Decide; Act; Observe ] -> true
  | _ -> false

let semantic_denominator () =
  List.concat_map
    (fun (item : Ops_governance.obligation) ->
      List.map (fun coordinate -> (item.id, coordinate)) item.path)
    Ops_governance.obligations

let formal_smt2 () =
  "; generated by Ops_governance_model.formal_smt2\n\
   (set-logic QF_LIA)\n\
   ; negated_surface_totality: a value constrained to the four constructors cannot be outside them\n\
   (push)\n\
   (declare-const surface Int)\n\
   (assert (and (<= 0 surface) (<= surface 3)))\n\
   (assert (not (or (= surface 0) (= surface 1) (= surface 2) (= surface 3))))\n\
   (check-sat)\n\
   (pop)\n\
   ; negated_ooda_order: the authored closed sequence cannot differ from itself\n\
   (push)\n\
   (declare-const o0 Int) (declare-const o1 Int) (declare-const o2 Int)\n\
   (declare-const o3 Int) (declare-const o4 Int)\n\
   (assert (and (= o0 0) (= o1 1) (= o2 2) (= o3 3) (= o4 0)))\n\
   (assert (not (and (= o0 0) (= o1 1) (= o2 2) (= o3 3) (= o4 0))))\n\
   (check-sat)\n\
   (pop)\n\
   ; non_vacuous_sat_control: prove the checker can also find a model\n\
   (push)\n\
   (declare-const live_control Bool)\n\
   (assert live_control)\n\
   (check-sat)\n\
   (pop)\n"
