(* Emits stanza.ml / stanza.mli from the live dune graph.

   The point is unforgeability: after this, `~targets:[ Stanza.hermes_wiki ]`
   does not typecheck, because hermes_wiki is a directory and not a library.
   The 182 declared names that are not graph nodes become compile errors
   rather than confident-looking strings.

   Integer witnesses rather than a variant with one constructor per library:
   values are plain ints, so adding a library does not invalidate every
   pattern match in the workspace. Abstractness is what makes them
   unforgeable, not the representation. *)

let root = "modules"

let sanitise name =
  String.map (fun c -> if c = '.' || c = '-' then '_' else c) name

let () =
  let output_mli = ref false in
  Arg.parse
    [ ("--mli", Arg.Set output_mli, "emit the interface instead of the implementation") ]
    (fun _ -> ())
    "gen_stanza [--mli]";
  let libs =
    match Dune_graph.libraries ~root with
    | Error e ->
        prerr_endline ("REFUSED: " ^ Dune_graph.string_of_parse_error e);
        exit 1
    | Ok l -> l
  in
  let graph = Dune_graph.of_libraries libs in
  let names = Dune_graph.nodes graph in
  let indexed = List.mapi (fun i n -> (n, i)) names in
  let index_of n = List.assoc n indexed in
  let file_of n =
    match List.find_opt (fun (item : Dune_graph.library) -> item.lib_name = n) libs with
    | Some item -> item.lib_file
    | None -> invalid_arg ("gen_stanza: graph node has no library row: " ^ n)
  in
  let b = Buffer.create 65536 in
  let p fmt = Printf.ksprintf (Buffer.add_string b) fmt in

  p "(* GENERATED by gen_stanza.exe from the dune library graph.\n";
  p "   Do not edit. A dune rule regenerates this and diffs it, so drift\n";
  p "   fails the build rather than rotting quietly.\n\n";
  p "   %d libraries. A value of this type is a WITNESS that the library\n"
    (List.length names);
  p "   exists in the graph; there is no way to make one from a string, which\n";
  p "   is the whole point. *)\n\n";

  if !output_mli then begin
    p "type t\n\n";
    p "val name : t -> string\n";
    p "val dune_file : t -> string\n";
    p "val owner_directory : t -> string\n";
    p "val equal : t -> t -> bool\n";
    p "val compare : t -> t -> int\n";
    p "val all : t list\n\n";
    p "(** The reverse dependency cone, baked in from the graph at generation\n";
    p "    time: everything that would be affected if this library were wrong.\n";
    p "    Excludes the library itself. *)\n";
    p "val cone : t -> t list\n\n";
    p "(** Union of the cones of several targets, minus the targets. This is\n";
    p "    the additive law: [cone_of (S @ T) = cone_of S union cone_of T]. *)\n";
    p "val cone_of : t list -> t list\n\n";
    p "(** {1 The libraries} *)\n\n";
    List.iter (fun n -> p "val %s : t\n" (sanitise n)) names
  end
  else begin
    p "type t = int\n\n";
    p "let names = [|\n";
    List.iter (fun n -> p "  %S;\n" n) names;
    p "|]\n\n";
    p "let dune_files = [|\n";
    List.iter (fun n -> p "  %S;\n" (file_of n)) names;
    p "|]\n\n";
    p "let name t = names.(t)\n";
    p "let dune_file t = dune_files.(t)\n";
    p "let owner_directory t = Filename.dirname (dune_file t)\n";
    p "let equal (a : t) b = a = b\n";
    p "let compare (a : t) b = Stdlib.compare a b\n";
    p "let all = List.init (Array.length names) (fun i -> i)\n\n";
    (* the cone table, computed once here rather than at every call site *)
    p "(* cone.(i) is the reverse dependency cone of library i, as indices. *)\n";
    p "let cone_table = [|\n";
    List.iter
      (fun n ->
        let c = Dune_graph.cone graph n in
        p "  [| %s |];\n"
          (String.concat "; " (List.map (fun d -> string_of_int (index_of d)) c)))
      names;
    p "|]\n\n";
    p "let cone t = Array.to_list cone_table.(t)\n\n";
    p "module IntSet = Set.Make (Int)\n\n";
    p "let cone_of targets =\n";
    p "  let seeds = IntSet.of_list targets in\n";
    p "  let reached =\n";
    p "    List.fold_left\n";
    p "      (fun acc t -> List.fold_left (fun a x -> IntSet.add x a) acc (cone t))\n";
    p "      IntSet.empty targets\n";
    p "  in\n";
    p "  IntSet.elements (IntSet.diff reached seeds)\n\n";
    p "(* {1 The libraries} *)\n\n";
    List.iter (fun n -> p "let %s : t = %d\n" (sanitise n) (index_of n)) names
  end;
  print_string (Buffer.contents b)
