#use "topfind";;
#require "yojson,cryptokit,unix";;
let root="/home/an/NAS-setup/uos"
let own=".uos-workspaces/ev98-peer-loop-20260909"
let author=".uos-workspaces/ev98-wire-codec-20260909"
let now=Unix.gettimeofday()
let iso n=let t=Unix.gmtime n in Printf.sprintf "%04d-%02d-%02dT%02d:%02d:%02dZ"(t.tm_year+1900)(t.tm_mon+1)t.tm_mday t.tm_hour t.tm_min t.tm_sec
let set k v xs=(k,v)::List.remove_assoc k xs
let strings xs=`List(List.map(fun s->`String s)xs)
let sha p=let c=open_in_bin p in let h=Cryptokit.hash_channel(Cryptokit.Hash.sha256())c in close_in c;Cryptokit.transform_string(Cryptokit.Hexa.encode())h
let () =
 let base=match Yojson.Safe.from_file(root^"/"^own^"/docs/reviews/20260909-1545-ev101-graph-risk-1788969563.json")with`List[`Assoc xs]->xs|_->failwith "template"in
 let paths=List.map(fun p->author^"/"^p)["engines/hermes/modules/system_engg/gospel_dispatch_contracts.ml";"engines/hermes/modules/system_engg/gospel_dispatch_contracts.mli";"engines/hermes/modules/system_engg/test_gospel_dispatch_contracts.ml";"tools/test_ev107_digest.ml"]in
 let refs=strings paths in
 let factors=match List.assoc "factors" base with`Assoc fs->`Assoc(List.map(fun(k,v)->match v with`Assoc xs->k,`Assoc(xs|>set "evidence_refs"refs|>set "rationale"(`String "Independent component review must distinguish exact payload digest equality and matching rejections from actual dispatch or formal authority; finite native probes constrain misleading parity evidence."))|_->k,v)fs)|_->failwith "factors"in
 let decision=match List.assoc "decision"base with`Assoc xs->`Assoc(xs|>set "summary"(`String "Read-only independent review of immutable EV107 digest11eeca9; compile and probe in private directories only, with own review records in peer workspace.")|>set "acceptance"(strings["Verify four immutable source files and actual callers";"Fresh native compiled known-digest and expectation-refusal probes";"Actual private primary/reference digest and rejection disagreement controls";"Author evidence artifact rehash and launch inspection";"Machine-readable bounded verdict; no full EV/admission"] )|>set "residuals"(strings["Comparison agreement may mean both filters reject";"Shared SQL/digest helpers are not independent proofs";"No runtime dispatch/Rete/crosshost/formal solver observation";"Cooperative filesystem/local compilation, not hermetic release or producer authentication"] )|>set "supersedes"(`String "New independent REVIEW task under PROGRAM attempt5; EV101 source frozen and its REPAIR task stays separate")|>set "forecast"(`String "Exact expectation and result comparison should refuse altered digest/rejection outcomes; tests cannot authenticate a producer.")|>set "falsifier"(`String "Mismatching expected digest or primary/reference result is returned as successful comparison.")|>set "assumptions"(strings["Parent authorizes independent bounded review and renewed epoch2 peer workspace through17:18";"Candidate remains immutable; only own docs and private probes may be written"]))|_->failwith "decision"in
 let stpa=`Assoc["controller",`String "Independent digest component reviewer";"control_action",`String "Assess exact digest and refusal agreement at immutable source";"losses",strings["L-RISK-UNAUTHORIZED-EFFECT"];"hazards",strings["H-RISK-FALSE-CLEARANCE"];"ucas",`List(List.map(fun(typ,context,c)->`Assoc["type",`String typ;"applicability",`String "applicable";"context",`String context;"hazard_ids",strings["H-RISK-FALSE-CLEARANCE"];"constraint",`String c])[
 "not_provided","Missing negative controls conceal ignored digest expectations.","Run immutable known digest/refusal and mutated disagreement probes.";
 "provided_unsafe","Agreement is described as dispatch approval or formal proof.","Report comparison-only semantics and actual caller limits; no admission.";
 "wrong_timing","Mutable source or stale authority substitutes reviewed bytes.","Explicit commit_id extraction, source digests and current review task active check.";
 "duration","A test child or evidence read exceeds review scope.","Private files, direct native argv, bounded child deadline and output, no runtime/task mutation beyond own review records."
 ])]in
 let fields=base|>set "assessment_id"(`String(Printf.sprintf "ev107-review-%.0f"now))|>set "plan_id"(`String "uos/ev107-digest-review/20260909")|>set "task_id"(`String "REVIEW")|>set "actor"(`String "codex-ev107-digest-review")|>set "phase"(`String "review")|>set "task_state"(`String Sys.argv.(1))|>set "scope"(`String "Read-only four-file EV107 digest candidate11eeca9; private OCaml fixtures and own peer-workspace review docs only; EV101 source unchanged")|>set "observed_at"(`String(iso now))|>set "ready_since"(`String(iso now))|>set "valid_until"(`String(iso(now+.3600.)))|>set "snapshot"(`Assoc["kind",`String "working_tree";"reference",`String "Author frozen candidate11eeca9 source paths; immutable extraction will independently verify these hashes before compilation";"evidence",`List(List.map(fun p->`Assoc["path",`String p;"sha256",`String(sha(root^"/"^p));"observed_at",`String(iso now)])paths)])|>set "factors"factors|>set "decision"decision|>set "stpa_analysis"stpa|>set "fmea_modes"(`List[`Assoc["id",`String "FM-DIGEST-COMPARISON";"s",`Int 3;"o",`Int 4;"det",`Int 3;"rpn",`Int 36;"band",`Int 4;"cause",`String "Ignored expectation or shallow outcome comparison can falsely report agreement.";"effect",`String "Misleading component correctness evidence.";"controls",`String "Known independent vectors, wrong expectation and private mismatch controls; bounded source-specific review."]])in
 let path=own^"/docs/reviews/20260909-1620-ev107-review-risk-"^Printf.sprintf "%.0f"now^".json"in let c=open_out_gen[Open_wronly;Open_creat;Open_excl]0o600(root^"/"^path)in output_string c(Yojson.Safe.pretty_to_string(`List[`Assoc fields]));close_out c;print_endline path
