#use "topfind";;
#require "yojson,cryptokit,unix";;
let root="/home/an/NAS-setup/uos"
let own=".uos-workspaces/ev98-peer-loop-20260909"
let now=Unix.gettimeofday()
let iso n=let t=Unix.gmtime n in Printf.sprintf "%04d-%02d-%02dT%02d:%02d:%02dZ"(t.tm_year+1900)(t.tm_mon+1)t.tm_mday t.tm_hour t.tm_min t.tm_sec
let set k v xs=(k,v)::List.remove_assoc k xs
let strings xs=`List(List.map(fun s->`String s)xs)
let sha p=let c=open_in_bin p in let h=Cryptokit.hash_channel(Cryptokit.Hash.sha256())c in close_in c;Cryptokit.transform_string(Cryptokit.Hexa.encode())h
let ()=
 let base=match Yojson.Safe.from_file(root^"/"^own^"/docs/reviews/20260909-1620-ev107-review-risk-1788971064.json")with`List[`Assoc xs]->xs|_->failwith "template"in
 let paths=List.map(fun p->own^"/"^p)(["apps/cepaf_gleam/src/cepaf_gleam/math/rete.gleam";"apps/cepaf_gleam/src/cepaf_gleam/knowledge/rete_ul_verifier.gleam"]@List.filter(fun p->Sys.file_exists(root^"/"^own^"/"^p))["tools/ev107_rete_reference.ml"])in
 let refs=strings paths in
 let factors=match List.assoc "factors"base with`Assoc fs->`Assoc(List.map(fun(k,v)->match v with`Assoc xs->k,`Assoc(xs|>set "evidence_refs"refs|>set "rationale"(`String "Independent finite reachability oracle constrains false assertion-closure evidence; no production dispatch or runtime changes."))|_->k,v)fs)|_->failwith "factors"in
 let decision=match List.assoc "decision"base with`Assoc xs->`Assoc(xs|>set "summary"(`String "Prepare independent native receipt oracle then review immutable static Rete closure source; production files remain read-only.")|>set "acceptance"(strings["Exactly2048 unique tuples for64edge masks16seed masks2orders";"Independent reflexive transitive reachability facts and antecedent edge count";"Malformed/duplicate/missing/tampered/abnormal receipt refusal controls";"Actual immutable candidate replay and typed atomic refusal review once source is available"] )|>set "assumptions"(strings["Static add-only facts and each rule fires at most once; no variable binding or retraction";"Parent owns production implementation; reviewer only helper and evidence in own epoch2 peer workspace"] )|>set "residuals"(strings["Finite four-node acyclic corpus only; not arbitrary Rete proof";"Local receipt cannot authenticate producer or source without external binding";"No live effects, formal solver or full EV admission"] )|>set "supersedes"(`String "New independent Rete REVIEW task; earlier graph and digest tasks completed")|>set "forecast"(`String "Reachability relation detects missing asserted facts despite plausible fired counts.")|>set "falsifier"(`String "Oracle accepts missing, duplicate or incorrect closure rows or abnormal child output."))|_->failwith "decision"in
 let stpa=`Assoc["controller",`String "Independent static closure receipt reviewer";"control_action",`String "Assess finite assertion closure and coverage";"losses",strings["L-RISK-UNAUTHORIZED-EFFECT"];"hazards",strings["H-RISK-FALSE-CLEARANCE"];"ucas",`List(List.map(fun(typ,c,k)->`Assoc["type",`String typ;"applicability",`String "applicable";"context",`String c;"hazard_ids",strings["H-RISK-FALSE-CLEARANCE"];"constraint",`String k])[
 "not_provided","Missing output facts concealed by count-only checks.","Check exact closure bitmask against independent reachability.";
 "provided_unsafe","Forged/incomplete corpus accepted as full behavior.","Exact unique coverage and digest/normal outcome validation; no authenticated producer claim.";
 "wrong_timing","Mutable implementation or expired task reused.","Fresh task observation and immutable candidate binding before replay.";
 "duration","Unbounded receipt or parser exceeds review scope.","Bound file/output/nesting/rows and native test child deadlines." ])]in
 let fields=base|>set "assessment_id"(`String(Printf.sprintf "ev107-rete-review-%.0f"now))|>set "plan_id"(`String "uos/ev107-rete-review/20260909")|>set "actor"(`String "codex-ev107-rete-review")|>set "task_state"(`String Sys.argv.(1))|>set "scope"(`String "Independent tools/ev107_rete_reference.ml and own review evidence only; candidate production source read-only")|>set "observed_at"(`String(iso now))|>set "ready_since"(`String(iso now))|>set "valid_until"(`String(iso(now+.3600.)))|>set "snapshot"(`Assoc["kind",`String "working_tree";"reference",`String "Own peer workspace historical Rete context plus oracle when created; production candidate bound separately before later replay";"evidence",`List(List.map(fun p->`Assoc["path",`String p;"sha256",`String(sha(root^"/"^p));"observed_at",`String(iso now)])paths)])|>set "factors"factors|>set "decision"decision|>set "stpa_analysis"stpa|>set "fmea_modes"(`List[`Assoc["id",`String "FM-ASSERTION-CLOSURE";"s",`Int 3;"o",`Int 4;"det",`Int 3;"rpn",`Int 36;"band",`Int 4;"cause",`String "Count-only result and duplicate-condition reasoning conceal assertion closure defects.";"effect",`String "Misleading correctness evidence.";"controls",`String "Independent finite reachability and complete corpus/refusal controls."]])in
 let path=own^"/docs/reviews/20260909-1635-ev107-rete-review-risk-"^Printf.sprintf "%.0f"now^".json"in
 let c=open_out_gen[Open_wronly;Open_creat;Open_excl]0o600(root^"/"^path)in output_string c(Yojson.Safe.pretty_to_string(`List[`Assoc fields]));close_out c;print_endline path
