type t = {
  title : string;
  source_path : string;
  markdown : string;
  artifacts : artifact list;
  rendered_body : string option;
}

and artifact =
  | Text of { label : string; content : string }
  | Image of { label : string; mime_type : string; base64 : string }
  | Video of { label : string; mime_type : string; base64 : string;
      sha256 : string; bytes : int; provenance : string }
  | Download of { label : string; mime_type : string; base64 : string;
      sha256 : string; bytes : int; provenance : string }

let create ~title ~source_path ~markdown =
  { title; source_path; markdown; artifacts = []; rendered_body = None }

let text_artifact ~label ~content = Text { label; content }
let image_artifact ~label ~mime_type ~base64 =
  Image { label; mime_type; base64 }
let video_artifact ~label ~mime_type ~base64 ~sha256 ~bytes ~provenance =
  Video { label; mime_type; base64; sha256; bytes; provenance }
let download_artifact ~label ~mime_type ~base64 ~sha256 ~bytes ~provenance =
  Download { label; mime_type; base64; sha256; bytes; provenance }

let with_artifacts document artifacts = { document with artifacts }
let with_rendered_body document rendered_body =
  { document with rendered_body = Some rendered_body }

let html_escape value =
  let buffer = Buffer.create (String.length value + 16) in
  String.iter
    (function
      | '&' -> Buffer.add_string buffer "&amp;"
      | '<' -> Buffer.add_string buffer "&lt;"
      | '>' -> Buffer.add_string buffer "&gt;"
      | '"' -> Buffer.add_string buffer "&quot;"
      | '\'' -> Buffer.add_string buffer "&#39;"
      | character -> Buffer.add_char buffer character)
    value;
  Buffer.contents buffer

let replace_apostrophes value =
  let buffer = Buffer.create (String.length value) in
  String.iter
    (function
      | '\'' -> Buffer.add_string buffer "&#39;"
      | character -> Buffer.add_char buffer character)
    value;
  Buffer.contents buffer

let render_artifact = function
  | Text { label; content } ->
      Printf.sprintf
        "<details class=\"artifact\"><summary>%s</summary><pre><code>%s</code></pre></details>"
        (html_escape label) (html_escape content)
  | Image { label; mime_type; base64 } ->
      Printf.sprintf
        "<figure class=\"artifact\"><img alt=\"%s\" src=\"data:%s;base64,%s\"><figcaption>%s</figcaption></figure>"
        (html_escape label) (html_escape mime_type) (html_escape base64)
        (html_escape label)
  | Video { label; mime_type; base64; sha256; bytes; provenance } ->
      Printf.sprintf
        "<figure class=\"artifact\"><video controls preload=\"metadata\" aria-label=\"%s\"><source src=\"data:%s;base64,%s\" type=\"%s\"></video><figcaption>%s · %d bytes · SHA-256 %s · %s</figcaption></figure>"
        (html_escape label) (html_escape mime_type) (html_escape base64)
        (html_escape mime_type) (html_escape label) bytes (html_escape sha256)
        (html_escape provenance)
  | Download { label; mime_type; base64; sha256; bytes; provenance } ->
      Printf.sprintf
        "<p class=\"artifact\"><a download=\"%s\" href=\"data:%s;base64,%s\">Download %s</a><br><small>%d bytes · SHA-256 %s · %s</small></p>"
        (html_escape label) (html_escape mime_type) (html_escape base64)
        (html_escape label) bytes (html_escape sha256) (html_escape provenance)

let render document =
  let title = html_escape document.title in
  let source_path = html_escape document.source_path in
  let body =
    (match document.rendered_body with
     | Some body -> body
     (* the streaming renderer is retired; journals render through the AST like
        every other page *)
     | None -> Docs_wiki.render_markdown_typed ~resolve:(fun _ -> None) document.markdown)
    |> replace_apostrophes
  in
  let artifacts =
    match document.artifacts with
    | [] -> ""
    | artifacts ->
        "<section class=\"artifacts\"><h2>Embedded artifacts</h2>" ^
        String.concat "\n" (List.map render_artifact artifacts) ^
        "</section>"
  in
  Printf.sprintf
    {|<!doctype html>
<!-- @generated by harness/journal_markdown_html.ml. DO NOT EDIT: change the
     Markdown source and re-render. This page carries GENERATED provenance, so
     every lint finding on it is an Error with no ratchet. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>%s</title>
<style>
:root{color-scheme:light dark;--bg:#f5f3ed;--panel:#fffdf8;--ink:#20201e;--muted:#66645e;--line:#d9d5ca;--accent:#d41470;--code:#17171a}
@media(prefers-color-scheme:dark){:root{--bg:#171719;--panel:#222225;--ink:#f3f1ea;--muted:#b6b2a9;--line:#3d3b3a;--accent:#ff62a8;--code:#101012}}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 ui-sans-serif,system-ui,sans-serif}
header,main{width:min(1120px,calc(100%% - 32px));margin:auto}header{padding:42px 0 22px;border-bottom:1px solid var(--line)}
header h1{margin:0 0 8px;font-size:clamp(2rem,5vw,4rem);line-height:1.02;letter-spacing:-.04em}header p{margin:4px 0;color:var(--muted)}
main{margin-top:24px;margin-bottom:64px;padding:clamp(20px,4vw,48px);background:var(--panel);border:1px solid var(--line);border-radius:20px;box-shadow:0 18px 48px #0001}
h1,h2,h3,h4{line-height:1.2;letter-spacing:-.02em}h2{margin-top:2.6rem;padding-top:1rem;border-top:1px solid var(--line)}
a{color:var(--accent)}code{font:0.92em/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}pre{overflow:auto;padding:18px;border-radius:12px;background:var(--code);color:#f8f8f2;white-space:pre-wrap;word-break:break-word}
.table-wrap{overflow:auto}table{width:100%%;border-collapse:collapse;margin:1rem 0}th,td{padding:10px 12px;border:1px solid var(--line);text-align:left;vertical-align:top}blockquote{margin:1rem 0;padding:.5rem 1rem;border-left:4px solid var(--accent);background:color-mix(in srgb,var(--accent) 8%%,transparent)}
.provenance{display:inline-block;padding:6px 10px;border:1px solid var(--line);border-radius:999px;background:var(--panel);font:13px ui-monospace,SFMono-Regular,Consolas,monospace}.artifact{margin:18px 0;padding:14px;border:1px solid var(--line);border-radius:12px}.artifact summary{cursor:pointer;font-weight:700}.artifact img{display:block;max-width:100%%;height:auto;margin:auto;border-radius:8px}.artifact figcaption{margin-top:8px;color:var(--muted);text-align:center}@media(max-width:600px){header,main{width:min(100%% - 20px,1120px)}main{padding:18px;border-radius:14px}}
</style>
</head>
<body>
<header><h1>%s</h1><p>Loss-aware journal projection generated from the canonical Markdown artifact.</p><p class="provenance">Prompt source: %s</p></header>
<main>%s%s</main>
</body>
</html>
|}
    title title source_path body artifacts
