#use "topfind";;
#require "unix,str,yojson,cryptokit,mtime.clock.os";;
#directory "/tmp/ev-campaign-independent-direct-review-20260909/build/default/.ev_receipts.objs/byte";;
#load "/tmp/ev-campaign-independent-direct-review-20260909/build/default/ev_receipts.cma";;
let root="/home/an/NAS-setup/uos"
let workspace=root^"/.uos-workspaces/codex-ev-admission-20260909-0210"
let revision=Sys.argv.(1)
let stage=Sys.argv.(2)
let require b why=if not b then failwith why
let read p=let c=open_in_bin p in Fun.protect ~finally:(fun()->close_in_noerr c)(fun()->
  let n=in_channel_length c in require(n<=4_194_304)"read bound";really_input_string c n)
let hash=Receipt_validator.sha
let rec mkdir p=if not(Sys.file_exists p)then(mkdir(Filename.dirname p);Unix.mkdir p 0o700)
let write p b=mkdir(Filename.dirname p);Ev_campaign.write p b
let replace_owned p b=let c=open_out_bin p in Fun.protect ~finally:(fun()->close_out_noerr c)(fun()->output_string c b)
let candidate p=Receipt_validator.run ~seconds:5. ~limit:1_048_576(root^"/toolchains/nix-profile/bin/jj")
  ["--ignore-working-copy";"--no-pager";"--color";"never";"-R";workspace;
   "file";"show";"-r";"commit_id(\""^revision^"\")";"-T";"\"\"";"--";"root:"^p]
let field=Yojson.Basic.Util.member
let string n j=field n j |> Yojson.Basic.Util.to_string
let strings re bytes=let re=Str.regexp re in
  let rec loop at acc=try ignore(Str.search_forward re bytes at);let s=Str.matched_group 1 bytes and next=Str.match_end()in loop next(s::acc)with Not_found->List.rev acc in loop 0 []
let generator=candidate "tools/generate_ev_recovery_runner.ml"
let modules=strings "\"\\([a-z_0-9]+_test\\)\"" generator
let target=stage^"/apps/cepaf_gleam/test/ev_recovery_runner.gleam"
let expected=candidate "apps/cepaf_gleam/test/ev_recovery_runner.gleam"
let bindings=ref []
let ()=
  require(String.length revision=40 && not(Sys.file_exists stage) && List.length modules=16)"fresh fixed-scope fixture";
  List.iter(fun p->let bytes=candidate p in write(stage^"/"^p)bytes;
    bindings:=`Assoc["path",`String p;"sha256",`String(hash bytes)]::!bindings)
    ("tools/generate_ev_recovery_runner.ml"::List.map(fun m->"apps/cepaf_gleam/test/"^m^".gleam")modules);
  write(stage^"/expected-runner.gleam")expected
let counter=ref 0 and checks=ref [] and receipts=ref []
let run args=
  incr counter;
  let receipt=stage^"/case-"^string_of_int !counter^".json" in
  let ok=try ignore(Receipt_validator.run ~seconds:25. ~limit:4_194_304(root^"/toolchains/opam-ocaml/bin/ocamlrun")
    ([root^"/toolchains/opam-ocaml/bin/ocaml";workspace^"/tools/ev_native.ml";"--cwd";stage;
      "--seconds";"15";"--receipt";receipt;"--";"ocaml";stage^"/tools/generate_ev_recovery_runner.ml"]@args));true
    with Failure _->false in
  let j=Yojson.Basic.from_string(read receipt) in
  let code=field "exit_code" j |> Yojson.Basic.Util.to_int in
  require(ok=(code=0) && field "failure" j=`Null &&
    field "child_termination" j=`Assoc["kind",`String "EXITED";"code",`Int code])"nonordinary generator outcome";
  require(hash(string "output" j)=string "output_sha256" j)"receipt output mismatch";
  receipts:=`Assoc["path",`String receipt;"sha256",`String(hash(read receipt))]::!receipts;
  code
let check label ok=require ok label;checks:=label::!checks;print_endline("PASS "^label)
let unchanged ()=read target=expected
let ()=
  check "fresh_exact_177" (run[]=0 && unchanged());
  check "occupied_path_preserved" (run[]<>0 && unchanged());
  check "explicit_regular_replacement_exact" (run["--replace"]=0 && unchanged());
  Unix.rename target(stage^"/preserved-initial-runner.gleam");
  let outside=stage^"/outside-marked.txt" and marker="// Generated by tools/generate_ev_recovery_runner.ml; component observations only.\nPRIVATE SENTINEL\n" in
  write outside marker;Unix.symlink outside target;
  check "marked_symlink_target_preserved" (run["--replace"]<>0 && read outside=marker && (Unix.lstat target).st_kind=Unix.S_LNK);
  Unix.unlink target;Unix.symlink(stage^"/absent")target;
  check "dangling_symlink_preserved" (run["--replace"]<>0 && (Unix.lstat target).st_kind=Unix.S_LNK && not(Sys.file_exists(stage^"/absent")));
  Unix.unlink target;write target "OPERATOR SENTINEL\n";
  check "unmarked_file_preserved" (run["--replace"]<>0 && read target="OPERATOR SENTINEL\n");
  Unix.unlink target;Unix.mkdir target 0o700;
  check "directory_preserved" (run["--replace"]<>0 && (Unix.lstat target).st_kind=Unix.S_DIR);
  Unix.rmdir target;Unix.link outside target;
  check "hardlink_other_name_preserved" (run["--replace"]=0 && unchanged() && read outside=marker && (Unix.stat target).st_ino<>(Unix.stat outside).st_ino);
  let parent=Filename.dirname target in Unix.rename parent(parent^"-real");Unix.symlink(parent^"-real")parent;
  check "symlink_parent_refused" (run["--replace"]<>0 && unchanged());
  Unix.unlink parent;Unix.rename(parent^"-real")parent;
  let module_path=parent^"/rag_cache_mesh_test.gleam" in let original=read module_path in
  let names=strings "^pub fn \\([a-z][a-z_0-9]*_test\\)()" original in
  require(List.length names>=2)"case-set controls require two exports";
  let first=List.hd names and second=List.nth names 1 in
  let alter name=Str.replace_first(Str.regexp_string("pub fn "^first^"()"))("pub fn "^name^"()") original in
  replace_owned module_path(alter "unreviewed_same_count_test");
  check "same_count_unreviewed_name_refused" (run["--replace"]<>0 && unchanged());
  replace_owned module_path(alter second);
  check "same_count_duplicate_refused" (run["--replace"]<>0 && unchanged());
  replace_owned module_path(Str.replace_first(Str.regexp_string("pub fn "^first^"()"))("fn "^first^"()")original);
  check "reduced_denominator_refused" (run["--replace"]<>0 && unchanged());
  let reversed=second::first::List.tl(List.tl names) in
  replace_owned module_path(String.concat "\n"(List.map(fun n->"pub fn "^n^"() {}")reversed)^"\n");
  check "same_count_reordered_calls_refused" (run["--replace"]<>0 && unchanged());
  replace_owned module_path original;
  check "restored_source_exact" (run["--replace"]=0 && unchanged());
  let legacy=(Yojson.Basic.from_string(read "/tmp/ev-recovery-case-set-1522.json") |> field "legacy_calls" |> Yojson.Basic.Util.to_list |> List.map Yojson.Basic.Util.to_string) in
  let actual=strings "^  \\([a-z_0-9]+_test\\.[a-z_0-9]+_test\\)()" expected in
  check "all_legacy168_ordered_with_reviewed9" (List.length actual=177 && List.filter(fun n->List.mem n legacy)actual=legacy && List.length legacy=168);
  write(stage^"/verification.json")(Yojson.Basic.pretty_to_string(`Assoc[
    "schema",`String "uos.recovery-generator-controls.v1";"candidate",`String revision;"authority",`String "NONE";
    "observed_at",`Float(Unix.gettimeofday());"checks",`List(List.map(fun s->`String s)(List.rev !checks));
    "checks_passed",`Int(List.length !checks);"source_bindings",`List(List.rev !bindings);
    "generator_sha256",`String(hash generator);"runner_sha256",`String(hash expected);
    "driver_sha256",`String(hash(read "/tmp/ev_recovery_generator_controls.ml"));"invocations",`List(List.rev !receipts);
    "limits",`String "Private deterministic file controls; concurrent hostile directory replacement and crash durability remain unproved. This checks enumeration, not all EV behavior."] )^"\n");
  Printf.printf "PASS %d generator control groups\n"(List.length !checks)
