@sciviz @extensions @gallery @catalog
Feature: SciViz 167 ggplot2 Extensions Registry Verification
  As a scientific visualization specialist
  I want all 167 ggplot2 extensions registered, mapped, and verified in the gallery
  So that complete visualization domain coverage is assured under SIL-6 standards

  Background:
    Given I navigate to "http://127.0.0.1:4100/sciviz/extensions"
    And the page title should contain "Extensions"

  Scenario Outline: Verify Extension <name> Rendered in Gallery
    Then the page text should contain "<name>"
    And no unhandled JavaScript exceptions should have occurred

    Examples:
      | name |
      | ggram |
      | ggQQunif |
      | ggupset |
      | xmrr |
      | gg3D |
      | ggQC |
      | ggdist |
      | ggedit |
      | ggpage |
      | ggpca |
      | ggbreak |
      | ggimg |
      | gganatogram |
      | ggforce |
      | ggalt |
      | ggiraph |
      | ggmuller |
      | ggstance |
      | ggrepel |
      | ggraph |
      | gginnards |
      | ggpp |
      | ggpmisc |
      | geomnet |
      | ggExtra |
      | ggfortify |
      | autoplotly |
      | gganimate |
      | ggfx |
      | plotROC |
      | ggbump |
      | ggthemes |
      | ggspectra |
      | ggstatsplot |
      | ggnetwork |
      | ggtech |
      | ggradar |
      | ggx |
      | ggTimeSeries |
      | ggtree |
      | ggseas |
      | ggsci |
      | ggmosaic |
      | survminer |
      | ggeasy |
      | ggside |
      | ggcorrplot |
      | ggpubr |
      | ggthemr |
      | GGally |
      | ggseqlogo |
      | ggChernoff |
      | ggridges |
      | lemon |
      | cowplot |
      | qqplotr |
      | ggalluvial |
      | patchwork |
      | ggquiver |
      | ggsignif |
      | ggdag |
      | ggformula |
      | ggbeeswarm |
      | ggperiodic |
      | ggpol |
      | ggpirate |
      | esquisse |
      | ggerror |
      | ggdark |
      | sugrrants |
      | tvthemes |
      | ggfittext |
      | ggparty |
      | gggenes |
      | gggenomes |
      | treemapify |
      | lindia |
      | gghalves |
      | ggrastr |
      | ggpointdensity |
      | ggsom |
      | ggnewscale |
      | ggh4x |
      | ggarrow |
      | legendry |
      | ggcharts |
      | humapr |
      | ggshadow |
      | ggseg |
      | mdthemes |
      | ggwordcloud |
      | ggasym |
      | gglorenz |
      | hrbrthemes |
      | ggpattern |
      | ggtext |
      | calendR |
      | ggip |
      | gglm |
      | econocharts |
      | ComplexUpset |
      | ggchromatic |
      | ggheatmap |
      | see |
      | directlabels |
      | ggHoriPlot |
      | ggtrace |
      | ggESDA |
      | geomtextpath |
      | ggdensity |
      | ggtranscript |
      | piecepackr |
      | oblicubes |
      | ggDoubleHeat |
      | nflplotR |
      | ggbraid |
      | ggblanket |
      | ggpie |
      | ggstar |
      | ggarchery |
      | tidyterra |
      | ggseqplot |
      | ggsurvfit |
      | ggsector |
      | ggterror |
      | ggragged |
      | ggmapinset |
      | ggmagnify |
      | ggblend |
      | ggflowchart |
      | ggrain |
      | ggoutlierscatterplot |
      | ggautothemes |
      | AMR |
      | ichimoku |
      | eheat |
      | ggstats |
      | ggfoundry |
      | ggalign |
      | ggreveal |
      | geofacet |
      | tidyplots |
      | rphylopic |
      | deeptime |
      | ggpcp |
      | ggvolcano |
      | ggfootball |
      | ggfields |
      | ggsankeyfier |
      | ggpath |
      | gglinedensity |
      | ggsurveillance |
      | gguapo |
      | ggDNAvis |
      | ggdibbler |
      | ggprop.test |
      | ggsky |
      | ggpop |
      | ggpointless |
      | ggincerta |
      | ggRandomForests |
      | ggcube |
      | ggtaichi |
      | ggchord2 |
      | ggtintshade |
      | glydraw |
      | ggmultiglyph |
