@a2ui @components @catalog @declarative @schema
Feature: A2UI Declarative Component Catalog Specification
  As an autonomous agent and UI runtime engineer
  I want all 239 A2UI component specifications registered and type-verified
  So that agentic UI generation adheres to declarative schema contracts without arbitrary JS

  Background:
    Given I navigate to "http://127.0.0.1:4100/components"
    And the page title should contain "Component Demo"

  Scenario Outline: Verify Component Type <comp> Schema Invariant
    Given I evaluate script "typeof window !== 'undefined'"
    Then the script result should equal "true"
    And the page text should contain "registered in A2UI catalog"
    And no unhandled JavaScript exceptions should have occurred

    Examples:
      | comp |
      | alert |
      | modal |
      | emergency_stop |
      | sparkline |
      | badge |
      | button |
      | data_table |
      | progress |
      | container_card |
      | ooda_ring |
      | reasoning |
      | topology |
      | action_button |
      | card_grid |
      | section |
      | split_pane |
      | tab_strip |
      | collapsible_panel |
      | fractal_breadcrumb |
      | grid_layout |
      | scroll_viewport |
      | sidebar_nav |
      | modal_overlay |
      | sticky_footer |
      | responsive_columns |
      | layer_accordion |
      | dashboard_tile |
      | header_bar |
      | empty_state |
      | kv_table |
      | log_stream |
      | json_tree |
      | triple_row |
      | diff_viewer |
      | metric_counter |
      | histogram_bar |
      | version_vector_row |
      | hash_display |
      | container_log_tail |
      | sparql_result_grid |
      | event_payload_card |
      | latency_gauge |
      | resource_usage_row |
      | task_detail_pane |
      | proof_token_card |
      | health_indicator |
      | connection_status |
      | cockpit_mode_badge |
      | quorum_indicator |
      | boot_phase_tracker |
      | threat_level_bar |
      | container_status_dot |
      | psi_invariant_row |
      | sil_compliance_badge |
      | circuit_breaker_status |
      | mara_status |
      | agent_heartbeat |
      | sync_status_icon |
      | entropy_score |
      | test_suite_status |
      | cognitive_load_meter |
      | dag_integrity_badge |
      | mesh_mode_indicator |
      | filter_bar |
      | search_input |
      | confirm_dialog |
      | toggle_switch |
      | dropdown_select |
      | command_palette |
      | threshold_slider |
      | bulk_action_bar |
      | topic_subscribe_btn |
      | refresh_button |
      | pagination_controls |
      | sort_header |
      | copy_button |
      | two_key_release |
      | chaos_inject_btn |
      | time_range_picker |
      | container_grid_16 |
      | ooda_waterfall |
      | trace_flamegraph |
      | span_gantt_chart |
      | peer_ring |
      | antibody_list |
      | attack_timeline |
      | knowledge_graph_mini |
      | pid_control_plot |
      | version_clock_ring |
      | event_frequency_heatmap |
      | task_kanban_board |
      | dependency_dag |
      | reconciliation_diff |
      | router_topology_mini |
      | metric_time_series |
      | hash_chain_strip |
      | layer_sunburst |
      | evolution_radar |
      | coverage_gauge_ring |
      | agent_run_card |
      | tool_call_panel |
      | reasoning_stream |
      | sse_connection_indicator |
      | agent_hierarchy_tree |
      | hitl_pending_queue |
      | activity_feed |
      | state_inspector |
      | message_thread |
      | agent_capability_badges |
      | guardian_approval_panel |
      | psi_invariant_dashboard |
      | emergency_banner |
      | constitutional_hash_chain |
      | audit_trail_log |
      | sil6_compliance_matrix |
      | cpu_governor_gauge |
      | memory_pressure_bar |
      | disk_io_sparkline |
      | network_throughput |
      | beam_scheduler_load |
      | nif_latency_histogram |
      | sqlite_wal_status |
      | gc_pressure_indicator |
      | process_count_gauge |
      | message_queue_depth |
      | ets_table_monitor |
      | dirty_scheduler_load |
      | zenoh_topic_rate |
      | otel_export_status |
      | heartbeat_monitor |
      | key_expression_viewer |
      | pub_sub_flow |
      | zenoh_session_card |
      | router_health_strip |
      | topic_tree |
      | message_inspector |
      | qos_priority_badge |
      | congestion_indicator |
      | liveliness_token |
      | scout_result |
      | container_restart_btn |
      | image_staleness_badge |
      | build_history_chart |
      | port_mapping_row |
      | volume_mount_list |
      | health_check_log |
      | resource_limit_bar |
      | network_namespace_badge |
      | tier_boot_progress |
      | apoptosis_countdown |
      | task_priority_pill |
      | task_status_flow |
      | task_burndown_chart |
      | task_dependency_edge |
      | critical_path_highlight |
      | task_age_indicator |
      | owner_avatar |
      | sprint_velocity |
      | raw_lines_preview |
      | parent_child_tree |
      | triple_store_stats |
      | sparql_query_editor |
      | entity_detail_card |
      | inference_chain |
      | ontology_class_tree |
      | semantic_search_result |
      | namespace_prefix_table |
      | graph_statistics_card |
      | grl_rule_card |
      | fact_table |
      | rule_fire_log |
      | decision_tree_node |
      | domain_selector |
      | hysteresis_band |
      | rete_network_viz |
      | escalation_path |
      | recovery_playbook_card |
      | cascade_containment |
      | partition_fence_status |
      | graceful_degradation_bar |
      | checkpoint_status |
      | rollback_button |
      | dying_gasp_log |
      | self_heal_timeline |
      | trace_id_link |
      | span_detail_drawer |
      | service_map_node |
      | log_level_filter |
      | metric_label_filter |
      | alert_rule_card |
      | slo_budget_gauge |
      | exemplar_link |
      | pid_tuning_panel |
      | metabolic_rate_gauge |
      | energy_flow_sankey |
      | neuro_signal_trace |
      | immune_antibody_forge |
      | homeostasis_error_integral |
      | bio_subsystem_radar |
      | adaptation_rate_meter |
      | consensus_vote_panel |
      | crdt_merge_log |
      | attestation_chain |
      | federation_member_card |
      | causal_order_timeline |
      | gateway_status |
      | sovereignty_badge |
      | mesh_partition_map |
      | color_contrast_badge |
      | keyboard_shortcut_hint |
      | aria_landmark_indicator |
      | focus_trap_boundary |
      | screen_reader_status |
      | reduced_motion_toggle |
      | high_contrast_mode |
      | text_scaling_control |
      | proof_token_verifier |
      | key_rotation_timeline |
      | certificate_status |
      | access_control_row |
      | encryption_indicator |
      | hmac_verification_badge |
      | rate_limit_gauge |
      | allium_entity_card |
      | allium_rule_display |
      | allium_invariant_badge |
      | spec_drift_indicator |
      | contract_boundary_viz |
      | toast_notification |
      | notification_badge_counter |
      | system_announcement |
      | operator_presence |
      | chat_message_bubble |
      | data_grid |
      | task_explorer |
      | knowledge_explorer |
      | analysis_matrix |
      | decision_support |
      | pipeline_monitor |
