use crate::spec::{LabSpec, VmSpec};
use anyhow::{Context, Result};
use serde_json::json;
use std::fs;
use std::path::Path;

pub fn render_all(spec: &LabSpec, out: &Path) -> Result<()> {
    spec.validate_safety_invariants()
        .map_err(|e| anyhow::anyhow!(e))?;
    fs::create_dir_all(out).with_context(|| format!("create {}", out.display()))?;
    fs::create_dir_all(out.join("libvirt"))?;
    fs::create_dir_all(out.join("cloud-init"))?;
    fs::create_dir_all(out.join("kubeadm"))?;
    fs::create_dir_all(out.join("host"))?;
    fs::create_dir_all(out.join("kubernetes"))?;

    write(out.join("README.generated.md"), &render_readme(spec))?;
    write(out.join("libvirt/network.xml"), &render_network(spec))?;
    write(out.join("host/haproxy.cfg"), &render_haproxy(spec))?;
    write(
        out.join("kubeadm/init-config.yaml"),
        &render_kubeadm_init(spec),
    )?;
    write(
        out.join("kubernetes/rook-values.json"),
        &render_rook_values(spec)?,
    )?;
    write(
        out.join("kubernetes/rook-resources.json"),
        &render_rook_resources(spec)?,
    )?;

    for vm in &spec.vms {
        write(
            out.join(format!("libvirt/{}.xml", vm.name)),
            &render_vm_domain(spec, vm),
        )?;
        write(
            out.join(format!("cloud-init/{}-user-data.yaml", vm.name)),
            &render_user_data(spec, vm),
        )?;
    }

    println!("Rendered Rust-owned configuration to {}", out.display());
    Ok(())
}

fn write(path: impl AsRef<Path>, content: &str) -> Result<()> {
    let path = path.as_ref();
    fs::write(path, content).with_context(|| format!("write {}", path.display()))
}

fn render_readme(spec: &LabSpec) -> String {
    format!(
        "# Generated NAS Kubernetes Lab Configuration\n\n\
         This directory is generated by `cargo run --manifest-path k8s-lab/Cargo.toml -- render`.\n\n\
         - Kubernetes: {}\n\
         - Rook: {}\n\
         - Control plane endpoint: {}\n\
         - Safety gate: audit and approve all candidate OSD disks before wiping or passthrough.\n",
        spec.kubernetes.version, spec.ceph.rook_version, spec.kubernetes.control_plane_endpoint
    )
}

fn render_network(spec: &LabSpec) -> String {
    format!(
        "<network>\n  <name>{}</name>\n  <bridge name='virbr-k8s'/>\n  <forward mode='nat'/>\n  <ip address='{}' netmask='255.255.255.0'>\n  </ip>\n</network>\n",
        spec.host.lab_network_name, spec.host.host_lab_ip
    )
}

fn render_haproxy(spec: &LabSpec) -> String {
    let backends = spec
        .vms
        .iter()
        .map(|vm| format!("    server {} {}:6443 check", vm.name, vm.ip))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "global\n    daemon\n    maxconn 2048\n\n\
         defaults\n    mode tcp\n    timeout connect 10s\n    timeout client 1m\n    timeout server 1m\n\n\
         frontend kube_api\n    bind {}:{}\n    default_backend kube_api_servers\n\n\
         backend kube_api_servers\n    balance roundrobin\n{}\n",
        spec.host.api_endpoint, spec.host.api_port, backends
    )
}

fn render_kubeadm_init(spec: &LabSpec) -> String {
    format!(
        "apiVersion: kubeadm.k8s.io/v1beta4\nkind: ClusterConfiguration\n\
         kubernetesVersion: {}\n\
         controlPlaneEndpoint: {}\n\
         networking:\n  podSubnet: {}\n  serviceSubnet: {}\n\
         apiServer:\n  certSANs:\n  - {}\n  - {}\n  - {}\n\
         ---\n\
         apiVersion: kubelet.config.k8s.io/v1beta1\nkind: KubeletConfiguration\n\
         cgroupDriver: systemd\n",
        spec.kubernetes.version,
        spec.kubernetes.control_plane_endpoint,
        spec.kubernetes.pod_cidr,
        spec.kubernetes.service_cidr,
        spec.host.api_endpoint,
        spec.host.host_lab_ip,
        spec.host.name
    )
}

fn render_vm_domain(_spec: &LabSpec, vm: &VmSpec) -> String {
    let disks = vm
        .osd_devices
        .iter()
        .enumerate()
        .map(|(i, dev)| {
            let target = (b'b' + i as u8) as char;
            format!(
                "    <disk type='block' device='disk'>\n      <driver name='qemu' type='raw' cache='none' io='native'/>\n      <source dev='{}'/>\n      <target dev='vd{}' bus='virtio'/>\n    </disk>",
                dev.host_device, target
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "<domain type='kvm'>\n  <name>{}</name>\n  <memory unit='MiB'>{}</memory>\n  <vcpu>{}</vcpu>\n  <os><type arch='x86_64'>hvm</type></os>\n  <devices>\n    <disk type='file' device='disk'>\n      <driver name='qemu' type='qcow2'/>\n      <source file='/var/lib/libvirt/images/{}.qcow2'/>\n      <target dev='vda' bus='virtio'/>\n    </disk>\n{}\n    <interface type='network'><source network='k8s-lab'/><model type='virtio'/></interface>\n    <console type='pty'/>\n  </devices>\n</domain>\n",
        vm.name, vm.memory_mib, vm.vcpus, vm.name, disks
    )
}

fn render_user_data(spec: &LabSpec, vm: &VmSpec) -> String {
    format!(
        "#cloud-config\nhostname: {}\nmanage_etc_hosts: true\npackage_update: true\npackages:\n  - containerd\n  - kubelet\n  - kubeadm\n  - kubectl\nwrite_files:\n  - path: /etc/sysctl.d/99-kubernetes.conf\n    content: |\n      net.bridge.bridge-nf-call-iptables = 1\n      net.ipv4.ip_forward = 1\nruncmd:\n  - [ systemctl, enable, --now, containerd ]\n  - [ swapoff, -a ]\n# Static IP target for {} on lab network {}. Apply through netplan or libvirt DHCP reservations.\n",
        vm.name, vm.ip, spec.host.lab_cidr
    )
}

fn render_rook_values(spec: &LabSpec) -> Result<String> {
    let nodes = spec
        .vms
        .iter()
        .map(|vm| {
            json!({
                "name": vm.name,
                "devices": vm.osd_devices.iter().enumerate().map(|(i, dev)| {
                    json!({
                        "name": format!("vd{}", (b'b' + i as u8) as char),
                        "config": { "metadataDevice": "", "deviceClass": dev.class }
                    })
                }).collect::<Vec<_>>()
            })
        })
        .collect::<Vec<_>>();

    let values = json!({
        "rookVersion": spec.ceph.rook_version,
        "namespace": spec.ceph.namespace,
        "cluster": {
            "name": spec.ceph.cluster_name,
            "mon": { "count": 3, "allowMultiplePerNode": false },
            "storage": { "useAllNodes": false, "useAllDevices": false, "nodes": nodes }
        }
    });
    Ok(serde_json::to_string_pretty(&values)?)
}

fn render_rook_resources(spec: &LabSpec) -> Result<String> {
    let resources = json!([
        rook_cluster(spec),
        rook_block_pool("hdd-pool", "hdd", 3, 2),
        rook_block_pool("nvme-scratch-pool", "nvme", 1, 1),
        rook_filesystem(spec),
        rook_object_store(spec),
    ]);
    Ok(serde_json::to_string_pretty(&resources)?)
}

fn rook_cluster(spec: &LabSpec) -> serde_json::Value {
    let nodes = spec
        .vms
        .iter()
        .map(|vm| {
            json!({
                "name": vm.name,
                "devices": vm.osd_devices.iter().enumerate().map(|(i, dev)| {
                    json!({
                        "name": format!("vd{}", (b'b' + i as u8) as char),
                        "config": { "deviceClass": dev.class }
                    })
                }).collect::<Vec<_>>()
            })
        })
        .collect::<Vec<_>>();

    json!({
        "apiVersion": "ceph.rook.io/v1",
        "kind": "CephCluster",
        "metadata": { "name": spec.ceph.cluster_name, "namespace": spec.ceph.namespace },
        "spec": {
            "cephVersion": { "image": "quay.io/ceph/ceph:v19" },
            "dataDirHostPath": "/var/lib/rook",
            "dashboard": { "enabled": true },
            "mon": { "count": 3, "allowMultiplePerNode": false },
            "storage": { "useAllNodes": false, "useAllDevices": false, "nodes": nodes }
        }
    })
}

fn rook_block_pool(name: &str, device_class: &str, size: u8, min_size: u8) -> serde_json::Value {
    json!({
        "apiVersion": "ceph.rook.io/v1",
        "kind": "CephBlockPool",
        "metadata": { "name": name, "namespace": "rook-ceph" },
        "spec": {
            "failureDomain": "host",
            "deviceClass": device_class,
            "replicated": { "size": size, "requireSafeReplicaSize": size > 1 },
            "parameters": { "min_size": min_size.to_string() }
        }
    })
}

fn rook_filesystem(spec: &LabSpec) -> serde_json::Value {
    json!({
        "apiVersion": "ceph.rook.io/v1",
        "kind": "CephFilesystem",
        "metadata": { "name": spec.ceph.filesystem_name, "namespace": spec.ceph.namespace },
        "spec": {
            "metadataPool": { "replicated": { "size": 3 } },
            "dataPools": [{ "name": "data0", "deviceClass": "hdd", "replicated": { "size": 3 } }],
            "metadataServer": { "activeCount": 1, "activeStandby": true }
        }
    })
}

fn rook_object_store(spec: &LabSpec) -> serde_json::Value {
    json!({
        "apiVersion": "ceph.rook.io/v1",
        "kind": "CephObjectStore",
        "metadata": { "name": spec.ceph.object_store_name, "namespace": spec.ceph.namespace },
        "spec": {
            "metadataPool": { "deviceClass": "hdd", "replicated": { "size": 3 } },
            "dataPool": { "deviceClass": "hdd", "replicated": { "size": 3 } },
            "gateway": { "port": 80, "instances": 1 }
        }
    })
}
