//// [C3I-SIL6-MSTS] MODULE CONTRACT
//// <c3i-module>
////   <identity><module>cepaf_gleam/sciviz/extension_catalog</module></identity>
////   <fractal-topology><layer>L2_COMPONENT..L8_VERIFICATION</layer></fractal-topology>
////   <compliance><stamp-controls>SC-SCIVIZ-001, SC-CHECKLIST-001, SC-INTENT-ATLAS-001</stamp-controls></compliance>
//// </c3i-module>
////
//// Comprehensive Catalog of all 167 Registered ggplot2 Extensions
//// Derived directly from https://exts.ggplot2.tidyverse.org/gallery/

import gleam/list

pub type ExtensionCategory {
  UncertaintyDistribution
  NetworkGraphTopology
  FlowAlluvialSankey
  HierarchicalPartition
  SpatialVectorField
  QualityControlTimeSeries
  BioinformaticsGenomics
  TypographyTextRepel
  MultiScaleCoordinate
  CompositeMultiPanel
  ThreeDimensionalProjection
  StatisticalDiagnosisInference
  PatternFilterShader
  DimensionalityReduction
  ThemingPaletteAesthetic
  IntrospectionLayerEditing
}

pub type ExtensionMetadata {
  ExtensionMetadata(
    name: String,
    url: String,
    author: String,
    description: String,
    tags: List(String),
    category: ExtensionCategory,
  )
}

pub fn category_to_string(c: ExtensionCategory) -> String {
  case c {
    UncertaintyDistribution -> "Uncertainty & Distribution"
    NetworkGraphTopology -> "Network & Graph Topology"
    FlowAlluvialSankey -> "Flow, Alluvial & Sankey"
    HierarchicalPartition -> "Hierarchical Partition"
    SpatialVectorField -> "Spatial & Vector Field"
    QualityControlTimeSeries -> "Quality Control & Time-Series"
    BioinformaticsGenomics -> "Bioinformatics & Genomics"
    TypographyTextRepel -> "Typography & Text Repel"
    MultiScaleCoordinate -> "Multi-Scale & Coordinates"
    CompositeMultiPanel -> "Composite & Multi-Panel"
    ThreeDimensionalProjection -> "3D & Perspective Projection"
    StatisticalDiagnosisInference -> "Statistical Diagnosis & Inference"
    PatternFilterShader -> "Pattern, Filter & Shaders"
    DimensionalityReduction -> "Dimensionality Reduction"
    ThemingPaletteAesthetic -> "Theming, Palettes & Aesthetics"
    IntrospectionLayerEditing -> "Introspection & Layer Editing"
  }
}

pub fn all_167_extensions() -> List(ExtensionMetadata) {
  [
    ExtensionMetadata(
      name: "ggram",
      url: "https://github.com/EvaMaeRey/ggram",
      author: "EvaMaeRey",
      description: "Create a side-by-side code-plot display by clearing your history, executing your plot code, and then executing ggram(). ",
      tags: ["ggplot2 syntax", "graphical poems"],
      category: CompositeMultiPanel,
    ),
    ExtensionMetadata(
      name: "ggQQunif",
      url: "https://github.com/rcorty/ggQQunif",
      author: "rcorty",
      description: "Make QQ plots for big data expected to be uniformly distributed, e.g. p-values.",
      tags: ["visualization", "quantiles", "p-values", "statistics", "big data"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggupset",
      url: "https://github.com/const-ae/ggupset",
      author: "const-ae",
      description: "Combination Matrix Axis for ‘ggplot2’ to Create ‘UpSet’ Plots",
      tags: ["visualization", "upset", "combination matrix"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "xmrr",
      url: "https://github.com/Zanidean/xmrr",
      author: "Alex Zanidean",
      description: "Generate XMR Control Chart Data from Time-Series Data.",
      tags: ["XmR", "Visualization", "Control Charts", "QC", "XBar"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "gg3D",
      url: "https://github.com/AckerDWM/gg3D",
      author: "Daniel Acker",
      description: "3D perspective plots for ggplot2",
      tags: ["3D", "Visualization"],
      category: ThreeDimensionalProjection,
    ),
    ExtensionMetadata(
      name: "ggQC",
      url: "https://github.com/kenithgrey/ggQC",
      author: "Kenith Grey",
      description: "Use ggQC to plot single, faceted and multi-layered quality control charts .",
      tags: ["QC", "XmR", "XbarR", "SixSigma", "Visualization"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggdist",
      url: "https://mjskay.github.io/ggdist",
      author: "mjskay",
      description: "‘ggdist’ provides stats and geoms for visualizing distributions and uncertainty.",
      tags: ["visualization", "uncertainty", "confidence", "probability"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggedit",
      url: "https://github.com/metrumresearchgroup/ggedit",
      author: "yonicd",
      description: "ggedit is aimed to interactively edit ggplot layers, scales and themes aesthetics",
      tags: ["visualization", "interactive", "shiny", "general", "themes"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggpage",
      url: "https://emilhvitfeldt.github.io/ggpage/",
      author: "emilhvitfeldt",
      description: "Creates Page Layout Visualizations.",
      tags: ["visualization", "text"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggpca",
      url: "https://cran.r-project.org/web/packages/ggpca/index.html",
      author: "Yaoxiang Li",
      description: "Provides tools for creating publication-ready PCA, t-SNE, and UMAP plots.",
      tags: ["visualization", "dimensionality_reduction", "PCA", "t-SNE", "UMAP"],
      category: DimensionalityReduction,
    ),
    ExtensionMetadata(
      name: "ggbreak",
      url: "https://github.com/YuLab-SMU/ggbreak",
      author: "YuLab-SMU",
      description: "Set Axis Break for ‘ggplot2’",
      tags: ["visualization", "geoms"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggimg",
      url: "https://github.com/statsmaths/ggimg",
      author: "statsmaths",
      description: "Graphics Layers for Plotting Image Data with ggplot2.",
      tags: ["visualization", "geoms"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "gganatogram",
      url: "https://github.com/jespermaag/gganatogram",
      author: "jespermaag",
      description: "gganatogram makes it possible to visualise tissues for different organisms or cell compartments.",
      tags: ["anatograms", "tissue", "visualization", "anatomy", "expression", "pharmacology"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggforce",
      url: "https://github.com/thomasp85/ggforce",
      author: "thomasp85",
      description: "ggforce is aimed at providing missing functionality to ggplot2 through the extension system introduced with ggplot2 v2.0",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggalt",
      url: "https://github.com/hrbrmstr/ggalt",
      author: "hrbrmstr",
      description: "A compendium of ‘geoms’, ‘coords’ and ‘stats’ for ‘ggplot2’.",
      tags: ["visualization", "general"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggiraph",
      url: "https://github.com/davidgohel/ggiraph",
      author: "davidgohel",
      description: "htmlwidget to make ‘ggplot’ graphics interactive.",
      tags: ["visualization", "general"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggmuller",
      url: "https://cran.r-project.org/web/packages/ggmuller/index.html",
      author: "robjohnnoble",
      description: "Creates Muller plots for visualizing evolutionary dynamics.",
      tags: ["visualization", "evolution", "dynamics"],
      category: FlowAlluvialSankey,
    ),
    ExtensionMetadata(
      name: "ggstance",
      url: "https://github.com/lionel-/ggstance",
      author: "lionel-",
      description: "ggstance implements horizontal versions of common ggplot2 geoms.",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggrepel",
      url: "https://github.com/slowkow/ggrepel",
      author: "slowkow",
      description: "Repel overlapping text labels away from each other.",
      tags: ["visualization", "general"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggraph",
      url: "https://github.com/thomasp85/ggraph",
      author: "thomasp85",
      description: "ggraph is tailored at plotting graph-like data structures (graphs, networks, trees, hierarchies…).",
      tags: ["visualization", "general"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "gginnards",
      url: "https://docs.r4photobiology.info/gginnards",
      author: "aphalo",
      description: "Find, delete, insert and move plot layers. Delete unused variables from the data stored within a ggplot object. Dump dat",
      tags: ["visualization", "general", "layer manipulation", "debug"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggpp",
      url: "https://docs.r4photobiology.info/ggpp",
      author: "aphalo",
      description: "Plot annotations, data labels, plot insets, filter labels by local density (geoms, statistics, positions).",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggpmisc",
      url: "https://docs.r4photobiology.info/ggpmisc",
      author: "aphalo",
      description: "Model equation, line, residuals (lm, quantile, MA, rlm, etc.), P, F, AIC, BIC, n, correlation, ANOVA and summary tables,",
      tags: ["visualization", "statistics", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "geomnet",
      url: "https://github.com/sctyner/geomnet",
      author: "sctyner",
      description: "geomnet implements network visualizations in ggplot2 via geom_net.",
      tags: ["visualization", "general"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggExtra",
      url: "https://github.com/daattali/ggExtra",
      author: "daattali",
      description: "ggExtra lets you add marginal density plots or histograms to ggplot2 scatterplots.",
      tags: ["histogram", "marginal", "density"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggfortify",
      url: "https://github.com/sinhrks/ggfortify",
      author: "terrytangyuan",
      description: "The unified interface to ggplot2 many popular statistical pakackage results.",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "autoplotly",
      url: "https://github.com/terrytangyuan/autoplotly",
      author: "terrytangyuan",
      description: "Automatic generation of interactive visualizations for popular statistical results.",
      tags: ["visualization", "general"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "gganimate",
      url: "https://gganimate.com",
      author: "thomasp85",
      description: "A Grammar of Animated Graphics.",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggfx",
      url: "https://ggfx.data-imaginist.com/",
      author: "thomasp85",
      description: "Pixel Filters for ‘ggplot2’ and ‘grid’",
      tags: ["visualization", "general"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "plotROC",
      url: "https://github.com/sachsmc/plotROC",
      author: "sachsmc",
      description: "plotROC provides functions to generate an interactive ROC curve plot for web use, and print versions.",
      tags: ["visualization", "general"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggbump",
      url: "https://github.com/davidsjoberg/ggbump",
      author: "davidsjoberg",
      description: "Bump Chart and Sigmoid Curves.",
      tags: ["visualization", "general", "geoms"],
      category: FlowAlluvialSankey,
    ),
    ExtensionMetadata(
      name: "ggthemes",
      url: "https://github.com/jrnold/ggthemes",
      author: "jrnold",
      description: "Some extra geoms, scales, and themes for ggplot.",
      tags: ["visualization", "general", "themes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggspectra",
      url: "https://docs.r4photobiology.info/ggspectra",
      author: "aphalo",
      description: "Plot light-related spectra, peaks, valleys, half maximum, labels with summaries and colours from spectral data (autoplot",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggstatsplot",
      url: "https://github.com/IndrajeetPatil/ggstatsplot",
      author: "IndrajeetPatil",
      description: "‘ggstatsplot’ provides a collection of functions to enhance ‘ggplot2’ plots with results from statistical tests.",
      tags: ["visualization", "statistics"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggnetwork",
      url: "https://github.com/briatte/ggnetwork",
      author: "briatte",
      description: "The ggnetwork package provides a way to build network plots with ggplot2.",
      tags: ["visualization", "general"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggtech",
      url: "https://github.com/ricardo-bion/ggtech",
      author: "ricardo-bion",
      description: "ggplot2 tech themes, scales, and geoms.",
      tags: ["visualization", "general", "themes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggradar",
      url: "https://github.com/ricardo-bion/ggradar",
      author: "ricardo-bion",
      description: "ggradar allows you to build radar charts with ggplot2.",
      tags: ["visualization", "general"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggx",
      url: "https://github.com/brandmaier/ggx",
      author: "brandmaier",
      description: "A Natural Language Interface to ‘ggplot2’.",
      tags: ["visualization", "nlp"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggTimeSeries",
      url: "https://github.com/Ather-Energy/ggTimeSeries",
      author: "Ather-Energy",
      description: "This R package offers novel time series visualisations.",
      tags: ["visualization", "general"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggtree",
      url: "https://guangchuangyu.github.io/ggtree",
      author: "GuangchuangYu",
      description: "gtree is designed for visualizing phylogenetic tree and different types of associated annotation data.",
      tags: ["visualization", "general"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggseas",
      url: "https://github.com/ellisp/ggseas",
      author: "ellisp",
      description: "Seasonal adjustment on the fly extension for ggplot2.",
      tags: ["visualization", "general"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggsci",
      url: "https://nanx.me/ggsci/",
      author: "road2stat",
      description: "A collection of ‘ggplot2’ color palettes inspired by scientific journals and science fiction TV shows.",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggmosaic",
      url: "https://github.com/haleyjeppson/ggmosaic",
      author: "haleyjeppson",
      description: "ggmosaic implements mosaic plots in ‘ggplot2’ via geom_mosaic.",
      tags: ["visualization", "general"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "survminer",
      url: "https://www.sthda.com/english/rpkgs/survminer/",
      author: "kassambara",
      description: "Drawing Survival Curves using ‘ggplot2’",
      tags: ["visualization", "survival"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggeasy",
      url: "https://jonocarroll.github.io/ggeasy/",
      author: "jonocarroll",
      description: "Easy Access to ‘ggplot2’ Commands",
      tags: ["visualization", "teaching"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggside",
      url: "https://github.com/jtlandis/ggside",
      author: "jtlandis",
      description: "Side Grammar Graphics",
      tags: ["visualization", "correlation"],
      category: CompositeMultiPanel,
    ),
    ExtensionMetadata(
      name: "ggcorrplot",
      url: "https://rpkgs.datanovia.com/ggcorrplot/",
      author: "kassambara",
      description: "Visualization of a correlation matrix using ‘ggplot2’",
      tags: ["visualization", "correlation"],
      category: DimensionalityReduction,
    ),
    ExtensionMetadata(
      name: "ggpubr",
      url: "https://rpkgs.datanovia.com/ggpubr/",
      author: "kassambara",
      description: "‘ggplot2’ Based Publication Ready Plots",
      tags: ["visualization", "statistics"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggthemr",
      url: "https://github.com/cttobin/ggthemr",
      author: "cttobin",
      description: "Themes for ggplot",
      tags: ["visualization", "general", "themes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "GGally",
      url: "https://ggobi.github.io/ggally/",
      author: "ggobi",
      description: "ggally extends ‘ggplot2’ by adding several functions to reduce the complexity of combining geometric objects with transf",
      tags: ["visualization", "general"],
      category: DimensionalityReduction,
    ),
    ExtensionMetadata(
      name: "ggseqlogo",
      url: "https://github.com/omarwagih/ggseqlogo",
      author: "omarwagih",
      description: "Publication-ready sequence logos using ggplot2.",
      tags: ["visualization", "general"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggChernoff",
      url: "https://github.com/Selbosh/ggChernoff",
      author: "Selbosh",
      description: "Visualise multivariate data using human faces",
      tags: ["visualization"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggridges",
      url: "https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html",
      author: "clauswilke",
      description: "Ridgeline plot geoms for ‘ggplot2’",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "lemon",
      url: "https://github.com/stefanedwards/lemon",
      author: "stenfanedwards",
      description: "Repositioning legends and adding brackets to axes to ‘ggplot2’.",
      tags: ["visualization", "brackets", "axis"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "cowplot",
      url: "https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html",
      author: "clauswilke",
      description: "Streamlined plot theme and plot annotations for ‘ggplot2’",
      tags: ["visualization", "general", "themes"],
      category: CompositeMultiPanel,
    ),
    ExtensionMetadata(
      name: "qqplotr",
      url: "https://github.com/aloy/qqplotr",
      author: "almeidaxan",
      description: "Quantile-quantile and probability-probability plot extensions for ‘ggplot2’",
      tags: ["quantile-quantile", "probability-probability"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggalluvial",
      url: "https://github.com/corybrunson/ggalluvial",
      author: "corybrunson",
      description: "A ‘ggplot2’ extension for alluvial diagrams.",
      tags: ["visualization", "categorical", "time series"],
      category: FlowAlluvialSankey,
    ),
    ExtensionMetadata(
      name: "patchwork",
      url: "https://github.com/thomasp85/patchwork#patchwork",
      author: "thomasp85",
      description: "Easy composition of ggplot plots using arithmetic operators",
      tags: ["visualization", "composition"],
      category: CompositeMultiPanel,
    ),
    ExtensionMetadata(
      name: "ggquiver",
      url: "https://github.com/mitchelloharawild/ggquiver",
      author: "mitchelloharawild",
      description: "Quiver/velocity plots for ‘ggplot2’.",
      tags: ["visualization", "quiver", "velocity", "vector"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggsignif",
      url: "https://github.com/const-ae/ggsignif",
      author: "const-ae and IndrajeetPatil",
      description: "Significance Brackets for ‘ggplot2’.",
      tags: ["visualization", "multiple comparisons"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggdag",
      url: "https://ggdag.malco.io/",
      author: "malcolmbarrett",
      description: "Causal directed acyclic graphs (DAGs) in ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "dags", "inference"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggformula",
      url: "https://projectmosaic.github.io/ggformula/",
      author: "rpruim",
      description: "ggplot2 via formulas and pipes  ``` ggplot2 ```",
      tags: ["visualization", "general", "interface"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggbeeswarm",
      url: "https://github.com/eclarke/ggbeeswarm",
      author: "Erik Clarke and Scott Sherrill-Mix",
      description: "Create beeswarm plots, which avoids overlapping datapoints.",
      tags: ["visualization", "beeswarm", "categorical"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggperiodic",
      url: "https://github.com/eliocamp/ggperiodic",
      author: "eliocamp",
      description: "Automagically augment periodic data in ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "periodic"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggpol",
      url: "https://github.com/erocoar/ggpol",
      author: "erocoar",
      description: "ggpol adds parliament diagrams and several other geoms to ggplot2.",
      tags: ["visualization", "general"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "ggpirate",
      url: "https://github.com/mikabr/ggpirate",
      author: "mikabr",
      description: "Pirate plots for ggplot2  ``` ggplot2 ```",
      tags: ["visualization"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "esquisse",
      url: "https://github.com/dreamRs/esquisse",
      author: "dreamrs",
      description: "Explore and Visualize Your Data Interactively with ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "interface"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggerror",
      url: "https://iamyannc.github.io/ggerror/",
      author: "iamyannc",
      description: "Simplifying and extanding ggplot2’s error geoms  ``` ggplot2 ```",
      tags: ["errors", "geom"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggdark",
      url: "https://github.com/nsgrantham/ggdark",
      author: "nsgrantham",
      description: "Dark Mode for ggplot2 Themes  ``` ggplot2 ```",
      tags: ["visualization", "general", "themes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "sugrrants",
      url: "https://pkg.earo.me/sugrrants",
      author: "earowang",
      description: "Supporting Graphs for Analysing Temporal Data with ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "calendar", "time-series"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "tvthemes",
      url: "https://github.com/Ryo-N7/tvthemes",
      author: "Ryo-N7",
      description: "ggplot2 Themes & Palettes from popular TV shows!  ``` ggplot2 ```",
      tags: ["visualization", "general", "palettes", "themes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggfittext",
      url: "https://wilkox.org/ggfittext",
      author: "wilkox",
      description: "ggplot2 geoms to fit text in a box  ``` ggplot2 ```",
      tags: ["visualization", "general", "text"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggparty",
      url: "https://github.com/martin-borkovec/ggparty",
      author: "martin-borkovec",
      description: "ggplot2 visualizations for the partykit package  ``` ggplot2 ```   ``` partykit ```",
      tags: ["visualization", "tree", "partykit"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "gggenes",
      url: "https://wilkox.org/gggenes",
      author: "wilkox",
      description: "ggplot2 geoms to draw gene arrow maps  ``` ggplot2 ```",
      tags: ["visualization", "general", "genetics"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "gggenomes",
      url: "https://thackl.github.io/gggenomes",
      author: "thackl",
      description: "a grammar of graphics for comparative genomics",
      tags: ["visualization", "genetics", "genomics"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "treemapify",
      url: "https://wilkox.org/treemapify",
      author: "wilkox",
      description: "Draw treemaps in ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "general", "treemap"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "lindia",
      url: "https://github.com/yeukyul/lindia",
      author: "yeukyul",
      description: "Create diagnostics plots for linear regression",
      tags: ["visualization", "general", "diagnostics", "regression"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "gghalves",
      url: "https://github.com/erocoar/gghalves",
      author: "erocoar",
      description: "gghalves adds half-geoms to ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggrastr",
      url: "https://github.com/VPetukhov/ggrastr",
      author: "vpetukhov",
      description: "Rasterize only specific layers of your plot",
      tags: ["visualization", "raster"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "ggpointdensity",
      url: "https://github.com/LKremer/ggpointdensity",
      author: "LKremer",
      description: "Introduces geom_pointdensity(): A cross between a scatter plot and a 2D density plot.  ``` geom_pointdensity() ```",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggsom",
      url: "https://github.com/oldlipe/ggsom",
      author: "oldlipe",
      description: "The aim of this package is to offer more variability of graphics based on the self-organizing maps.",
      tags: ["visualization", "SOM", "multi-dimensional", "parallel-coordinates"],
      category: DimensionalityReduction,
    ),
    ExtensionMetadata(
      name: "ggnewscale",
      url: "https://github.com/eliocamp/ggnewscale",
      author: "eliocamp",
      description: "Use multiple fill and colour scales in ‘ggplot2’.",
      tags: ["visualization", "general", "scales"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggh4x",
      url: "https://teunbrand.github.io/ggh4x/",
      author: "teunbrand",
      description: "Options for tailored facets, multiple colourscales and miscellaneous",
      tags: ["visualization", "general", "scales", "facets"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggarrow",
      url: "https://teunbrand.github.io/ggarrow/",
      author: "teunbrand",
      description: "Arrow geoms and arrow theme element with customisation options",
      tags: ["visualization", "arrows", "lines"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "legendry",
      url: "https://github.com/teunbrand/legendry",
      author: "teunbrand",
      description: "Extended legends and axes",
      tags: ["visualization", "guide", "legend", "axis"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggcharts",
      url: "https://thomas-neitmann.github.io/ggcharts/index.html",
      author: "thomas-neitmann",
      description: "Shorten the distance from data visualization idea to actual plot",
      tags: ["visualization", "general"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "humapr",
      url: "https://github.com/benskov/humapr",
      author: "benskov",
      description: "Visualise topographic human data with choropleths",
      tags: ["visualization", "general", "tabulation", "choropleth"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggshadow",
      url: "https://github.com/marcmenem/ggshadow",
      author: "marcmenem",
      description: "Draw a shadow below lines to make busy plots more aesthetically pleasing",
      tags: ["visualization", "general"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "ggseg",
      url: "https://github.com/LCBC-UiO/ggseg",
      author: "Athanasiamo",
      description: "Draw polygons of brain atlas segmentations",
      tags: ["visualization", "brain imaging"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "mdthemes",
      url: "https://github.com/thomas-neitmann/mdthemes",
      author: "thomas-neitmann",
      description: "‘ggplot2’ themes that render text as markdown/HTML",
      tags: ["visualization", "themes"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggwordcloud",
      url: "https://lepennec.github.io/ggwordcloud/",
      author: "lepennec",
      description: "A word cloud text geom for ‘ggplot2’.",
      tags: ["visualization", "text"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggasym",
      url: "https://jhrcook.github.io/ggasym/index.html",
      author: "jhrcook",
      description: "Asymmetric matrix plotting with multiple scales.",
      tags: ["visualization", "multi-dimensional", "matrix", "scales"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "gglorenz",
      url: "https://github.com/jjchern/gglorenz",
      author: "jjchern",
      description: "Plotting Lorenz curves with the blessing of ggplot2.",
      tags: ["visualization", "general", "statistics"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "hrbrthemes",
      url: "https://github.com/hrbrmstr/hrbrthemes",
      author: "hrbrmstr",
      description: "A compilation of extra {ggplot2} themes, scales and utilities, including a spell check function for plot label fields an",
      tags: ["theme", "typography"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggpattern",
      url: "https://github.com/trevorld/ggpattern",
      author: "coolbutuseless",
      description: "Pattern fills for ggplot2 geoms.",
      tags: ["visualization", "pattern"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "ggtext",
      url: "https://wilkelab.org/ggtext/",
      author: "Claus Wilke",
      description: "Improved text rendering support for ggplot2  ``` ggplot2 ```",
      tags: ["general", "theme", "typography"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "calendR",
      url: "https://r-coder.com/calendar-plot-r/",
      author: "R-CoderDotCom",
      description: "Ready to Print Monthly and Yearly Calendars",
      tags: ["visualization", "calendar", "time-series"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggip",
      url: "https://davidchall.github.io/ggip/",
      author: "davidchall",
      description: "Data visualization of IP addresses and networks",
      tags: ["visualization", "cyber", "space-filling curves"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "gglm",
      url: "https://graysonwhite.github.io/gglm/",
      author: "graysonwhite",
      description: "Grammar of Graphics for linear model diagnostic plots.",
      tags: ["visualization", "modeling", "diagnostic"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "econocharts",
      url: "https://r-coder.com/economics-charts-r/",
      author: "R-CoderDotCom",
      description: "Microeconomics and Macroeconomics Charts",
      tags: ["economics", "microeconomics", "macroeconomics"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ComplexUpset",
      url: "https://github.com/krassowski/complex-upset",
      author: "krassowski",
      description: "Visualize set intersections and add ggplot2 annotations  ``` ggplot2 ```",
      tags: ["visualization", "venn", "set", "intersections", "venn-diagram", "upset"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "ggchromatic",
      url: "https://teunbrand.github.io/ggchromatic/",
      author: "teunbrand",
      description: "Colourspace Scales for ‘ggplot2’",
      tags: ["visualization", "scales"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggheatmap",
      url: "https://github.com/XiaoLuo-boy/ggheatmap",
      author: "XiaoLuo-boy",
      description: "ggplot2 version of heatmap",
      tags: ["visualization", "heatmap"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "see",
      url: "https://github.com/easystats/see",
      author: "easystats",
      description: "Visualisation Toolbox for ‘easystats’ and Extra Geoms, Themes and Color Palettes for ‘ggplot2’",
      tags: ["visualizations", "statistics"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "directlabels",
      url: "https://tdhock.github.io/directlabels",
      author: "tdhock",
      description: "Framework for adding direct labels to lattice or ggplot2 plots.",
      tags: ["visualization", "direct-labels", "positioning", "general", "plot-labelling"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggHoriPlot",
      url: "https://github.com/rivasiker/ggHoriPlot",
      author: "rivasiker",
      description: "Horizon Plots for ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "general", "horizon-plot", "time-series"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggtrace",
      url: "https://rnabioco.github.io/ggtrace/",
      author: "sheridar",
      description: "Outline groups of data points using ggplot2",
      tags: ["visualization"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggESDA",
      url: "https://github.com/kiangkiangkiang/ggESDA",
      author: "kiangkiangkiang",
      description: "Exploratory Symbolic Data Analysis with ‘ggplot2’.",
      tags: ["visualization", "symbolic data", "interval-valued data"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "geomtextpath",
      url: "https://allancameron.github.io/geomtextpath/",
      author: "AllanCameron",
      description: "Create curved text and directly label lines in ggplot  ``` ggplot ```",
      tags: ["typography", "plot-labelling", "visualization"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggdensity",
      url: "https://jamesotto852.github.io/ggdensity",
      author: "jamesotto852",
      description: "Interpretable bivariate density visualization with highest density regions",
      tags: ["visualization", "density-estimation"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggtranscript",
      url: "https://dzhang32.github.io/ggtranscript/",
      author: "dzhang32",
      description: "Visualizing transcript structure and annotation using ggplot2  ``` ggplot2 ```",
      tags: ["visualization", "genetics", "genomics", "transcripts", "annotation"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "piecepackr",
      url: "https://trevorldavis.com/piecepackr",
      author: "trevorld",
      description: "Board game graphics",
      tags: ["board games", "geoms"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "oblicubes",
      url: "https://trevorldavis.com/R/oblicubes",
      author: "trevorld",
      description: "3D Rendering Using Obliquely Projected Cubes and Cuboids",
      tags: ["visualization", "geoms"],
      category: ThreeDimensionalProjection,
    ),
    ExtensionMetadata(
      name: "ggDoubleHeat",
      url: "https://github.com/PursuitOfDataScience/ggDoubleHeat",
      author: "PursuitOfDataScience",
      description: "A heatmap-like visualization tool",
      tags: ["visualization", "geoms"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "nflplotR",
      url: "https://nflplotr.nflverse.com",
      author: "mrcaseb",
      description: "‘nflplotR’ provides a set of functions to visualize National Football League analysis in ‘ggplot2’.",
      tags: ["general", "scales", "geoms", "images", "theme", "elements"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggbraid",
      url: "https://nsgrantham.github.io/ggbraid",
      author: "nsgrantham",
      description: "Braid ribbons in ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "general", "geoms"],
      category: FlowAlluvialSankey,
    ),
    ExtensionMetadata(
      name: "ggblanket",
      url: "https://davidhodge931.github.io/ggblanket/articles/ggblanket.html",
      author: "davidhodge931",
      description: "Simplify ggplot2 visualisation",
      tags: ["visualization"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggpie",
      url: "https://github.com/showteeth/ggpie",
      author: "showteeth",
      description: "Create pie and donut plot using ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "general", "pie", "donut", "rose pie"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "ggstar",
      url: "https://github.com/xiangpin/ggstar",
      author: "xiangpin",
      description: "Multiple Geometric Shape Point Layer for ‘ggplot2’",
      tags: ["visualization", "different shape points"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "ggarchery",
      url: "https://github.com/mdhall272/ggarchery",
      author: "mdhall272",
      description: "Flexible segment geoms with arrows for ‘ggplot2’",
      tags: ["visualization", "arrows"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "tidyterra",
      url: "https://github.com/dieghernan/tidyterra",
      author: "dieghernan",
      description: "‘ggplot2’ geoms for ‘terra’ rasters and vectors",
      tags: ["visualization", "raster", "spatial"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggseqplot",
      url: "https://maraab23.github.io/ggseqplot",
      author: "maraab23",
      description: "‘ggseqplot’ renders sequence plots using ggplot2.",
      tags: ["visualization", "sequence analysis"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggsurvfit",
      url: "https://www.danieldsjoberg.com/ggsurvfit/",
      author: "ddsjoberg",
      description: "Flexible Time-to-Event Figures",
      tags: ["visualization", "survival", "statistics"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggsector",
      url: "https://github.com/yanpd01/ggsector",
      author: "yanpd01",
      description: "Create sector plots using ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "geoms", "sector", "fan"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggterror",
      url: "https://github.com/mivalek/ggterrorbar",
      author: "mivalek",
      description: "Create T-errorbars like in THAT paper",
      tags: ["visualization", "geoms"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggragged",
      url: "https://mikmart.github.io/ggragged/",
      author: "mikmart",
      description: "Facets for panel layouts with ragged edges",
      tags: ["facets"],
      category: CompositeMultiPanel,
    ),
    ExtensionMetadata(
      name: "ggmapinset",
      url: "https://cidm-ph.github.io/ggmapinset/",
      author: "arcresu",
      description: "Add zoomed inset panels to your ggplot maps",
      tags: ["visualization", "spatial"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggmagnify",
      url: "https://github.com/hughjonesd/ggmagnify",
      author: "hughjonesd",
      description: "Create a magnified inset of part of a ggplot object.",
      tags: ["visualization", "geoms", "inset", "zoom", "magnification"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggblend",
      url: "https://mjskay.github.io/ggblend/",
      author: "mjskay",
      description: "Algebra of operations for blending, copying, adjusting, transforming, and compositing ggplot2 layers.",
      tags: ["visualization", "blending", "affine transformation", "layer algebra", "compositing"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "ggflowchart",
      url: "https://nrennie.github.io/ggflowchart/",
      author: "nrennie",
      description: "Create flowcharts using ggplot2.  ``` ggplot2 ```",
      tags: ["visualization", "flowchart", "network", "diagram"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggrain",
      url: "https://github.com/njudd/ggrain",
      author: "njudd",
      description: "Raincloud geom for ‘ggplot2’",
      tags: ["visualization", "general"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggoutlierscatterplot",
      url: "https://github.com/lukastay/ggoutlierscatterplot",
      author: "lukastay",
      description: "Visualize multidimensional outlier detection algorithms",
      tags: ["visualization", "outlier", "outliers", "scatterplot", "algorithms", "algorithm", "regression"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggautothemes",
      url: "https://github.com/lukastay/ggautothemes/tree/master",
      author: "lukastay",
      description: "Quickly see how different themes will look on your ggplot visual.",
      tags: ["visualization", "theme", "themeing", "color", "fill", "hue", "ggthemes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "AMR",
      url: "https://msberends.github.io/AMR/",
      author: "msberends",
      description: "Plotting AMR results for SIR categories, MIC values, and disk diffusion diameters",
      tags: ["visualization", "epidemiology", "color", "fill"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ichimoku",
      url: "https://shikokuchuo.net/ichimoku/",
      author: "shikokuchuo",
      description: "Visualization and Tools for Ichimoku Kinko Hyo Strategies",
      tags: ["visualization", "time-series", "finance", "trading", "candlestick"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "eheat",
      url: "https://github.com/Yunuuuu/eheat",
      author: "Yunuuuu",
      description: "Extended ComplexHeatmap with ggplot2",
      tags: ["visualization", "heatmap"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggstats",
      url: "https://larmarange.github.io/ggstats/",
      author: "larmarange",
      description: "Forest plots of model coefficients, Likert plots and custom proportions",
      tags: ["visualization", "p-values", "forest plot", "geoms", "positions", "statistics", "Likert"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggfoundry",
      url: "https://cgoo4.github.io/ggfoundry/",
      author: "cgoo4",
      description: "Shape Foundry & Geom for ‘ggplot2’.",
      tags: ["visualization", "geoms", "color", "fill", "shapes"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggalign",
      url: "https://yunuuuu.github.io/ggalign/",
      author: "Yunuuuu",
      description: "A ‘ggplot2’ Extension for Consistent Axis Alignment",
      tags: ["visualization", "composition", "heatmap"],
      category: MultiScaleCoordinate,
    ),
    ExtensionMetadata(
      name: "ggreveal",
      url: "https://weverthon.com/ggreveal/",
      author: "weverthonmachado",
      description: "Reveal a ‘ggplot’ Incrementally",
      tags: ["visualization", "presentation", "slides"],
      category: IntrospectionLayerEditing,
    ),
    ExtensionMetadata(
      name: "geofacet",
      url: "https://hafen.github.io/geofacet/",
      author: "hafen",
      description: "Easy faceting according to geographic position",
      tags: ["visualization", "facet", "facets", "geo", "geography", "composition"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "tidyplots",
      url: "https://tidyplots.org",
      author: "jbengler",
      description: "Tidy plots for scientific papers",
      tags: ["visualization", "general", "theme", "color", "statistics"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "rphylopic",
      url: "https://rphylopic.palaeoverse.org/",
      author: "willgearty",
      description: "Get and use silhouettes of organisms from PhyloPic",
      tags: ["visualization", "silhouettes", "images", "biology"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "deeptime",
      url: "https://williamgearty.com/deeptime",
      author: "willgearty",
      description: "Plotting tools for anyone working in deep time",
      tags: ["visualization", "earth sciences", "phylogenetics", "pattern", "color", "time-series"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "ggpcp",
      url: "https://github.com/heike/ggpcp",
      author: "heike",
      description: "Generalized Parallel Coordinate Plots in ggplot2",
      tags: ["visualization", "parallel coordinate plot", "multivariate", "categorical"],
      category: DimensionalityReduction,
    ),
    ExtensionMetadata(
      name: "ggvolcano",
      url: "https://cran.r-project.org/web/packages/ggvolcano/index.html",
      author: "Yaoxiang Li",
      description: "Provides tools for creating publication-ready volcano plots.",
      tags: ["visualization", "volcano_plot", "differential_expression"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggfootball",
      url: "https://aymennasri.github.io/ggfootball/",
      author: "aymennasri",
      description: "‘Plotting Football matches Expected Goals (xG) Stats with ‘Understat’ Data’.",
      tags: ["general", "football", "interactive", "visualization"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggfields",
      url: "https://pepijn-devries.github.io/ggfields/",
      author: "pepijn-devries",
      description: "Plot arrows or arrow fields, with accompanying scales and guides.",
      tags: ["visualization", "vector", "velocity", "angle", "spatial", "fields"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggsankeyfier",
      url: "https://pepijn-devries.github.io/ggsankeyfier/",
      author: "pepijn-devries",
      description: "visualise your data as Sankey or Alluvial diagrams",
      tags: ["visualization", "Sankey", "alluvial", "diagram", "flow", "network"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggpath",
      url: "https://mrcaseb.github.io/ggpath/",
      author: "mrcaseb",
      description: "Robust Image Rendering Support for ‘ggplot2’.",
      tags: ["general", "geoms", "images", "theme", "elements"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "gglinedensity",
      url: "https://hrryt.github.io/gglinedensity/",
      author: "hrryt",
      description: "Make heatmaps of line density using the DenseLines algorithm",
      tags: ["visualization", "general", "heatmap", "time-series", "density-estimation"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggsurveillance",
      url: "https://ggsurveillance.biostats.dev/",
      author: "ndevln",
      description: "Visualisations for Outbreak Investigation and Infectious Disease Surveillance",
      tags: ["visualization", "general", "scales", "time-series", "diverging bar charts", "population pyramids", "epicurves", "epigantt"],
      category: QualityControlTimeSeries,
    ),
    ExtensionMetadata(
      name: "gguapo",
      url: "https://eliansoutu.github.io/gguapo/",
      author: "eliansoutu",
      description: "Charts with unique styles inspired by renowned artists",
      tags: ["themes", "art", "styles", "general", "visualization"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggDNAvis",
      url: "https://ejade42.github.io/ggDNAvis/",
      author: "ejade42",
      description: "‘ggplot2’-Based Tools for Visualising DNA Sequences and Modifications",
      tags: ["DNA", "RNA", "genetics", "biology", "visualization", "visualisation", "customisable", "customizable", "medicine", "methylation", "sequence", "FASTQ"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggdibbler",
      url: "https://harriet-mason.github.io/ggdibbler/",
      author: "harriet-mason",
      description: "Uncertainty visualisation for signal supression",
      tags: ["uncertainty", "visualization", "general", "statistics"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggprop.test",
      url: "https://github.com/EvaMaeRey/ggprop.test",
      author: "EvaMaeRey",
      description: "A ggplot2 extension package to teach/learn the logic of the prop test.",
      tags: ["ggplot2 syntax", "longform graphical poems"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggsky",
      url: "https://uskovgs.github.io/ggsky",
      author: "uskovgs",
      description: "Draw all-sky maps in Galactic or equatorial coordinates with a Hammer-Aitoff projection",
      tags: ["visualization", "astronomy", "coordinates", "projection", "axis"],
      category: SpatialVectorField,
    ),
    ExtensionMetadata(
      name: "ggpop",
      url: "https://jurjoroa.github.io/ggpop",
      author: "jurjoroa",
      description: "Create icon-based representative population and geomcharts with Font Awesome icons",
      tags: ["visualization", "population", "icons", "fontawesome", "isotype"],
      category: HierarchicalPartition,
    ),
    ExtensionMetadata(
      name: "ggpointless",
      url: "https://flrd.github.io/ggpointless/",
      author: "flrd",
      description: "A Collection of Geometries, and Stats for ‘ggplot2’",
      tags: ["visualisation", "general"],
      category: StatisticalDiagnosisInference,
    ),
    ExtensionMetadata(
      name: "ggincerta",
      url: "https://github.com/maggiexma/ggincerta",
      author: "maggiexma",
      description: "Visualise uncertainty in spatial areal data through bivariate colour palettes, pixelation and glyphs",
      tags: ["uncertainty", "spatial", "sf", "maps", "visualization"],
      category: UncertaintyDistribution,
    ),
    ExtensionMetadata(
      name: "ggRandomForests",
      url: "https://github.com/ehrlinger/ggRandomForests",
      author: "ehrlinger",
      description: "Visually exploring random forests from the randomForestSRC package with ggplot2.",
      tags: ["visualization", "random forests", "randomForestSRC", "survival", "regression", "classification"],
      category: BioinformaticsGenomics,
    ),
    ExtensionMetadata(
      name: "ggcube",
      url: "https://matthewkling.github.io/ggcube/",
      author: "matthewkling",
      description: "Create 3D ggplots by combining a 3D coordinate specification with 3D layer functions.",
      tags: ["visualization", "general", "3D"],
      category: ThreeDimensionalProjection,
    ),
    ExtensionMetadata(
      name: "ggtaichi",
      url: "https://github.com/PursuitOfDataScience/ggtaichi",
      author: "PursuitOfDataScience",
      description: "Compare two data sources on a single grid of taichi (yin-yang) diagrams.",
      tags: ["visualization", "geoms"],
      category: ThemingPaletteAesthetic,
    ),
    ExtensionMetadata(
      name: "ggchord2",
      url: "https://github.com/nrennie/ggchord2",
      author: "nrennie",
      description: "Create chord diagrams with ‘ggplot2’.",
      tags: ["visualization", "chords", "arcs", "flows", "general", "categorical"],
      category: NetworkGraphTopology,
    ),
    ExtensionMetadata(
      name: "ggtintshade",
      url: "https://github.com/wkumler/ggtintshade",
      author: "wkumler",
      description: "Tinting and Shading Aesthetics for ‘ggplot2’.",
      tags: ["visualization", "color", "tint", "shade", "value", "saturation", "lightness", "aesthetic"],
      category: PatternFilterShader,
    ),
    ExtensionMetadata(
      name: "glydraw",
      url: "https://glycoverse.github.io/glydraw/",
      author: "fubin1999",
      description: "Draw customizable SNFG glycan cartoons in ggplot2 plots from structures or text notations.",
      tags: ["glycan", "SNFG", "biology", "scales"],
      category: TypographyTextRepel,
    ),
    ExtensionMetadata(
      name: "ggmultiglyph",
      url: "https://github.com/nrennie/ggmultiglyph",
      author: "aravind-j",
      description: "Multivariate Data Visualization using Glyphs.",
      tags: ["visualization", "multivariate", "glyphs", "geoms"],
      category: ThemingPaletteAesthetic,
    )
  ]
}

pub fn count_by_category() -> List(#(ExtensionCategory, Int)) {
  let all = all_167_extensions()
  [
    #(UncertaintyDistribution, count_cat(all, UncertaintyDistribution)),
    #(NetworkGraphTopology, count_cat(all, NetworkGraphTopology)),
    #(FlowAlluvialSankey, count_cat(all, FlowAlluvialSankey)),
    #(HierarchicalPartition, count_cat(all, HierarchicalPartition)),
    #(SpatialVectorField, count_cat(all, SpatialVectorField)),
    #(QualityControlTimeSeries, count_cat(all, QualityControlTimeSeries)),
    #(BioinformaticsGenomics, count_cat(all, BioinformaticsGenomics)),
    #(TypographyTextRepel, count_cat(all, TypographyTextRepel)),
    #(MultiScaleCoordinate, count_cat(all, MultiScaleCoordinate)),
    #(CompositeMultiPanel, count_cat(all, CompositeMultiPanel)),
    #(ThreeDimensionalProjection, count_cat(all, ThreeDimensionalProjection)),
    #(StatisticalDiagnosisInference, count_cat(all, StatisticalDiagnosisInference)),
    #(PatternFilterShader, count_cat(all, PatternFilterShader)),
    #(DimensionalityReduction, count_cat(all, DimensionalityReduction)),
    #(ThemingPaletteAesthetic, count_cat(all, ThemingPaletteAesthetic)),
    #(IntrospectionLayerEditing, count_cat(all, IntrospectionLayerEditing)),
  ]
}

fn count_cat(items: List(ExtensionMetadata), target: ExtensionCategory) -> Int {
  list.filter(items, fn(m) { m.category == target })
  |> list.length
}
