open Core
module Crdt = Sa_plan_crdt

(** Generates HTML / Multipart Email Payloads for the planning system. *)

let format_task_html (task: Crdt.Task.t) =
  let color = match task.status with
    | Done -> "green"
    | In_progress -> "blue"
    | In_review -> "orange"
    | Backlog -> "gray"
  in
  sprintf "<li><strong>[%s]</strong> %s - <span style='color:%s'>%s</span><br/><em>%s</em></li>"
    task.id task.title color (Crdt.Task_status.to_string task.status) task.description

let generate_email_payload ~to_addr ~subject state =
  let tasks = Map.data state in
  let list_items = List.map tasks ~f:format_task_html |> String.concat ~sep:"\n" in
  let html_body = sprintf "
    <html>
      <body>
        <h2>%s</h2>
        <p>This is an automated C3I tracking update generated by the ZigVM OCaml Harness.</p>
        <ul>
          %s
        </ul>
      </body>
    </html>
  " subject list_items in
  sprintf "To: %s\nSubject: %s\nContent-Type: text/html; charset=\"UTF-8\"\n\n%s"
    to_addr subject html_body
