open Zigvm_harness_support

let ensure_dir path =
  if Sys.file_exists path then () else Unix.mkdir path 0o755

let write_atomic path contents =
  let temporary = path ^ ".tmp" in
  let channel = open_out_bin temporary in
  Fun.protect
    ~finally:(fun () -> close_out_noerr channel)
    (fun () -> output_string channel contents);
  Sys.rename temporary path

let feature_ledger () =
  let implemented =
    Infranodus_feature.all
    |> List.filter (fun feature ->
           Infranodus_feature.status feature = Infranodus_feature.Implemented)
    |> List.length
  in
  Printf.sprintf
    "# InfraNodus OCaml Capability Ledger\n\n\
     Generated by `infranodus_artifacts`; do not edit rows manually.\n\n\
     - Total catalogued capabilities: **%d**\n\
     - Implemented with repository evidence: **%d**\n\
     - Planned or adapter-gated: **%d**\n\
     - Status law: `Implemented` means executable OCaml evidence exists; cataloguing a capability does not imply parity.\n\n%s"
    (List.length Infranodus_feature.all) implemented
    (List.length Infranodus_feature.all - implemented)
    (Infranodus_feature.to_markdown Infranodus_feature.all)

let scenarios_json () =
  let scenarios =
    Infranodus_scenario.feature_scenarios @ Infranodus_scenario.workflows
    |> List.map Infranodus_scenario.to_yojson
  in
  let evidence =
    Infranodus_scenario.evidence_manifest Infranodus_scenario.feature_scenarios
    |> List.map Infranodus_scenario.evidence_to_yojson
  in
  `Assoc
    [
      ("schema", `String "zigvm.infranodus.scenario-manifest.v1");
      ("scenarios", `List scenarios);
      ("evidence", `List evidence);
    ]
  |> Yojson.Safe.pretty_to_string

let page_evidence_name = function
  | Ui_page_registry.Observed -> "OBSERVED"
  | Ui_page_registry.Documented -> "DOCUMENTED"
  | Ui_page_registry.Composed -> "COMPOSED"
  | Ui_page_registry.Evidence_gated -> "EVIDENCE_GATED"
  | Ui_page_registry.Local_extension -> "LOCAL_EXTENSION"

let strings values = `List (List.map (fun value -> `String value) values)

let page_manifest_json () =
  let trace_for page_id =
    Ui_traceability.all
    |> List.filter (fun row -> String.equal row.Ui_traceability.page_id page_id)
    |> List.map (fun (row : Ui_traceability.row) ->
           `Assoc
             [
               ("scenario_id", `String row.scenario_id);
               ( "capability_id",
                 match row.capability_id with
                 | Some value -> `String value
                 | None -> `Null );
               ("component", `String row.component_name);
               ("state", `String row.state);
               ( "event_id",
                 match row.event_id with Some value -> `String value | None -> `Null );
               ("figma_frame", `String row.figma_frame);
               ("evidence_manifest", `String row.evidence_manifest);
             ])
  in
  `Assoc
    [
      ("schema", `String "zigvm.infranodus.page-manifest/v1");
      ("authority", `String "Ui_page_registry + Ui_traceability (pure OCaml)");
      ("page_count", `Int (List.length Ui_page_registry.all));
      ("capability_count", `Int (List.length Ui_page_registry.known_capability_ids));
      ("viewport_widths", `List [ `Int 390; `Int 768; `Int 1024; `Int 1440; `Int 1920 ]);
      ( "pages",
        `List
          (List.map
             (fun (page : Ui_page_registry.page) ->
               `Assoc
                 [
                   ("id", `String page.Ui_page_registry.id);
                   ("name", `String page.name);
                   ("route", `String (Ui_route.to_path page.route));
                   ("capability_ids", strings page.capability_ids);
                   ("states", strings page.states);
                   ("components", strings page.component_names);
                   ("evidence", `String (page_evidence_name page.evidence));
                   ( "evidence_note",
                     match page.evidence_note with
                     | Some value -> `String value
                     | None -> `Null );
                   ("traceability", `List (trace_for page.id));
                 ])
             Ui_page_registry.all) );
    ]
  |> Yojson.Safe.pretty_to_string

let authority_doc () =
  {|# InfraNodus OCaml Authority Ontology

This artifact records the implemented authority boundary. It complements the
full product ontology and the generated capability/scenario ledgers.

## Fractal Strata

| Stratum | Carrier | Authority | Observation |
|---|---|---|---|
| A: domain | `Workspace_domain`, graph intelligence, feature/scenario/Figma algebras | Pure OCaml | values, laws, canonical JSON |
| B: engines | `Workspace_store`, Dream, Bonsai, Playwright controller | OCaml interpreters | API responses, rendered DOM, media evidence |
| C: effects | SQLite actor, browser process, provider adapters, Figma MCP | Quarantined effects | events, artifacts, explicit unavailable states |

## Control Plane

OCaml owns commands, revisions, privacy confirmation, feature status,
responsive contracts, scenarios, viewports, assertions, tracing, screenshots,
and video lifecycle. Playwright is driven through the typed OCaml binding only.
Figma MCP is an external editor/interpreter: it may materialize the OCaml design
contract, but it cannot redefine tokens, breakpoints, component contracts, or
screen laws.

## Data Plane

Project state reaches SQLite only through `Workspace_store` and the harness
`Db` actor. Browser state reaches the system through Dream JSON and Bonsai
actions. Media evidence is an observation, never application state. Provider
imports and model inference remain typed adapter boundaries and must report
unavailability rather than fabricate results.

## Implemented Flow

`Bonsai event -> Dream command -> Workspace_domain.apply -> Workspace_store/Db
-> JSON projection -> Bonsai model -> DOM -> OCaml Playwright observation ->
PNG/WebM/trace verdict`.

## Safety And Evolution Laws

- Non-persistent projects never reach SQLite.
- Public sharing and deletion require explicit confirmation.
- Revisions reject stale writes.
- Feature status cannot be `Implemented` without named evidence.
- Every feature has a scenario contract at every canonical viewport.
- Figma initial/final interpretations are observationally equivalent.
- Browser evidence fails closed on console/page errors, overflow, undersized
  controls, pane-order violations, or missing tabs.

## Honest Boundary

The catalog contains 70 capabilities and every row has executable OCaml
evidence. Provider-bound operations still disclose live configured,
unavailable, and rate-limited deployment state. This is not a claim of full
InfraNodus proprietary-algorithm parity. Figma file
`MrrWJ0b0zhrmptQ7MW0IMA` contains editable Graph, Evidence, Analytics,
Research, and Project captures at nodes 5:2–9:2; raw capture frames do not
replace the OCaml token/component/screen/transition authority.
|}

let capture_latest_prompt ~history ~output =
  let needle = "get figma skills and superpowers for codex, mcp" in
  let input = open_in_bin history in
  let latest = ref None in
  Fun.protect
    ~finally:(fun () -> close_in_noerr input)
    (fun () ->
      try
        while true do
          let line = input_line input in
          if String.length line >= String.length needle then
            match String.index_opt line needle.[0] with
            | None -> ()
            | Some _ ->
                if
                  let rec contains at =
                    if at + String.length needle > String.length line then false
                    else if String.sub line at (String.length needle) = needle then true
                    else contains (at + 1)
                  in
                  contains 0
                then latest := Some line
        done
      with End_of_file -> ());
  match !latest with
  | None -> failwith "latest InfraNodus/Figma prompt not found in Codex history"
  | Some line ->
      ignore (Yojson.Safe.from_string line);
      write_atomic output (line ^ "\n");
      Digest.to_hex (Digest.string line)

let () =
  let root = ref "." in
  let history = ref None in
  Arg.parse
    [
      ("--root", Arg.Set_string root, "repository root");
      ("--capture-history", Arg.String (fun value -> history := Some value),
       "Codex history JSONL from which to preserve the latest exact prompt");
    ]
    (fun argument -> raise (Arg.Bad ("unexpected argument: " ^ argument)))
    "infranodus_artifacts [--root PATH] [--capture-history PATH]";
  let docs = Filename.concat !root "docs" in
  let ontology = Filename.concat docs "ontology" in
  let journal = Filename.concat docs "journal" in
  ensure_dir ontology;
  ensure_dir journal;
  write_atomic (Filename.concat docs "INFRANODUS_OCAML_PARITY_LEDGER.md")
    (feature_ledger ());
  write_atomic (Filename.concat ontology "INFRANODUS_SCENARIO_MANIFEST.json")
    (scenarios_json () ^ "\n");
  write_atomic (Filename.concat ontology "FIGMA_OCAML_DESIGN_CONTRACT.json")
    (Figma_design.Final.default () |> Figma_design.to_yojson
   |> Yojson.Safe.pretty_to_string |> fun value -> value ^ "\n");
  write_atomic (Filename.concat ontology "INFRANODUS_PAGE_MANIFEST.json")
    (page_manifest_json () ^ "\n");
  write_atomic (Filename.concat ontology "INFRANODUS_OCAML_AUTHORITY.md")
    (authority_doc () ^ "\n");
  (match !history with
  | None -> Printf.printf "generated InfraNodus contracts\n%!"
  | Some source ->
      let target = Filename.concat journal "20260803-infranodus-figma-source-prompt.jsonl" in
      let digest = capture_latest_prompt ~history:source ~output:target in
      Printf.printf "generated InfraNodus contracts; prompt-md5=%s\n%!" digest)
