#directory "+unix";;
#load "unix.cma";;
Unix.putenv "OCAMLPATH" "/home/an/NAS-setup/uos/toolchains/opam-ocaml/lib";;
#directory "/home/an/NAS-setup/uos/toolchains/opam-ocaml/lib";;
#use "topfind";;
#require "yojson,cryptokit,unix,mtime.clock.os";;
#directory "/tmp/ev-campaign-independent-direct-review-20260909/build/default/.ev_receipts.objs/byte";;
#load "/tmp/ev-campaign-independent-direct-review-20260909/build/default/ev_receipts.cma";;
let ws="/home/an/NAS-setup/uos/.uos-workspaces/ev98-peer-loop-20260909" and rev=Sys.argv.(1) and dst=Sys.argv.(2);;
let rec mkdir p=if not(Sys.file_exists p)then(mkdir(Filename.dirname p);Unix.mkdir p 0o700);;
let write p bytes=mkdir(Filename.dirname p);Ev_campaign.write p bytes;;
let names=List.map(fun n->"src/cepaf_gleam/"^n)["crdt/delta_state.gleam";"crdt/health_bridge.gleam";"crdt/mesh_sync.gleam";"crdt/mesh_wire.gleam";"crdt/delta_mesh_engine.gleam";"ha/deadman_freshness.gleam";"crdt/mesh_peer.gleam";"crdt/mesh_peer_actor.gleam";"crdt/mesh_zenoh_http.gleam";"crdt/mesh_zenoh_transport.gleam"]@List.map(fun n->"test/"^n^".gleam")["crdt_delta_state_test";"crdt_health_bridge_test";"crdt_mesh_sync_test";"deadman_freshness_test";"delta_mesh_engine_test";"mesh_sync_codec_test";"ev98_codec_runner";"mesh_peer_test";"mesh_peer_actor_test";"mesh_zenoh_test";"mesh_zenoh_live_test"]@["gleam.toml";"manifest.toml"];;
let refs=List.map(fun name->let path="apps/cepaf_gleam/"^name in let bytes=Receipt_validator.candidate_bytes ws rev path in write(dst^"/package/"^name)bytes;`Assoc["path",`String path;"sha256",`String(Receipt_validator.sha bytes)])names;;
let dependency_root="/home/an/NAS-setup/uos/apps/cepaf_gleam/build/dev/erlang";;
let rec entries depth path=if depth>12 then failwith "dependency depth";Array.to_list(Sys.readdir path)|>List.sort String.compare|>List.concat_map(fun name->let path=path^"/"^name in let st=Unix.lstat path in match st.Unix.st_kind with Unix.S_DIR->entries(depth+1)path|Unix.S_REG when st.st_size<=4194304->[path]|_->failwith("dependency shape "^path));;
let dependency_paths=List.concat_map(fun name->entries 0(dependency_root^"/"^name))["gleam_stdlib";"gleam_erlang";"gleam_otp";"gleam_json";"gleeunit"];;
if List.length dependency_paths>1024 then failwith "dependency count";;
let read p=let c=open_in_bin p in Fun.protect~finally:(fun()->close_in_noerr c)(fun()->really_input_string c(in_channel_length c));;
let deps=List.map(fun path->`Assoc["path",`String path;"sha256",`String(Receipt_validator.sha(read path))])dependency_paths;;
write(dst^"/source-manifest.json")(Yojson.Basic.pretty_to_string(`Assoc["source_revision",`String rev;"sources",`List refs;"dependencies",`List deps;"authority",`String "NONE"]));;
