#!/usr/bin/env ocaml
#use "topfind";;
#require "bos,str,unix";;
(* @agent_intent: Generate a Gleam main for the explicitly reviewed component
   tests. @laws: no shell; fixed module scope; no empty or silently reduced suite.
   This lexical generator is restricted to these repository test files. *)
let workspace = Filename.dirname (Filename.dirname (Unix.realpath Sys.argv.(0)))
let modules = ["ev_control_bounds_test"; "ev_control_boundary_test";
  "multi_agent_quorum_test"; "predictive_autoscaler_test";
  "predictive_autoscaler_hud_test"; "homeostasis_evolution_engine_test";
  "tui_15_evolutionary_cycles_test"; "homeostasis_evolution_hud_test";
  "multi_agent_quorum_hud_test"; "heijunka_scheduler_test"; "work_stealing_test";
  "delta_mesh_engine_test"; "deadman_freshness_test";
  "crdt_health_bridge_test"; "crdt_mesh_sync_test"; "rag_cache_mesh_test"]
let functions name =
  let path = workspace ^ "/apps/cepaf_gleam/test/" ^ name ^ ".gleam" in
  let expression = Str.regexp "^pub fn \\([a-z][a-z_0-9]*_test\\)()" in
  let channel = open_in path in
  let names = Fun.protect ~finally:(fun () -> close_in_noerr channel) (fun () ->
    let rec read found = match input_line channel with
      | line -> read (if Str.string_match expression line 0
          then Str.matched_group 1 line :: found else found)
      | exception End_of_file -> List.rev found in read []) in
  if names = [] then failwith ("No reviewed tests found in " ^ name);
  List.map (fun fn -> name ^ "." ^ fn) names
let calls = List.concat_map functions modules
let () = if List.length calls <> 168 then
  failwith (Printf.sprintf "Expected 168 reviewed tests, found %d" (List.length calls))
let body = String.concat "\n" (
  ["// Generated by tools/generate_ev_recovery_runner.ml; component observations only.";
   "import gleam/io"] @ List.map (fun name -> "import " ^ name) modules
  @ [""; "pub fn main() {"]
  @ List.concat_map (fun name -> ["  " ^ name ^ "()"; "  io.println(\"PASS " ^ name ^ "\")"]) calls
  @ ["  io.println(\"168 component checks passed; EV admission NOT_GRANTED\")"; "}"; ""])
let path = workspace ^ "/apps/cepaf_gleam/test/ev_recovery_runner.gleam"
let () =
  let replacing = match Array.to_list Sys.argv with
    | [_] -> false | [_; "--replace"] -> true
    | _ -> failwith "usage: generate_ev_recovery_runner.ml [--replace]" in
  if replacing then begin
    let ch = open_in path in
    let first = Fun.protect ~finally:(fun () -> close_in_noerr ch) (fun () -> input_line ch) in
    if first <> "// Generated by tools/generate_ev_recovery_runner.ml; component observations only."
    then failwith "refusing to replace a file without this generator's marker"
  end;
  let flags = if replacing then [Unix.O_WRONLY; Unix.O_TRUNC]
    else [Unix.O_WRONLY; Unix.O_CREAT; Unix.O_EXCL] in
  let fd = Unix.openfile path flags 0o600 in
  let channel = Unix.out_channel_of_descr fd in
  Fun.protect ~finally:(fun () -> close_out_noerr channel) (fun () ->
    output_string channel body; flush channel; Unix.fsync fd);
  (match Bos.OS.Cmd.run Bos.Cmd.(v "/home/an/NAS-setup/uos/toolchains/gleam-1.16.0/bin/gleam"
      % "format" % path) with
    | Ok () -> () | Error (`Msg message) -> failwith message);
  Printf.printf "Generated %d calls in %s\n" (List.length calls) path
