#use "topfind";;
#require "bos.setup,yojson";;
open Bos
open Yojson.Basic.Util
let get = function Ok x -> x | Error (`Msg e) -> failwith e
let s x = `String x
let strings xs = `List (List.map s xs)
let str k j = member k j |> to_string
let arr k j = member k j |> to_list
let assoc fields = `Assoc fields
let put fields j = match j with `Assoc old -> `Assoc (fields @ List.filter (fun (k,_) -> not (List.mem_assoc k fields)) old) | _ -> failwith "object required"
let read p = Yojson.Basic.from_file p
let write p text = get (OS.File.write (Fpath.v p) text)
let json p j = write p (Yojson.Basic.pretty_to_string j ^ "\n")
let sha p = let out,(_,rc) = get (OS.Cmd.run_out (Cmd.of_list ["sha256sum";p]) |> OS.Cmd.out_string) in if rc <> `Exited 0 then failwith ("hash failed: "^p); String.sub out 0 64
let prefix = "20260906-1655"
let base_path = "governance/planning/20260906-0817-uos-full-implementation-backlog.json"
let additions_path = "governance/planning/"^prefix^"-uos-execution-additions.json"
let manifest_path = "governance/planning/"^prefix^"-uos-sa-plan-execution-manifest.json"
let plan_path = "docs/design/"^prefix^"-uos-sa-plan-execution-plan.md"
let detail_path = "docs/design/"^prefix^"-uos-sa-plan-work-items.md"
let journal_path = "docs/journal/"^prefix^"-uos-sa-plan-execution-planning-journal.md"
let receipt_path = "governance/sources/"^prefix^"-uos-sa-plan-registration-receipt.json"
let plan_id = "uos/full-implementation/"^prefix
let db = "/home/an/NAS-setup/uos/var/sa-plan/uos.sqlite3"
let root = "/home/an/NAS-setup/uos"
let url p = "http://nas-1.tail55d152.ts.net:4100/files/"^p
let link title p = "["^title^"]("^url p^")"
let tags = "#fractal-l0 #fractal-l1 #fractal-l2 #fractal-l3 #fractal-l4 #fractal-l5 #fractal-l6 #fractal-l7 #fractal-l8 #fractal-l9 #zk-adr #km-triad #zero-muda #tailscale-web\n"
let deps t = arr "depends_on" t |> List.map to_string
let topological tasks =
  let ids = List.map (str "id") tasks in
  if List.length (List.sort_uniq String.compare ids) <> List.length ids then failwith "duplicate task ID";
  List.iter (fun t -> List.iter (fun d -> if not (List.mem d ids) then failwith ("unknown dependency "^d)) (deps t)) tasks;
  let rec go done_ids pending waves = match pending with [] -> List.rev waves | _ ->
    let ready,rest = List.partition (fun t -> List.for_all (fun d -> List.mem d done_ids) (deps t)) pending in
    if ready=[] then failwith "cyclic dependency graph";
    go (List.map (str "id") ready @ done_ids) rest (List.map (str "id") ready :: waves)
  in go [] tasks []
let checklist =
  let ids = ["TIME";"TAIL";"FRACT";"KM";"MUDA";"GRAPH";"DRIVE";"C1C8";"MATH";"9MOD";"REGR";"GLEAM";"HERMES";"ZIGVM";"MAX";"OTEL";"SOV";"JJ"] in
  let notes = ["Observed clock and hour/seconds filename";"Tailnet links supplied; browser acceptance remains open";"L0-L9 tags provided";"Source and plan links; bidirectional KM verification is W06";"No new runtime dependencies; full census is E04";"No foreign vector library added";"Physical storage untouched; Q02 verifies production path";"W/V tasks define browser obligations";"M/E/V tasks require actual metrics and proofs";"Modality-specific receipts required";"Registration verification is not application regression credit";"P01/P04 own real supervision integration";"K01/K03 own actual subprocess and oracle calls";"Kernel/VFS verification stays explicit";"MAX remains isolated";"E08/M04/P04 bind real traces";"No reviewer signature fabricated";"Standalone JJ; original OCaml unchanged"] in
  "<details>\n<summary>5-domain, 18-checkpoint planning checklist</summary>\n\n| Domain | Checkpoint | State | Evidence / obligation |\n|---|---|---|---|\n" ^
  String.concat "" (List.mapi (fun i id -> let d=if i<4 then 1 else if i<7 then 2 else if i<11 then 3 else if i<16 then 4 else 5 in Printf.sprintf "| D%d | CHK-%02d-%s | %s | %s |\n" d (i+1) id (if List.mem i [0;1;2;17] then "PLANNING_METADATA" else "IMPLEMENTATION_UNRUN") (List.nth notes i)) ids) ^ "\n</details>\n"
let () =
  let base=read base_path in
  let originals=arr "tasks" base and additions=arr "tasks" (read additions_path) in
  let tasks=List.map (fun t ->
    let id=str "id" t in
    let extra=match id with "E01"->["PLAN00"] | "E07"->["P01";"P03"] | "R01"->["P04";"K02";"K03";"Q01";"Q02";"N01"] | _->[] in
    let command,status=match id with
      | "PLAN00" -> "timeout 1200s ocaml tools/sa_plan_execution.ml selftest "^manifest_path,"Actual planning registration selftest; not implementation acceptance"
      | "E01" -> "timeout 1200s ocaml tests/acceptance/candidate_snapshot_test.ml","E01 supplies this standalone bootstrap probe before the E02 runner exists; E02 subsequently replays the shared acceptance fixture"
      | _ -> "timeout 1200s ocaml tests/acceptance/run.ml --backlog "^manifest_path^" --task "^id,"Acceptance runner and task adapter are delivered by E02 and the owning task; missing adapters are nonpassing" in
    put ["depends_on",strings(List.sort_uniq String.compare(deps t @ extra));"status",s "PLANNED";"source_kind",s(if List.mem id (List.map (str "id") originals) then "original-backlog" else "review-or-planning-gap");"validation_command",s command;"command_status",s status] t) (originals@additions) in
  let waves=topological tasks in
  let groups=arr "workstreams" base @ List.map (fun (id,title)->assoc["id",s id;"title",s title;"path",s detail_path]) ["P","sa-plan control and linked execution";"K","Real knowledge runtime and oracle execution";"Q","Compiler and production-test corrections";"N","Peer service recovery"] in
  let queue="uos-full-implementation-"^prefix^"-reserved" in
  let legacy=read "governance/testing/ocaml_gleam/20260905-2251-sa-plan-workflow-spec.json" in
  let legacy_tasks=List.map (fun t ->
    let id=str "id" t in
    let owner=match id with "OGL.00"->["E04"] | "OGL.01"->["M08";"H03"] | "OGL.02"->["E04";"E06"] | "OGL.03"->["E06";"M06"] | "OGL.91"->["E07";"E08"] | "OGL.92"->["E04";"R01"] | "OGL.93"->["V04";"V05";"V07"] | "OGL.94"->["E07";"R02"] | _ -> if String.ends_with ~suffix:".D" id then ["E04"] else if String.ends_with ~suffix:".V" id then ["E07";"V04"] else if String.ends_with ~suffix:".R" id then ["E07";"R02"] else ["E07"] in
    put ["master_tasks",strings owner;"registration_action",s "LINK_EXISTING_DO_NOT_DUPLICATE";"observed_state",s "available";"execution_authority",s "existing-sa-plan-writer"] t) (arr "tasks" legacy) in
  let finding_map=List.map (fun(id,owners)->assoc["finding",s id;"tasks",strings owners]) ["F01",["E03";"P01";"P02";"W04"];"F02",["K01";"K02";"K03"];"F03",["E03";"M01";"M04";"M05";"M07";"M08";"V05";"V06"];"F04",["E01";"E08";"R02";"R03"];"F05",["E01";"R03"];"F06",["Q01"];"F07",["E04";"E05";"K02"];"F08",["W01";"V01";"V02";"V03";"V04";"V07"];"F09",["Q02"]] in
  let workflows=assoc["id",s(plan_id^"/workflow");"name",s(plan_id^"/workflow");"kind",s "uos-programme";"tasks",strings(List.map (str "id") tasks)] :: List.map (fun g -> let id=str "id" g in assoc["id",s(plan_id^"/workflow/"^String.lowercase_ascii id);"name",s(plan_id^"/workflow/"^String.lowercase_ascii id);"kind",s "uos-workstream";"tasks",strings(List.filter(fun tid -> str "workstream" (List.find(fun t->str "id" t=tid)tasks)=id)(List.map(str "id")tasks))]) groups in
  let jobs=List.map(fun t -> let id=str "id" t in assoc["id",s(plan_id^"/job/"^id);"name",s(plan_id^"/job/"^String.lowercase_ascii id);"task_id",s id;"queue",s(if id="PLAN00" then queue^"-planning" else queue);"worker",s(if id="PLAN00" then "codex.plan-registration" else "uos.execution.worker.v1");"max_attempts",`Int 3;"workflow_id",s(plan_id^"/workflow/"^String.lowercase_ascii(str "workstream" t));"depends_on",member "depends_on" t;"external_dependencies",(if id="E07" then `List[assoc["plan_id",s "uos/ocaml-gleam-tests/v1";"task_id",s "OGL";"required_state",s "completed";"candidate_bound_receipt_required",`Bool true]] else `List[])]) tasks in
  let manifest=assoc[
    "schema",s "uos.sa-plan-execution.v1";"clock_utc",s "2026-09-06T16:55:55Z";"host_sync",assoc["leap_status",s "Normal";"system_offset_seconds_fast",`Float 0.000773245];
    "plan_id",s plan_id;"name",s plan_id;"title",s "UOS complete implementation and review-gap execution";"status",s "SPECIFICATION_READY_EXECUTION_STATE_IN_SA_PLAN";"database",s db;"queue",s queue;
    "state_authority",s "Sa_plan.Store; Markdown and this manifest define contracts, not mutable execution state";"dispatch_enabled",`Bool false;"temporal_service_connected",`Bool false;"native_workflow_meaning",s "Local durable history; running indicates registered/open, not executing agents";
    "per_command_timeout_seconds",`Int 1200;"task_lease_ns",s "1320000000000";"short_solver_budget_policy",s "Preserve stricter solver-specific bounds; 1200s is the outer command ceiling";
    "requirements",member "requirements" base;"workstreams",`List groups;"tasks",`List tasks;"jobs",`List jobs;"workflows",`List workflows;"eligibility_waves",`List(List.map strings waves);"finding_map",`List finding_map;
    "dynamic_expansion",assoc["required_for",strings["A01";"A07";"A08";"Z01";"Z04";"Z09";"Z10";"W01";"V02"];"policy",s "Register discovered standards clauses, source cases, routes, components and states as new sa-plan child tasks/jobs before execution; retain parent acceptance as open until the finite pinned census is covered. Graph revision changes use a reviewed extension plan and explicit dependency receipts, never silent replacement of a registered graph."];
    "legacy_plan",assoc["plan_id",s "uos/ocaml-gleam-tests/v1";"database",s "/home/an/NAS-setup/.uos-workspaces/ocaml-gleam-tests/state/ocaml_gleam_tests/sa_plan.sqlite3";"workflow_id",s "uos/ocaml-gleam-tests/v1/workflow";"task_count",`Int 75;"job_count",`Int 74;"workflow_count",`Int 1;"observed_tasks_available",`Int 75;"observed_job_attempts",`Int 0;"observed_workflow_state",s "running";"writer_ownership_changed",`Bool false;"tasks",`List legacy_tasks];
    "source_inputs",`List(List.map(fun path->assoc["path",s path;"sha256",s(sha path)]) [base_path;additions_path;"governance/sources/20260906-1620-codex-review-agy-forensic-reconciliation-receipt.json";"governance/testing/ocaml_gleam/20260905-2251-sa-plan-workflow-spec.json"]);
    "plan_document",s plan_path;"work_item_document",s detail_path;"receipt_path",s receipt_path;
    "task_execution_protocol",strings["Read source contract and candidate; classify current evidence";"Claim task and job with current ownership; evaluate local and linked-plan dependencies";"Record actual failing regression or bounded acceptance baseline";"Implement the smallest independently reviewable change in an isolated JJ workspace";"Build and execute required unit/system/BDD/property/fuzz/browser/formal checks";"Review candidate-bound observations independently; missing tools and unknown results are nonpassing";"Record receipt and journal activity, then complete job/task only when its acceptance gate is satisfied"];
    "limitations",strings["Planning registration is not implementation admission";"Native job claims do not enforce task dependencies; P01 supplies the required dispatch gate";"Default CLI status/tree target a legacy plan; use explicit task list and this plan's readback tool";"Legacy plan remains in its original store and is linked, not copied";"No external agents, services or deployment are started by registration"]] in
  json manifest_path manifest;
  let b=Buffer.create 30000 in
  let add=Buffer.add_string b in
  add "# UOS sa-plan execution implementation plan\n\n> For agentic workers: use the executing-plans workflow inline by default. Track every task, job and workflow in sa-plan; obtain additional-agent authorization before delegation.\n\n";
  add "**Goal:** Execute the complete original implementation mission and close every reviewed gap with candidate-bound runtime and formal evidence.\n\n**Architecture:** sa-plan owns task/job/workflow state. A typed Gleam execution boundary supervises bounded native workers; immutable source and acceptance manifests connect specifications to actual receipts. Existing detailed workstream plans remain the implementation specifications.\n\n**Tech Stack:** Gleam/OTP, Lustre/Wisp, Hermes OCaml/Bos/Dune, bounded Rust/Zenoh, ZigVM, Lean/Gospel/Quint/Z3, real browser tooling, standalone Jujutsu.\n\n";
  add("**Spec:** "^link "Original plan" "docs/design/20260906-0817-uos-full-implementation-plan.md"^" and "^link "Codex review" "docs/journal/20260906-1620-codex-review-agy-forensic-reconciliation.md"^".\n\n"^tags^"\n");
  add(String.concat " | "[link "This plan" plan_path;link "All work items" detail_path;link "Manifest" manifest_path;link "Registration receipt" receipt_path;"[Planning cockpit](http://nas-1.tail55d152.ts.net:4100/planning)"]^"\n\n");
  add "## Execution inventory and authority\n\nThe new programme contains 71 tasks: 60 original backlog tasks, 10 additional implementation tasks, and PLAN00 for this planning/registration work. It has one job per task and 13 local durable workflows (programme plus 12 workstreams). Only PLAN00 can be completed by this planning task; all 70 implementation items remain unrun.\n\nThe existing OCaml-to-Gleam plan remains authoritative for its 75 tasks, 74 jobs and one open workflow. It is linked without duplicating or resetting any task, attempt, result or history. P03 federates it; P01 enforces its completion receipts before E07 closes. Across the two stores, the tracked scope is 146 task records, 145 jobs and 14 workflows; these are management records, not passing tests.\n\n";
  add("Plan ID: `"^plan_id^"`. Canonical database: `"^db^"` (ignored runtime state, never committed or copied). The source manifest is immutable; status is read from sa-plan. Native workflow `running` means an open history, not a running agent. Native Temporal-style history does not imply a Temporal service, timers, signals or workers.\n\n");
  add "## Global constraints\n\n- Preserve every original OCaml source/test/fixture/Dune file byte-for-byte; external source trees are read-only evidence. No source ingestion before quiescence, exact revision, sanitized manifest, license and two-key checks.\n- Use standalone Jujutsu and isolated workspaces; serialize integration. Do not alter other agents' ownership or live stores.\n- Gleam owns supervision, intent, authorization and effects; Hermes owns bounded analysis/oracles; Zig owns deterministic runtime; Python stays in MAX.\n- Preserve the protected OS serial and zero Bevy/Graphite constraint. No destructive storage test.\n- Use 1,200-second outer command limits and short progress polling. Retain stricter per-query solver budgets, explicit process-tree cleanup and known satisfiable controls.\n- Every new document has an observed YYYYMMDD-HHSS prefix, Tailnet links, fractal tags and truthful 18-checkpoint component. All explanatory diagrams have matching ASCII and Mermaid forms.\n- No fixed PASS strings, synthetic hashes, invented reviewer approvals or unmeasured quality metrics confer admission.\n- Keep 35 original requirements, all nine reviewed findings, all 75 linked legacy tasks, and the full versioned FPP/SysML/Zenoh and route/component census in scope.\n- Register every newly discovered execution leaf and retry as sa-plan task/job/workflow activity before acting. Record pending reasons rather than dropping unsupported cases.\n\n";
  add "## Workstreams\n\n| ID | Workstream | Tasks |\n|---|---|---|\n";
  List.iter(fun g-> let gid=str "id" g in add("| "^gid^" | "^link (str "title" g)(str "path" g)^" | "^String.concat ", "(List.filter_map(fun t->if str "workstream" t=gid then Some(str "id" t)else None)tasks)^" |\n"))groups;
  add "\n## Ordered execution\n\nPLAN00 registers and verifies this programme. E01 is the first implementation task. E02 establishes the acceptance harness; E03 replaces false verification. Subsequent task eligibility comes from the complete dependency graph, not workstream names or apparent agent availability. Execution is inline by default.\n\n```text\n[PLAN00 Registration] --> [E01 Candidate]\n[E01 Candidate] --> [E02 Acceptance harness]\n[E02 Acceptance harness] --> [E03 Truthful gates]\n[E03 Truthful gates] --> [DAG Remaining implementation]\n[DAG Remaining implementation] --> [R02 Independent admission]\n[R02 Independent admission] --> [R03 Release handover]\n```\n\n```mermaid\nflowchart TD\n  PLAN00[\"Registration\"] --> E01[\"Candidate\"]\n  E01 --> E02[\"Acceptance harness\"]\n  E02 --> E03[\"Truthful gates\"]\n  E03 --> DAG[\"Remaining implementation\"]\n  DAG --> R02[\"Independent admission\"]\n  R02 --> R03[\"Release handover\"]\n```\n\nThe diagrams summarize the path; the exact task-level DAG below is authoritative. They do not impose a calendar promise or imply that a full language implementation is a short task.\n\n| Eligibility wave | Tasks |\n|---|---|\n";
  List.iteri(fun i ids->add(Printf.sprintf "| %d | %s |\n" (i+1)(String.concat ", " ids)))waves;
  add "\n## Task, job and workflow protocol\n\nEach task has a versioned fixture, exact file targets and an acceptance gate in the work-item document. Its job carries the task ID, dependencies, workflow, manifest digest and command ceiling. Jobs are registered on a dedicated reserved queue with dispatch disabled until P01 proves dependency and lease handling. This is deliberate scheduling state, not a claim of execution.\n\n";
  List.iteri(fun i x->add(Printf.sprintf "%d. %s.\n"(i+1)(to_string x)))(arr "task_execution_protocol" manifest);
  add "\nUse stable activity keys `{plan}/{task}/{candidate}/{stage}/{attempt}`. Stages are specification, red-test, implementation, verification, review and journal/admission; completion records actual results, never planned results. A replay of an already observed idempotent activity returns the same receipt. Changed candidate or payload requires a new attempt and renewed evidence. Solver UNKNOWN, skipped required tests, missing tools and stale receipts cannot complete a task.\n\nA task may span several bounded commands. Use a 1,320-second initial lease for a single 1,200-second command plus cleanup and recording; renew ownership through the implemented fenced API before subsequent work. Current native task/job interfaces are not claimed to provide full end-to-end fencing: P01/M05 prove that behavior.\n\n";
  add "## Browser, models and native completeness\n\nW01 must close the route/page/component/state manifest. V02 registers at least four semantic cycles for every page AND every component; profile/state expansions remain explicit. Each cycle observes behavior, compares it with intent/specification, applies a justified correction and re-verifies. Record keyboard/pointer actions, DOM/AST/accessibility state, links and anchors, screenshots, relevant video, network/console events, and timing. Repeating a smoke check four times does not close this requirement.\n\nA01/A07/A08 and Z01/Z04/Z09/Z10 are full pinned standards/API parents. Their census produces explicit child tasks, jobs and workflows for every clause/feature, including exclusions and unsupported states. Parent acceptance stays open until that finite census is accounted for. Register extension graphs with source/version/parent mappings; never silently mutate the already registered graph or invent completion counts.\n\nTDD specifies red/green development; BDD expresses observable journeys; unit/system/property/fuzz/mutation/fault/performance/formal tests each carry their own commands, seeds, oracles and evidence denominators. Mathematical validity does not alone certify look-and-feel or UX/CX. Include accessibility, human task outcomes and measured design criteria.\n\n";
  add "## Review findings and remaining obligations\n\n| Finding | Owning tasks |\n|---|---|\n";
  List.iter(fun f->add("| "^str "finding" f^" | "^String.concat ", "(arr "tasks" f|>List.map to_string)^" |\n"))finding_map;
  add "\nE01/R03 reconcile the three-tier handover, actual warning counts, signatures, exact revisions and the outdated handover tag. H01/M05/R03 cover timestamp and document-link corrections. N01 covers VM-1:8088. Q02 fixes test-local storage-validator coverage. K01-K03 make claimed journal, worker and differential behavior real. P01-P04 close the planning integration gaps.\n\n";
  add("## Commands\n\nUse the bound Store adapter for registration and selected-plan status; the existing CLI's generic `status`, `tree` and `sync` select its legacy InfraNodus plan.\n\n```sh\ncd "^root^"\ntimeout 1200s ocaml tools/sa_plan_execution.ml status "^manifest_path^" "^db^"\n\nUOS_SA_PLAN_DB="^db^" tools/sa-plan --format json task list "^plan_id^"\nUOS_SA_PLAN_DB="^db^" tools/sa-plan --format json job list "^queue^"\nUOS_SA_PLAN_DB="^db^" tools/sa-plan --format json workflow history "^plan_id^"/workflow\n```\n\nThe adapter also supports `validate`, `register`, `selftest` and a narrowly scoped `complete-planning` operation. Registration does not start execution workers. The final receipt reports actual Store readback, replay checks, available tasks, attempts and completed planning-only work.\n\n");
  add "## Completion gate\n\nR02 requires all implementation dependencies, linked-plan completion evidence, full finite standards/route/source census, actual browser and formal results, reviewed rollback and independent decisions for the same release candidate. R03 publishes accurate final documents and a new scoped tag after admission, preserving old tags as history. No calendar finish date is inferred from task count; estimates and resource envelopes are refined from actual leaf work and observed durations in sa-plan.\n\n";
  add checklist; write plan_path(Buffer.contents b);
  Buffer.clear b; add("# UOS sa-plan work-item contracts\n\n"^tags^"\n"^link "Execution plan" plan_path^" | "^link "Manifest" manifest_path^"\n\nThe manifest and native sa-plan IDs bind every task below. Original 60 task contracts are retained; additions and dependencies are explicit. Runtime state is read from sa-plan, not edited in this document.\n\n");
  List.iter(fun t->let id=str "id" t in
    add("## "^id^": "^str "title" t^"\n\n**Workstream:** "^str "workstream" t^". **Priority:** "^str "priority" t^". **Dependencies:** "^(if deps t=[] then "none" else String.concat ", "(deps t))^". **Requirements:** "^String.concat ", "(arr "requirements" t|>List.map to_string)^".\n\n**Files:**\n\n");
    List.iter(fun f->add("- "^str "mode" f^": `"^str "path" f^"`\n"))(arr "files" t);
    add "\n**Execution steps:**\n\n"; List.iteri(fun i x->add(Printf.sprintf "- [ ] Step %d: %s\n"(i+1)(to_string x)))(arr "implementation_steps" t);
    add("\n**Executable acceptance fixture:**\n\n```json\n"^Yojson.Basic.pretty_to_string(member "acceptance_case" t)^"\n```\n\n**Acceptance gate:** "^str "acceptance_gate" t^"\n\n**Replay contract:**\n\n```sh\n"^str "validation_command" t^"\n```\n\n"^str "command_status" t^".\n\n"))tasks;
  add "## Linked existing OCaml-to-Gleam tasks\n\nThese native records remain in `uos/ocaml-gleam-tests/v1`. They are not copied into the new plan. P03/P01 provide federation and completion gates.\n\n| Existing task | Title | Master obligations |\n|---|---|---|\n";
  List.iter(fun t->add("| "^str "id" t^" | "^str "title" t^" | "^String.concat ", "(arr "master_tasks" t|>List.map to_string)^" |\n"))legacy_tasks;
  add("\n"^checklist); write detail_path(Buffer.contents b);
  Printf.printf "Generated execution specification: %d tasks, %d jobs, %d workflows, %d waves, %d linked legacy tasks.\n%!" (List.length tasks)(List.length jobs)(List.length workflows)(List.length waves)(List.length legacy_tasks)
