#!/usr/bin/env ocaml
#use "topfind";;
#require "bos,str,unix,cryptokit";;
(* @agent_intent: Generate a Gleam main for the explicitly reviewed component
   tests. @laws: no shell; fixed module scope; no empty or silently reduced suite.
   This lexical generator is restricted to these repository test files. *)
let workspace = Filename.dirname (Filename.dirname (Unix.realpath Sys.argv.(0)))
let modules = ["ev_control_bounds_test"; "ev_control_boundary_test";
  "multi_agent_quorum_test"; "predictive_autoscaler_test";
  "predictive_autoscaler_hud_test"; "homeostasis_evolution_engine_test";
  "tui_15_evolutionary_cycles_test"; "homeostasis_evolution_hud_test";
  "multi_agent_quorum_hud_test"; "heijunka_scheduler_test"; "work_stealing_test";
  "delta_mesh_engine_test"; "deadman_freshness_test";
  "crdt_health_bridge_test"; "crdt_mesh_sync_test"; "rag_cache_mesh_test"]
let functions name =
  let path = workspace ^ "/apps/cepaf_gleam/test/" ^ name ^ ".gleam" in
  let expression = Str.regexp "^pub fn \\([a-z][a-z_0-9]*_test\\)()" in
  let channel = open_in path in
  let names = Fun.protect ~finally:(fun () -> close_in_noerr channel) (fun () ->
    let rec read found = match input_line channel with
      | line -> read (if Str.string_match expression line 0
          then Str.matched_group 1 line :: found else found)
      | exception End_of_file -> List.rev found in read []) in
  if names = [] then failwith ("No reviewed tests found in " ^ name);
  List.map (fun fn -> name ^ "." ^ fn) names
let calls = List.concat_map functions modules
let reviewed_call_count = 177
let reviewed_calls_sha256 = "e8b2c1393dde447e1eafa7f91225c47ef0c9c2844e765a315e1cd63ddf2bf869"
let call_set_sha256 calls =
  Cryptokit.hash_string (Cryptokit.Hash.sha256 ()) (String.concat "\n" calls ^ "\n")
  |> Cryptokit.transform_string (Cryptokit.Hexa.encode ())
let () = if List.length calls <> reviewed_call_count
    || call_set_sha256 calls <> reviewed_calls_sha256 then
  failwith (Printf.sprintf
    "Expected the exact %d reviewed calls (%s), found %d calls (%s)"
    reviewed_call_count reviewed_calls_sha256 (List.length calls) (call_set_sha256 calls))
let body = String.concat "\n" (
  ["// Generated by tools/generate_ev_recovery_runner.ml; component observations only.";
   "import gleam/io"] @ List.map (fun name -> "import " ^ name) modules
  @ [""; "pub fn main() {"]
  @ List.concat_map (fun name -> ["  " ^ name ^ "()"; "  io.println(\"PASS " ^ name ^ "\")"]) calls
  @ ["  io.println(\"177 component invocations passed; EV admission NOT_GRANTED\")"; "}"; ""])
let path = workspace ^ "/apps/cepaf_gleam/test/ev_recovery_runner.gleam"
let () =
  let replacing = match Array.to_list Sys.argv with
    | [_] -> false | [_; "--replace"] -> true
    | _ -> failwith "usage: generate_ev_recovery_runner.ml [--replace]" in
  let parent = Filename.dirname path in
  if Unix.realpath parent <> parent then failwith "runner directory contains a symlink";
  let parent_identity = Unix.lstat parent in
  let same_inode a b = a.Unix.st_dev = b.Unix.st_dev && a.Unix.st_ino = b.Unix.st_ino in
  let original = if replacing then begin
    let stat = Unix.lstat path in
    if stat.Unix.st_kind <> Unix.S_REG then failwith "runner must be a regular file, not a symlink";
    let ch = open_in path in
    let bytes = Fun.protect ~finally:(fun () -> close_in_noerr ch) (fun () ->
      if not (same_inode stat (Unix.fstat (Unix.descr_of_in_channel ch)))
      then failwith "runner changed while opening";
      let size = in_channel_length ch in
      if size > 1_048_576 then failwith "runner size bound";
      really_input_string ch size) in
    if not (String.starts_with
      ~prefix:"// Generated by tools/generate_ev_recovery_runner.ml; component observations only.\n" bytes)
    then failwith "refusing to replace a file without this generator's marker"
    else Some stat
  end else None in
  let temporary, channel = Filename.open_temp_file ~temp_dir:parent
    ".ev-recovery-runner-" ".gleam" in
  Fun.protect ~finally:(fun () -> close_out_noerr channel;
    if Sys.file_exists temporary then Unix.unlink temporary) (fun () ->
  output_string channel body; flush channel; Unix.fsync (Unix.descr_of_out_channel channel);
  close_out channel;
  (match Bos.OS.Cmd.run Bos.Cmd.(v "/home/an/NAS-setup/uos/toolchains/gleam-1.16.0/bin/gleam"
      % "format" % temporary) with
    | Ok () -> () | Error (`Msg message) -> failwith message);
  let current_parent = Unix.lstat parent in
  if current_parent.Unix.st_kind <> Unix.S_DIR
     || not (same_inode parent_identity current_parent) || Unix.realpath parent <> parent
  then failwith "runner directory changed while formatting";
  (match original with
   | Some stat ->
       let current = Unix.lstat path in
       if current.Unix.st_kind <> Unix.S_REG || not (same_inode stat current)
          || stat.Unix.st_size <> current.Unix.st_size || stat.Unix.st_mtime <> current.Unix.st_mtime
       then failwith "runner changed while formatting";
       Unix.rename temporary path
   | None -> Unix.link temporary path);
  );
  Printf.printf "Generated %d calls in %s\n" (List.length calls) path
