(* HW.7.1.1 — design tokens to generated CSS. See the mli: css is pure,
   every declaration is annotated with its token path, and both failure
   modes refuse rather than emit something plausible. *)

type token = { path : string; value : string }
type theme = { mode : string; bindings : (string * string) list }

type error =
  | Unknown_token of { mode : string; variable : string; path : string }
  | Unsafe_value of { path : string; value : string }
  | Mode_name_mismatch of { mode : string; missing : string list }
  | Duplicate_token of { path : string }

let describe = function
  | Unknown_token { mode; variable; path } ->
      Printf.sprintf
        "theme %s binds %s to the token %s, which does not exist — a missing colour renders as inherit, which looks fine and is not"
        mode variable path
  | Unsafe_value { path; value } ->
      Printf.sprintf
        "token %s has the value %S, which contains CSS syntax — it could close the declaration and inject rules, so it is refused rather than escaped"
        path value
  | Mode_name_mismatch { mode; missing } ->
      Printf.sprintf
        "theme %s does not bind %s — every mode must bind the SAME names, or the variable is undefined for whoever switched to that mode"
        mode (String.concat ", " missing)
  | Duplicate_token { path } ->
      Printf.sprintf "token %s is defined more than once — which value wins would be an accident of order" path

(* A value reaching a stylesheet is author text at a syntax boundary. *)
let unsafe_chars = [ ';'; '{'; '}'; '<'; '>'; '\n'; '\r' ]

let is_unsafe v =
  String.exists (fun c -> List.mem c unsafe_chars) v
  ||
  (* a CSS comment opener would swallow the rest of the block *)
  let n = String.length v in
  let rec go i = i + 1 < n && ((v.[i] = '/' && v.[i + 1] = '*') || go (i + 1)) in
  go 0

let check ~tokens ~themes =
  let sorted_tokens = List.sort (fun a b -> compare a.path b.path) tokens in
  let dups =
    let rec go = function
      | a :: (b :: _ as rest) ->
          (if a.path = b.path then [ Duplicate_token { path = a.path } ] else []) @ go rest
      | _ -> []
    in
    go sorted_tokens
  in
  let unsafe =
    sorted_tokens
    |> List.filter_map (fun t ->
           if is_unsafe t.value then Some (Unsafe_value { path = t.path; value = t.value })
           else None)
  in
  let known = List.map (fun t -> t.path) tokens in
  let unknown =
    themes
    |> List.sort (fun a b -> compare a.mode b.mode)
    |> List.concat_map (fun th ->
           th.bindings
           |> List.sort compare
           |> List.filter_map (fun (variable, path) ->
                  if List.mem path known then None
                  else Some (Unknown_token { mode = th.mode; variable; path })))
  in
  (* every mode binds the same NAMES — the union is the contract *)
  let all_names =
    themes |> List.concat_map (fun th -> List.map fst th.bindings) |> List.sort_uniq compare
  in
  let mismatched =
    themes
    |> List.sort (fun a b -> compare a.mode b.mode)
    |> List.filter_map (fun th ->
           let has = List.map fst th.bindings in
           match List.filter (fun n -> not (List.mem n has)) all_names with
           | [] -> None
           | missing -> Some (Mode_name_mismatch { mode = th.mode; missing }))
  in
  dups @ unsafe @ unknown @ mismatched

let banner =
  "/* GENERATED by Wiki_theme (HW.7.1.1) — do not hand-edit.\n\
  \   Every declaration below names the design token it came from, so a\n\
  \   reviewer can trace any pixel to its source. Regenerate and\n\
  \   byte-compare to detect a hand edit. */\n"

let css ~tokens ~themes =
  match check ~tokens ~themes with
  | _ :: _ as errors -> Error errors
  | [] ->
      let value_of path =
        match List.find_opt (fun t -> t.path = path) tokens with
        | Some t -> t.value
        | None -> "" (* unreachable: check proved every path resolves *)
      in
      let b = Buffer.create 1024 in
      Buffer.add_string b banner;
      (* sorted, so input order CANNOT change the output *)
      themes
      |> List.sort (fun a b -> compare a.mode b.mode)
      |> List.iter (fun th ->
             let selector =
               if th.mode = "light" then ":root"
               else Printf.sprintf ":root[data-theme=\"%s\"]" th.mode
             in
             Buffer.add_string b (Printf.sprintf "\n%s {\n" selector);
             th.bindings
             |> List.sort compare
             |> List.iter (fun (variable, path) ->
                    (* THE ANNOTATION IS THE FEATURE *)
                    Buffer.add_string b
                      (Printf.sprintf "  %s: %s; /* %s */\n" variable (value_of path) path));
             Buffer.add_string b "}\n");
      Ok (Buffer.contents b)
